export const DEFAULT_SECTORS = [
  { name: 'Lojistik', nameEn: 'Logistics', slug: 'LOGISTICS', iconName: 'truck', sortOrder: 1 },
  { name: 'Üretim', nameEn: 'Manufacturing', slug: 'MANUFACTURING', iconName: 'factory', sortOrder: 2 },
  { name: 'Perakende', nameEn: 'Retail', slug: 'RETAIL', iconName: 'store', sortOrder: 3 },
  { name: 'İnşaat', nameEn: 'Construction', slug: 'CONSTRUCTION', iconName: 'hard_hat', sortOrder: 4 },
  { name: 'Gıda Hizmetleri', nameEn: 'Food Service', slug: 'FOOD_SERVICE', iconName: 'restaurant', sortOrder: 5 },
  { name: 'Temizlik', nameEn: 'Cleaning', slug: 'CLEANING', iconName: 'cleaning_services', sortOrder: 6 },
  { name: 'Güvenlik', nameEn: 'Security', slug: 'SECURITY', iconName: 'security', sortOrder: 7 },
  { name: 'Depo', nameEn: 'Warehouse', slug: 'WAREHOUSE', iconName: 'warehouse', sortOrder: 8 },
  { name: 'Kurye', nameEn: 'Courier', slug: 'COURIER', iconName: 'delivery_dining', sortOrder: 9 },
  { name: 'Tarım', nameEn: 'Agriculture', slug: 'AGRICULTURE', iconName: 'agriculture', sortOrder: 10 },
  { name: 'Otomotiv', nameEn: 'Automotive', slug: 'AUTOMOTIVE', iconName: 'directions_car', sortOrder: 11 },
  { name: 'Tekstil', nameEn: 'Textile', slug: 'TEXTILE', iconName: 'checkroom', sortOrder: 12 },
  { name: 'Madencilik', nameEn: 'Mining', slug: 'MINING', iconName: 'construction', sortOrder: 13 },
  { name: 'Sağlık Destek', nameEn: 'Healthcare Support', slug: 'HEALTHCARE_SUPPORT', iconName: 'medical_services', sortOrder: 14 },
  { name: 'Konaklama', nameEn: 'Hospitality', slug: 'HOSPITALITY', iconName: 'hotel', sortOrder: 15 },
  { name: 'Bakım & Onarım', nameEn: 'Maintenance', slug: 'MAINTENANCE', iconName: 'build', sortOrder: 16 },
  { name: 'Şoför', nameEn: 'Driver', slug: 'DRIVER', iconName: 'local_shipping', sortOrder: 17 },
  { name: 'Teknisyen', nameEn: 'Technician', slug: 'TECHNICIAN', iconName: 'engineering', sortOrder: 18 },
  { name: 'Diğer', nameEn: 'Other', slug: 'OTHER', iconName: 'work', sortOrder: 99 },
] as const;
