import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  sector: Sector;
  sourceType: SourceType;
  websiteUrl?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const ALL_ENTRIES: CompanyEntry[] = [
  // ========== LOGISTICS_TRANSPORTATION (47) ==========
  { name: 'Royal Mail', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evri', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DPD UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yodel', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ocado', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stagecoach', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FirstGroup', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arriva UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Go-Ahead Group', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wincanton', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eddie Stobart', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clipper Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'XPO Logistics UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DHL UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FedEx UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPS UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parcelforce', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palletways', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuehne+Nagel UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Express', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Abellio UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TransPennine Express', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Northern Trains', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'South Western Railway', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Southeastern Railway', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Great Western Railway', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avanti West Coast', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'East Midlands Railway', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'c2c Rail', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chiltern Railways', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Freightliner UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GB Railfreight', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CEVA Logistics UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GXO Logistics UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhenus Logistics UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hermes Parcelnet', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TNT UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tuffnells Parcels', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'APC Overnight', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CitySprint', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Addison Lee', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norbert Dentressangle UK', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stobart Group', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bibby Distribution', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Culina Group', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nagel Langdons', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pall-Ex Group', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },

  // ========== MANUFACTURING (47) ==========
  { name: 'JCB', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rolls-Royce', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BAE Systems', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dyson', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reckitt', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unilever UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GlaxoSmithKline', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AstraZeneca Manufacturing', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smiths Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renishaw', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IMI plc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spirax-Sarco', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Halma plc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Weir Group UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Babcock International', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultra Electronics', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meggitt', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'QinetiQ', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cobham Advanced Electronic Solutions', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GKN Aerospace UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Martin-Baker', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leonardo UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thales UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chemring Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Senior plc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spectris', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rotork', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oxford Instruments', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Morgan Advanced Materials', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vesuvius plc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TT Electronics', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bodycote', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Castings plc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Triton Showers', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Haldex UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delphi Technologies UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cummins UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caterpillar UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perkins Engines', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toyota Manufacturing UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honda Manufacturing UK', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch UK Manufacturing', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pilkington Glass', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ibstock Brick', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marshalls plc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forterra Building Products', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },

  // ========== RETAIL_WAREHOUSING (47) ==========
  { name: 'Tesco', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sainsbury\'s', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASDA', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Morrisons', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lidl UK', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldi UK', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marks & Spencer', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primark', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B&Q', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Screwfix', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Argos', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wilko', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Poundland', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Home Bargains', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B&M Bargains', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'The Range', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wickes', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toolstation', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Halfords', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Currys', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Lewis Partnership', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Waitrose', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Co-op Food', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iceland Foods', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Farmfoods', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costco UK', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Booker Wholesale', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Makro UK', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bestway Wholesale', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Travis Perkins', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jewson', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Selco Builders Warehouse', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dunelm', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Next', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TK Maxx UK', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sports Direct', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JD Sports', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decathlon UK', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WHSmith', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Superdrug', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boots', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Holland & Barrett', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pets at Home', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smyths Toys', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Robert Dyas', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Card Factory', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Matalan', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },

  // ========== CONSTRUCTION (47) ==========
  { name: 'Balfour Beatty', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Taylor Wimpey', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Persimmon Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barratt Developments', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kier Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Morgan Sindall', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Skanska UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Laing O\'Rourke', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Galliford Try', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wates Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Willmott Dixon', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BAM Nuttall', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costain', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mace Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISG Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinci Construction UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Sisk & Son UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McLaren Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bellway Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Redrow Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Countryside Partnerships', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crest Nicholson', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bovis Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lovell Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Miller Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berkeley Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'St James Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Linden Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gleeson Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McCarthy Stone', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'J Murphy & Sons', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amey Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VolkerWessels UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tilbury Douglas', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McAlpine Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Robertson Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seddon Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Graham Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Multiplex UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bowmer & Kirkland', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henry Boot', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Keller Group UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Strabag UK', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Graham Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie UK Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Weston Homes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },

  // ========== FOOD_BEVERAGE (47) ==========
  { name: 'Greggs', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costa Coffee', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pret A Manger', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wetherspoons', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nando\'s UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wagamama', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Five Guys UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McDonald\'s UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KFC UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Burger King UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pizza Hut UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Domino\'s UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Papa John\'s UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Subway UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starbucks UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caffe Nero', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leon Restaurants', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Itsu', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tortilla UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Franco Manca', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dishoom', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bill\'s Restaurants', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prezzo', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zizzi', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASK Italian', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carluccio\'s', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Harvester', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toby Carvery', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beefeater', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brewers Fayre', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hungry Horse', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wingstop UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Popeyes UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Taco Bell UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tim Hortons UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wendy\'s UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yo! Sushi', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gourmet Burger Kitchen', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Byron Burgers', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honest Burgers', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flat Iron Steak', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cote Brasserie', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Miller & Carter', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chiquito', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Las Iguanas', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Slim Chickens UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'German Doner Kebab UK', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },

  // ========== AUTOMOTIVE (47) ==========
  { name: 'Jaguar Land Rover', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nissan Sunderland', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mini Oxford Plant', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bentley Motors', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aston Martin', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McLaren Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lotus Cars', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Morgan Motor Company', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caterham Cars', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'London Electric Vehicle Company', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alexander Dennis', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wrightbus', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Optare', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leyland Trucks', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dennis Eagle', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ford Dagenham', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vauxhall Motors Ellesmere Port', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toyota Burnaston', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honda Swindon', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BMW Hams Hall', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kwik Fit', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Halfords Autocentre', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arnold Clark', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pendragon', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lookers', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sytner Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inchcape UK', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vertu Motors', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marshalls Motor Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JCT600', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Listers Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jardine Motors', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peter Vardy', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TrustFord', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Motorpoint', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ATS Euromaster', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Tyres', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RAC', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AA Roadside', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Green Flag', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Snap-on UK', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euro Car Parts', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSF Car Parts', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LKQ Euro Car Parts', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unipart Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copart UK', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BCA UK', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TEXTILE_APPAREL (47) ==========
  { name: 'Burberry', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barbour', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Smedley', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johnstons of Elgin', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sunspel', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mulberry', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paul Smith', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alexander McQueen UK', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stella McCartney', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ted Baker', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hackett London', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dunhill', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Church\'s Shoes', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loake Shoemakers', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grenson Shoes', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tricker\'s', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crockett & Jones', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dr. Martens', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clarks', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hunter Boots', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belstaff', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivienne Westwood', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Temperley London', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boden', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Joules', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FatFace', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'White Stuff', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seasalt Cornwall', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Finisterre', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toast Clothing', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Whistles', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reiss', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AllSaints', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hobbs London', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Phase Eight', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monsoon', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'River Island', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'New Look', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Superdry', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jack Wills', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crew Clothing', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Charles Tyrwhitt', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TM Lewin', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hawes & Curtis', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Turnbull & Asser', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oliver Sweeney', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pantherella', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },

  // ========== MINING_ENERGY (47) ==========
  { name: 'BP', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shell UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SSE', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Grid', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Centrica', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Drax Group', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EDF Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ScottishPower', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'E.ON UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RWE UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orsted UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vattenfall UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Equinor UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TotalEnergies UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Harbour Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ithaca Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EnQuest', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Serica Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neptune Energy UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'INEOS Energy UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perenco UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Octopus Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bulb Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Good Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ecotricity', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OVO Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Utilita', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'So Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shell Energy Retail', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'British Gas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Npower', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UK Power Networks', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Western Power Distribution', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Northern Powergrid', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Electricity North West', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SP Energy Networks', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SGN', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cadent Gas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wales & West Utilities', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Northern Gas Networks', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RWE Renewables UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens Gamesa UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vestas UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SSE Renewables', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lightsource bp', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Statkraft UK', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renewable Energy Systems', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },

  // ========== HEALTHCARE (47) ==========
  { name: 'NHS England', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NHS Scotland', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NHS Wales', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bupa', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuffield Health', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spire Healthcare', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Circle Health Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HCA Healthcare UK', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ramsay Health Care UK', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Practice Plus Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Care UK', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HC-One', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barchester Healthcare', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Four Seasons Health Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anchor Hanover', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MHA Care Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hallmark Care Homes', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avery Healthcare', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caring Homes', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sunrise Senior Living UK', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Priory Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cygnet Health Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elysium Healthcare', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'St Andrew\'s Healthcare', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Voyage Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mencap', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Turning Point', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Change Grow Live', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WithYou', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Richmond Fellowship', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lifeways Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dimensions UK', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'United Response', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hft', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MacIntyre Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Creative Support', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Real Life Options', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sanctuary Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bright Horizons UK', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Busy Bees Nurseries', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'N Family Club', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Minster Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Exemplar Health Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maria Mallaband Care Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orchard Care Homes', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Runwood Homes', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Countess of Chester Hospital NHS', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },

  // ========== HOSPITALITY_TOURISM (47) ==========
  { name: 'Whitbread', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IHG Hotels UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Travelodge', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Greene King', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mitchells & Butlers', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Accor UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Radisson Hotel Group UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Best Western UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jurys Inn', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leonardo Hotels UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Britannia Hotels', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maldron Hotels UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'easyHotel', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Point A Hotels', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yotel', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'citizenM UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'The Edwardian Hotels', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Firmdale Hotels', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dorchester Collection UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mandarin Oriental London', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Four Seasons London', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Claridge\'s', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'The Savoy', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'The Ritz London', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marston\'s Pubs', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stonegate Pub Company', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Punch Pubs', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Star Pubs & Bars', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ei Group', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Young\'s Brewery Pubs', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fuller\'s Pubs', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shepherd Neame', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hall & Woodhouse', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Butlin\'s', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Haven Holidays', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Center Parcs UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parkdean Resorts', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pontins', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Warner Leisure Hotels', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Merlin Entertainments', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alton Towers', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thorpe Park', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Legoland Windsor', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Madame Tussauds London', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group UK', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },

  // ========== AGRICULTURE (47) ==========
  { name: 'Cranswick', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton Food Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Moy Park', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: '2 Sisters Food Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tulip Ltd', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pilgrim\'s Pride UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ABP Food Group UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dunbia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dawn Meats UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kepak UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Muller UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arla Foods UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dairy Crest', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'First Milk', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meadow Foods', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ornua UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wyke Farms', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barber\'s Farmhouse Cheese', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Young\'s Seafood', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Whitby Seafoods', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'The Seafood Company', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Associated British Foods', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Premier Foods', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bakkavor', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Greencore', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samworth Brothers', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oscar Mayer UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Finsbury Food Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Warburtons', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hovis', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roberts Bakery', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kingsmill', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Weetabix', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kellogg\'s UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nestle UK Factory', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mars UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondelez UK', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Burton\'s Biscuits', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fox\'s Biscuits', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McVitie\'s', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Walkers Crisps', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tyrrells', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pipers Crisps', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'G\'s Fresh', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Produce World Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berry Gardens', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thanet Earth', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },

  // ========== SECURITY (47) ==========
  { name: 'G4S UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Securitas UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mitie Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corps Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wilson James', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axis Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIS Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OCS Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loomis UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brink\'s UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ward Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lodge Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bidvest Noonan UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kingdom Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carlisle Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Constant Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Profile Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smart Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'First Response Group', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paramount Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultimate Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sight & Sound Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emprise Services', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Westgrove Group', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sword Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chubb Fire & Security UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADT UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Banham Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tyco Security UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NSI Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SSAIB Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SecuriGroup', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cordant Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clarity Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Excel Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enigma Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Watchful Eye Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Venture Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pilgrims Group', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Control Risks UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olive Group UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GardaWorld UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Security UK', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Interguard Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Proguard Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alert Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Titan Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },

  // ========== FACILITY_MANAGEMENT (47) ==========
  { name: 'Serco', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodexo UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OCS Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mitie Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman & Wakefield UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savills UK Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinci Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie Services UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Energies & Services UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Interserve', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amey Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kier Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capita Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'G4S Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atalian Servest UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Churchill Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kingdom Cleaning', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ABM UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emcor UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dalkia UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Robertson FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norland Managed Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Integral UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bellrock Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pareto FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Principle Cleaning', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nviro', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Incentive FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pinnacle Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Places for People FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mears Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wates FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kwest FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anabas', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acuity FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Derwent FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arcus FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ascona Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SFM UK', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cordant Cleaning', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NJC Cleaning', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Office & General Cleaning', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenon FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Recolight Recycling', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== METAL_STEEL (47) ==========
  { name: 'Tata Steel UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Liberty Steel UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sheffield Forgemasters', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'British Steel', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Outokumpu UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celsa Steel UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barrett Steel', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Severfield', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'William Hare Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Billington Holdings', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caunton Engineering', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metsec', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hadley Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubular Steel', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Murray Metals', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rainham Steel', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASD Metal Services', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metals4U', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kloeckner Metals UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Russel Metals UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novelis UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcoa UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rio Tinto Alcan UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sapa Aluminium UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hindalco UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brock Metal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'William King Foundry', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grainger & Worrall', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Castings Technology International', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thomas Dudley Foundry', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wallwork Heat Treatment', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bodycote Heat Treatment UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metalweb', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CMC UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EMR Metal Recycling', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sims Metal UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'European Metal Recycling', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'S Norton & Co', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ward Recycling', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CF Sherwood Metals', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metalysis', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Special Metals Wiggin', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ross & Catherall', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bruntcliffe Engineering', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Firth Rixson', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elkem UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Precision Castparts UK', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CHEMICALS_PLASTICS (47) ==========
  { name: 'INEOS', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Croda International', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johnson Matthey', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synthomer', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elementis', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Victrex', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Essentra', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RPC Group UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berry Global UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DS Smith Plastics', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coveris UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sealed Air UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klockner Pentaplast UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amcor UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smurfit Kappa UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondi UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ardagh Group UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rexam UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crown Holdings UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nampak Plastics UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Chemical UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SABIC UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solvay UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huntsman UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ashland UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lubrizol UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Scott Bader', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Akzo Nobel UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PPG Industries UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sherwin-Williams UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dulux (AkzoNobel)', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crown Paints', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hempel UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jotun UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'International Paint', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bostik UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mapei UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fosroc UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flexcrete Technologies', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tarmac Cement', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hanson Cement', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cemex UK', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aggregate Industries', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Breedon Group', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },

  // ========== ECOMMERCE_FULFILLMENT (47) ==========
  { name: 'Amazon UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASOS Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boohoo Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'THG Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Very Group', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ocado Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zalando UK Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Missguided Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PrettyLittleThing Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'In The Style Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gymshark Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Farfetch Warehouse UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Net-a-Porter Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Selfridges Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Harrods Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Lewis Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AO.com Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wayfair UK Warehouse', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Currys Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Argos Distribution', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Royal Mail Parcels', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DHL eCommerce UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hermes Fulfillment UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fulfilla', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huboo Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'James & James Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zendbox', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ShipBob UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Whistl', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'iForce Group', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clipper Logistics Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unipart Logistics', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TDG Logistics UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norbert Dentressangle Logistics UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arvato UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ingram Micro UK', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Geodis UK Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NFT Distribution', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bakers Logistics', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tesco Dotcom Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sainsbury\'s Online Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASDA Online Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Morrisons Online Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iceland Online Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dunelm Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B&Q Online Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wickes Online Fulfillment', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== TELECOMMUNICATIONS (47) ==========
  { name: 'BT Group', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Openreach', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Virgin Media O2', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vodafone UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sky', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Three UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EE', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TalkTalk', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Plusnet', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zen Internet', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyperoptic', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Community Fibre', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CityFibre', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gigaclear', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toob', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KCOM', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vonage UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gamma Communications', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Daisy Group', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colt Technology Services', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zayo Group UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'euNetworks UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SSE Telecoms', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cornerstone Networks', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arqiva', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cellnex UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MBNL', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samsung Networks UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telent Technology Services', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comms365', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maintel', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Exponential-e', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neos Networks', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Virgin Media Business', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BT Enterprise', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vodafone Business UK', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'County Broadband', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B4RN', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Truespeed', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zzoomm', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lightning Fibre', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jurassic Fibre', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swish Fibre', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netomnia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },

  // ========== OTHER (47) ==========
  { name: 'Royal Mint', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Network Rail', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thames Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anglian Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Severn Trent Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'United Utilities', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yorkshire Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'South West Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wessex Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Southern Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Northumbrian Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Welsh Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Affinity Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'South East Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Portsmouth Water', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transport for London', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Highways England', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HS2 Ltd', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crossrail', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heathrow Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gatwick Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manchester Airport Group', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Edinburgh Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Birmingham Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bristol Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'London City Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Biffa Waste', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veolia UK', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suez Recycling UK', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FCC Environment', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viridor', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renewi UK', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grundon Waste', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Countrystyle Recycling', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'British Red Cross', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'St John Ambulance', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RNLI', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mountain Rescue England', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HM Prison Service', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ministry of Defence Civilian', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Defence Equipment & Support', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sellafield Ltd', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuclear Decommissioning Authority', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AWE Aldermaston', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DVLA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Environment Agency', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Canal & River Trust', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
];

async function main() {
  const market = Market.UK;
  console.log(`Seeding ${ALL_ENTRIES.length} additional companies for UK market (part 2)...`);
  let created = 0, existed = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl ?? undefined, sector: entry.sector },
        create: { name: entry.name, slug, market, sector: entry.sector, websiteUrl: entry.websiteUrl, isActive: true },
      });
      const src = await prisma.crawlSource.findFirst({ where: { companyId: company.id } });
      if (!src) {
        await prisma.crawlSource.create({
          data: {
            companyId: company.id,
            name: `${entry.name} Jobs`,
            type: entry.sourceType as any,
            crawlMethod: CrawlMethod.HTML,
            seedUrls: [],
            schedule: '0 3 * * *',
            agingDays: 14,
            market,
            isActive: true,
          },
        });
        created++;
      } else { existed++; }
    } catch (e: any) {
      if (e.code === 'P2002') { existed++; } else { console.error(`Error: ${entry.name}:`, e.message); }
    }
  }
  console.log(`\nDone! Created: ${created}, Already existed: ${existed}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
