import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });
const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  websiteUrl: string | null;
  sector: Sector;
  sourceType: SourceType;
}

function slugify(text: string): string {
  return text.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// ========== HOSPITALITY_TOURISM (50) ==========
const HOSPITALITY_TOURISM: CompanyEntry[] = [
  { name: 'Taj Hotels', websiteUrl: 'https://www.tajhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oberoi Hotels', websiteUrl: 'https://www.oberoihotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ITC Hotels', websiteUrl: 'https://www.itchotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lemon Tree Hotels', websiteUrl: 'https://www.lemontreehotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott India', websiteUrl: 'https://www.marriott.com/en-us/search/findHotels.mi?countryCode=IN', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyatt India', websiteUrl: 'https://www.hyatt.com/en-US/hotel/india.html', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton India', websiteUrl: 'https://www.hilton.com/en/locations/india/', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Radisson Hotels India', websiteUrl: 'https://www.radissonhotels.com/en-us/destination/india', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Accor India', websiteUrl: 'https://all.accor.com/india/', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wyndham Hotels India', websiteUrl: 'https://www.wyndhamhotels.com/en-us/destination/india', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IHCL (Indian Hotels Company)', websiteUrl: 'https://www.ihcltata.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EIH Limited (Oberoi Group)', websiteUrl: 'https://www.eihltd.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leela Hotels', websiteUrl: 'https://www.theleela.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sarovar Hotels', websiteUrl: 'https://www.sarovarhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Holidays', websiteUrl: 'https://www.clubmahindra.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thomas Cook India', websiteUrl: 'https://www.thomascook.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cox & Kings India', websiteUrl: 'https://www.coxandkings.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MakeMyTrip', websiteUrl: 'https://www.makemytrip.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goibibo', websiteUrl: 'https://www.goibibo.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yatra.com', websiteUrl: 'https://www.yatra.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cleartrip', websiteUrl: 'https://www.cleartrip.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oyo Rooms', websiteUrl: 'https://www.oyorooms.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FabHotels', websiteUrl: 'https://www.fabhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Treebo Hotels', websiteUrl: 'https://www.treebo.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zostel', websiteUrl: 'https://www.zostel.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IRCTC Tourism', websiteUrl: 'https://www.irctctourism.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'India Tourism Development Corporation', websiteUrl: 'https://www.itdc.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuoni India', websiteUrl: 'https://www.kuoni.co.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SOTC Travel', websiteUrl: 'https://www.sotc.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kesari Tours', websiteUrl: 'https://www.kesari.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata SIA Airlines (Vistara)', websiteUrl: 'https://www.airvistara.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IndiGo Airlines', websiteUrl: 'https://www.goindigo.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air India', websiteUrl: 'https://www.airindia.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SpiceJet', websiteUrl: 'https://www.spicejet.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GoFirst Airlines', websiteUrl: 'https://www.flygofirst.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air Asia India', websiteUrl: 'https://www.airasia.com/en/in/', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Akasa Air', websiteUrl: 'https://www.akasaair.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airports Authority of India', websiteUrl: 'https://www.aai.aero', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GMR Airports', websiteUrl: 'https://www.gmrgroup.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GVK Airport Developers', websiteUrl: 'https://www.gvkairports.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berggruen Hotels', websiteUrl: 'https://www.berggruen.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sterling Holidays', websiteUrl: 'https://www.sterlingholidays.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Country Inn & Suites India', websiteUrl: 'https://www.countryinns.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comfort Inn India', websiteUrl: 'https://www.choicehotels.com/india', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ramada India', websiteUrl: 'https://www.wyndhamhotels.com/ramada', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Best Western India', websiteUrl: 'https://www.bestwestern.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bloom Hotels', websiteUrl: 'https://www.bloomhotels.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sayaji Hotels', websiteUrl: 'https://www.sayajihotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kamat Hotels', websiteUrl: 'https://www.kamathhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WelcomHeritage Hotels', websiteUrl: 'https://www.welcomheritagehotels.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
];

// ========== AGRICULTURE (50) ==========
const AGRICULTURE: CompanyEntry[] = [
  { name: 'ITC Agri Business', websiteUrl: 'https://www.itcportal.com/businesses/agri-business/', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPL Limited', websiteUrl: 'https://www.upl-ltd.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rallis India', websiteUrl: 'https://www.rallis.co.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Godrej Agrovet', websiteUrl: 'https://www.godrejagrovet.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayer CropScience India', websiteUrl: 'https://www.cropscience.bayer.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Syngenta India', websiteUrl: 'https://www.syngenta.co.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF India Agriculture', websiteUrl: 'https://www.basf.com/in/en/industries/agriculture.html', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PI Industries', websiteUrl: 'https://www.piindustries.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dhanuka Agritech', websiteUrl: 'https://www.dhanuka.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Insecticides India', websiteUrl: 'https://www.insecticidesindia.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coromandel International', websiteUrl: 'https://www.coromandel.biz', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chambal Fertilisers', websiteUrl: 'https://www.chambal.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Fertilizers Ltd', websiteUrl: 'https://www.nationalfertilizers.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IFFCO', websiteUrl: 'https://www.iffco.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat Narmada Valley Fertilizers', websiteUrl: 'https://www.gnfc.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rashtriya Chemicals & Fertilizers', websiteUrl: 'https://www.rcfltd.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zuari Agro Chemicals', websiteUrl: 'https://www.zuari.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kaveri Seed Company', websiteUrl: 'https://www.kaveriseeds.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuziveedu Seeds', websiteUrl: 'https://www.nuziveeduseeds.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahyco Seeds', websiteUrl: 'https://www.mahyco.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Advanta Seeds', websiteUrl: 'https://www.advantaseeds.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DCM Shriram Bioseed', websiteUrl: 'https://www.dcmshriram.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jain Irrigation Systems', websiteUrl: 'https://www.jains.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netafim India', websiteUrl: 'https://www.netafim.com/en/countries/india/', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EPC Industrie (Mahindra EPC)', websiteUrl: 'https://www.mahindraagri.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NCDEX', websiteUrl: 'https://www.ncdex.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Agricultural Cooperative Marketing', websiteUrl: 'https://www.nafed-india.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mother Dairy', websiteUrl: 'https://www.motherdairy.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amul (GCMMF)', websiteUrl: 'https://www.amul.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heritage Foods', websiteUrl: 'https://www.heritagefoods.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parag Milk Foods', websiteUrl: 'https://www.paragmilkfoods.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hatsun Agro Product', websiteUrl: 'https://www.hatsun.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VST Tillers Tractors', websiteUrl: 'https://www.vsttillers.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Tractors', websiteUrl: 'https://www.mahindratractors.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TAFE Tractors', websiteUrl: 'https://www.tafe.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eicher Tractors', websiteUrl: 'https://www.eichertractors.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Escorts Agri Machinery', websiteUrl: 'https://www.escorts.co.in/agri-machinery', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Deere India', websiteUrl: 'https://www.deere.co.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'New Holland Agriculture India', websiteUrl: 'https://agriculture.newholland.com/en/india/', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Claas India', websiteUrl: 'https://www.claas.co.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agritas (Agri fintech)', websiteUrl: 'https://www.agritas.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DeHaat', websiteUrl: 'https://www.agrevolution.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AgroStar', websiteUrl: 'https://www.agrostar.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ninjacart', websiteUrl: 'https://ninjacart.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Waycool Foods', websiteUrl: 'https://www.waycoolfoods.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WayCool Agri', websiteUrl: 'https://www.waycoolagri.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crofarm', websiteUrl: 'https://www.crofarm.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FarmEasy', websiteUrl: 'https://www.farmeasy.co', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BigHaat', websiteUrl: 'https://www.bighaat.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agribazaar', websiteUrl: 'https://www.agribazaar.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== SECURITY_SERVICES (50) ==========
const SECURITY_SERVICES: CompanyEntry[] = [
  { name: 'SIS Group', websiteUrl: 'https://www.sisgroup.sg', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tops Security', websiteUrl: 'https://www.topssecurity.co.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'G4S India', websiteUrl: 'https://www.g4s.com/en-in/', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Securitas India', websiteUrl: 'https://www.securitas.com/in/en/', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allied Universal India', websiteUrl: 'https://www.aus.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CISCO Security India', websiteUrl: 'https://www.ciscosecurity.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Checkmate Services', websiteUrl: 'https://www.checkmateservices.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jaguar Security', websiteUrl: 'https://www.jaguarsecurity.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brinks India', websiteUrl: 'https://www.brinks.com/en/countries/india.html', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur India', websiteUrl: 'https://www.prosegur.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CMS Info Systems', websiteUrl: 'https://www.cmsinfosystems.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Writer Corporation (Security)', websiteUrl: 'https://www.writercorporation.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bhadra International India', websiteUrl: 'https://www.bhadrainternational.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Force 1 Security', websiteUrl: 'https://www.force1security.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bombay Intelligence Security', websiteUrl: 'https://www.bisindia.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Globe Detective Agency', websiteUrl: 'https://www.globedetectiveagency.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hawk Eye Security', websiteUrl: 'https://www.hawkeyesecurity.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unipro Security', websiteUrl: 'https://www.uniprosecurity.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Premier Shield Security', websiteUrl: 'https://www.premiershield.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wackenhut India', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PINKERTON India', websiteUrl: 'https://www.pinkerton.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kroll India', websiteUrl: 'https://www.kroll.com/en/our-locations/india', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Control Risks India', websiteUrl: 'https://www.controlrisks.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Facility Security India', websiteUrl: 'https://in.issworld.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peregrine Risk Management', websiteUrl: 'https://www.peregrinerisk.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stateforce Security', websiteUrl: 'https://www.stateforcesecurity.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tier 1 Defense Security', websiteUrl: 'https://www.tier1defense.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alert Security India', websiteUrl: 'https://www.alertsecurityservices.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Associated Guard Security', websiteUrl: 'https://www.associatedguard.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aman Security', websiteUrl: 'https://www.amansecurity.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pyramid Cyber Security', websiteUrl: 'https://www.pyramidcybersecurity.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quick Heal Technologies', websiteUrl: 'https://www.quickheal.co.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'K7 Computing', websiteUrl: 'https://www.k7computing.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lucideus (SAFE Security)', websiteUrl: 'https://safe.security', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sequretek', websiteUrl: 'https://www.sequretek.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TAC Security', websiteUrl: 'https://www.tacsecurity.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arete Incident Response India', websiteUrl: 'https://areteir.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PwC Cybersecurity India', websiteUrl: 'https://www.pwc.in/services/cybersecurity.html', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deloitte Cyber India', websiteUrl: 'https://www2.deloitte.com/in/en/pages/risk/solutions/cyber-security.html', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KPMG Cyber India', websiteUrl: 'https://home.kpmg/in/en/home/services/advisory/risk-consulting/cyber-security.html', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Consultancy Security Practice', websiteUrl: 'https://www.tcs.com/cybersecurity', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HCL Cybersecurity', websiteUrl: 'https://www.hcltech.com/cybersecurity', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wipro Cyber Defense', websiteUrl: 'https://www.wipro.com/cybersecurity/', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Infosys Cybersecurity', websiteUrl: 'https://www.infosys.com/services/cyber-security.html', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Security India', websiteUrl: 'https://www.boschsecurity.com/in/en/', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honeywell Security India', websiteUrl: 'https://www.honeywell.com/in/en', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hikvision India', websiteUrl: 'https://www.hikvision.com/en/countries/india/', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CP Plus (Aditya Infotech)', websiteUrl: 'https://www.cpplusworld.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Matrix Comsec', websiteUrl: 'https://www.matrixcomsec.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Videonetics', websiteUrl: 'https://www.videonetics.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
];

// ========== FACILITY_MANAGEMENT (50) ==========
const FACILITY_MANAGEMENT: CompanyEntry[] = [
  { name: 'Sodexo India', websiteUrl: 'https://www.sodexo.com/home/countries/india.html', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Facility Services India', websiteUrl: 'https://in.issworld.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quess Corp', websiteUrl: 'https://www.quesscorp.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TeamLease Services', websiteUrl: 'https://www.teamlease.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE India', websiteUrl: 'https://www.cbre.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jones Lang LaSalle India', websiteUrl: 'https://www.jll.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman & Wakefield India', websiteUrl: 'https://www.cushmanwakefield.com/en/india', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Knight Frank India', websiteUrl: 'https://www.knightfrank.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colliers India', websiteUrl: 'https://www.colliers.com/en/india', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savills India', websiteUrl: 'https://www.savills.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OCS Group India', websiteUrl: 'https://www.ocs.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aramark India', websiteUrl: 'https://www.aramark.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group India', websiteUrl: 'https://www.compass-group.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elior India', websiteUrl: 'https://www.eliorgroup.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BVG Group India', websiteUrl: 'https://www.bvgindia.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Updater Services (UDS)', websiteUrl: 'https://www.updaterservices.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NoBrokerHood', websiteUrl: 'https://hood.nobroker.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pristine Logistics & Infraprojects', websiteUrl: 'https://www.pristinelogistics.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leads Connect Services', websiteUrl: 'https://www.leadsconnect.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manipal Facilities Management', websiteUrl: 'https://www.manipalbusiness.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ServiceMaster India', websiteUrl: 'https://www.servicemaster.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rentokil Initial India', websiteUrl: 'https://www.rentokil.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terminix India', websiteUrl: 'https://www.terminixindia.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perfection Integrated Services', websiteUrl: 'https://www.perfection.co.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSK Facility Management', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EMCURE Facility India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Integrated Facilities Management (IFM)', websiteUrl: 'https://www.ifmindia.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aditya Birla Facility Management', websiteUrl: 'https://www.adityabirlafacilitymanagement.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Realty Facility Mgmt', websiteUrl: 'https://www.tatarealty.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brigade Facilities Management', websiteUrl: 'https://www.brigadegroup.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embassy Services', websiteUrl: 'https://www.embassyservices.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HCL Facilities Management', websiteUrl: 'https://www.hcltech.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wipro Infrastructure Engineering', websiteUrl: 'https://www.wipro.com/infrastructure-engineering/', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Larsen & Toubro Realty', websiteUrl: 'https://www.ltrealty.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Omaxe Facility Management', websiteUrl: 'https://www.omaxe.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DLF Facility Management', websiteUrl: 'https://www.dlf.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prestige Facility Management', websiteUrl: 'https://www.prestigeconstructions.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sobha Facility Management', websiteUrl: 'https://www.sobha.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Godrej Properties FM', websiteUrl: 'https://www.godrejproperties.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Lifespace FM', websiteUrl: 'https://www.mahindralifespaces.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shapoorji Pallonji FM', websiteUrl: 'https://www.shapoorjipallonji.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piramal Realty FM', websiteUrl: 'https://www.piramalrealty.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Phoenix Mills FM', websiteUrl: 'https://www.phoenixmalls.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexus Malls FM', websiteUrl: 'https://www.nexusmalls.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Select City Walk FM', websiteUrl: 'https://www.selectcitywalk.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pacific Mall FM', websiteUrl: 'https://www.pacificmalls.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unity One Mall FM', websiteUrl: 'https://www.unityone.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ambience Mall FM', websiteUrl: 'https://www.ambiencemalls.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wave City Center FM', websiteUrl: 'https://www.wavecitycenter.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Logix City Centre FM', websiteUrl: 'https://www.logixgroup.in', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
];

// ========== METAL_STEEL (50) ==========
const METAL_STEEL: CompanyEntry[] = [
  { name: 'Tata Steel', websiteUrl: 'https://www.tatasteel.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JSW Steel', websiteUrl: 'https://www.jsw.in/steel', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Steel Authority of India (SAIL)', websiteUrl: 'https://www.sail.co.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jindal Steel & Power', websiteUrl: 'https://www.jindalpowerlimited.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jindal Stainless', websiteUrl: 'https://www.jindalstainless.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Essar Steel', websiteUrl: 'https://www.arcelormittalindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ArcelorMittal Nippon Steel India', websiteUrl: 'https://www.arcelormittalindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rashtriya Ispat Nigam (Vizag Steel)', websiteUrl: 'https://www.vizagsteel.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NMDC Limited', websiteUrl: 'https://www.nmdc.co.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vedanta Limited', websiteUrl: 'https://www.vedantalimited.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hindalco Industries', websiteUrl: 'https://www.hindalco.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Aluminium Company (NALCO)', websiteUrl: 'https://www.nalcoindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hindustan Copper Limited', websiteUrl: 'https://www.hindustancopper.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sterlite Copper', websiteUrl: 'https://www.sterlitetechnologies.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Metaliks', websiteUrl: 'https://www.tatametaliks.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mukand Steel', websiteUrl: 'https://www.mukand.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bhushan Power & Steel', websiteUrl: 'https://www.jswsteel.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uttam Galva Steels', websiteUrl: 'https://www.uttamgalva.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shyam Metalics & Energy', websiteUrl: 'https://www.shyammetalics.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kalyani Steel', websiteUrl: 'https://www.kalyanisteels.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sunflag Iron & Steel', websiteUrl: 'https://www.sunflag.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sarda Energy & Minerals', websiteUrl: 'https://www.sardamenergy.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSPL Limited (Baldota Group)', websiteUrl: 'https://www.mspl.co.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lloyds Metals & Energy', websiteUrl: 'https://www.lloydsgroupindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Man Industries', websiteUrl: 'https://www.manindustries.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ratnamani Metals & Tubes', websiteUrl: 'https://www.ratnamani.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'APL Apollo Tubes', websiteUrl: 'https://www.aplapollo.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maharashtra Seamless', websiteUrl: 'https://www.maharashtraseamless.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubacex India', websiteUrl: 'https://www.tubacex.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nava Bharat Ventures', websiteUrl: 'https://www.nbventures.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Pigments', websiteUrl: 'https://www.tatasteel.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Usha Martin', websiteUrl: 'https://www.ushamartin.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beekay Steel Industries', websiteUrl: 'https://www.beekaysteels.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Steel Strips Wheels', websiteUrl: 'https://www.sswl.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Automotive Stampings', websiteUrl: 'https://www.autostampings.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JBM Auto (Metal)', websiteUrl: 'https://www.jbmgroup.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharat Forge', websiteUrl: 'https://www.bharatforge.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ramkrishna Forgings', websiteUrl: 'https://www.rkforge.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amtek Auto (Forgings)', websiteUrl: 'https://www.amtek.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Titagarh Wagons (Steel)', websiteUrl: 'https://www.titagarh.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Electrotherm India', websiteUrl: 'https://www.electrotherm.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goodluck India', websiteUrl: 'https://www.goodluckindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VSL Wires', websiteUrl: 'https://www.vslwires.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rajratan Global Wire', websiteUrl: 'https://www.rajratan.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Precision Wires India', websiteUrl: 'https://www.precisionwires.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trident Techlabs', websiteUrl: 'https://www.tridentindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSTC Limited', websiteUrl: 'https://www.mstcindia.co.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metal Scrap Trade Corporation', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata International (Metals)', websiteUrl: 'https://www.tatainternational.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mishra Dhatu Nigam (Midhani)', websiteUrl: 'https://www.midhani-india.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
];

// ========== CHEMICALS_PLASTICS (50) ==========
const CHEMICALS_PLASTICS: CompanyEntry[] = [
  { name: 'Pidilite Industries', websiteUrl: 'https://www.pidilite.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Asian Paints', websiteUrl: 'https://www.asianpaints.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berger Paints India', websiteUrl: 'https://www.bergerpaints.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kansai Nerolac Paints', websiteUrl: 'https://www.nerolac.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Akzo Nobel India', websiteUrl: 'https://www.akzonobel.co.in', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPL Limited (Chemicals)', websiteUrl: 'https://www.upl-ltd.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF India', websiteUrl: 'https://www.basf.com/in/en.html', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Chemicals', websiteUrl: 'https://www.tatachemicals.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat Alkalies & Chemicals', websiteUrl: 'https://www.gacl.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deepak Nitrite', websiteUrl: 'https://www.deepaknitrite.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aarti Industries', websiteUrl: 'https://www.aartiindustries.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SRF Limited', websiteUrl: 'https://www.srf.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Navin Fluorine International', websiteUrl: 'https://www.navinfluorine.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fine Organic Industries', websiteUrl: 'https://www.fineorganics.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinati Organics', websiteUrl: 'https://www.vinatiorganics.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Balaji Amines', websiteUrl: 'https://www.balajiamines.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alkyl Amines Chemicals', websiteUrl: 'https://www.alkylamines.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Godrej Industries (Chemicals)', websiteUrl: 'https://www.godrejindustries.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Galaxy Surfactants', websiteUrl: 'https://www.galaxysurfactants.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solar Industries India', websiteUrl: 'https://www.solargroup.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HPCL (Petrochemicals)', websiteUrl: 'https://www.hindustanpetroleum.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BPCL Petrochemicals', websiteUrl: 'https://www.bharatpetroleum.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IOCL Petrochemicals', websiteUrl: 'https://www.iocl.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reliance Industries Petrochemicals', websiteUrl: 'https://www.ril.com/OurBusinesses/Petrochemicals.aspx', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GAIL Petrochemicals', websiteUrl: 'https://www.gailonline.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chemplast Sanmar', websiteUrl: 'https://www.chemplastsanmar.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DCM Shriram Chemicals', websiteUrl: 'https://www.dcmshriram.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sumitomo Chemical India', websiteUrl: 'https://www.sumitomo-chem.co.jp/english/india/', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat Fluorochemicals', websiteUrl: 'https://www.gfcl.co.in', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camlin Fine Sciences', websiteUrl: 'https://www.camlinfinesciences.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rossari Biotech', websiteUrl: 'https://www.rossari.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clean Science Technology', websiteUrl: 'https://www.cleansciencetech.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tatva Chintan Pharma Chem', websiteUrl: 'https://www.tatvachintan.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat Narmada Valley Chemicals', websiteUrl: 'https://www.gnfc.in', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Punjab Chemicals & Crop Protection', websiteUrl: 'https://www.punjabagrotech.in', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nocil Limited (Rubber Chemicals)', websiteUrl: 'https://www.nocil.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel India', websiteUrl: 'https://www.henkel.com/en-IN', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: '3M India', websiteUrl: 'https://www.3m.com/3M/en_IN/', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Chemical India', websiteUrl: 'https://www.dow.com/en-in.html', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DuPont India', websiteUrl: 'https://www.dupont.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanxess India', websiteUrl: 'https://www.lanxess.in', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clariant India', websiteUrl: 'https://www.clariant.com/en/Region-Pages/India', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huntsman India', websiteUrl: 'https://www.huntsman.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Momentive India', websiteUrl: 'https://www.momentive.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supreme Industries (Plastics)', websiteUrl: 'https://www.supremeindustriesindia.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Finolex Industries (PVC)', websiteUrl: 'https://www.finolexpipes.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jain Irrigation (Plastics)', websiteUrl: 'https://www.jains.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prince Pipes and Fittings', websiteUrl: 'https://www.princepipes.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Astral Limited (Pipes)', websiteUrl: 'https://www.astralpipes.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nilkamal Limited (Plastics)', websiteUrl: 'https://www.nilkamal.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
];

// ========== ECOMMERCE_CARGO (50) ==========
const ECOMMERCE_CARGO: CompanyEntry[] = [
  { name: 'Flipkart', websiteUrl: 'https://www.flipkart.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amazon India', websiteUrl: 'https://www.amazon.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swiggy', websiteUrl: 'https://www.swiggy.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zomato', websiteUrl: 'https://www.zomato.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delhivery', websiteUrl: 'https://www.delhivery.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meesho', websiteUrl: 'https://www.meesho.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Snapdeal', websiteUrl: 'https://www.snapdeal.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Myntra', websiteUrl: 'https://www.myntra.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nykaa', websiteUrl: 'https://www.nykaa.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pepperfry', websiteUrl: 'https://www.pepperfry.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Urban Ladder', websiteUrl: 'https://www.urbanladder.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bigbasket', websiteUrl: 'https://www.bigbasket.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grofers (Blinkit)', websiteUrl: 'https://www.blinkit.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dunzo', websiteUrl: 'https://www.dunzo.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zepto', websiteUrl: 'https://www.zeptonow.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swiggy Instamart', websiteUrl: 'https://www.swiggy.com/instamart', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PharmEasy', websiteUrl: 'https://www.pharmeasy.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netmeds', websiteUrl: 'https://www.netmeds.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: '1mg (Tata Health)', websiteUrl: 'https://www.1mg.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jiomart', websiteUrl: 'https://www.jiomart.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ajio', websiteUrl: 'https://www.ajio.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Cliq', websiteUrl: 'https://www.tatacliq.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Croma (Tata)', websiteUrl: 'https://www.croma.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reliance Digital', websiteUrl: 'https://www.reliancedigital.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ONDC', websiteUrl: 'https://ondc.org', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Udaan B2B', websiteUrl: 'https://www.udaan.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IndiaMART', websiteUrl: 'https://www.indiamart.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TradeIndia', websiteUrl: 'https://www.tradeindia.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Exporters India', websiteUrl: 'https://www.exportersindia.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limeroad', websiteUrl: 'https://www.limeroad.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Craftsvilla', websiteUrl: 'https://www.craftsvilla.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ShopClues', websiteUrl: 'https://www.shopclues.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paytm Mall', websiteUrl: 'https://paytmmall.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bluedart', websiteUrl: 'https://www.bluedart.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DTDC Courier', websiteUrl: 'https://www.dtdc.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ekart Logistics (Flipkart)', websiteUrl: 'https://www.ekartlogistics.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'XpressBees', websiteUrl: 'https://www.xpressbees.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shadowfax', websiteUrl: 'https://www.shadowfax.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ecom Express', websiteUrl: 'https://www.ecomexpress.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pickrr', websiteUrl: 'https://www.pickrr.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shiprocket', websiteUrl: 'https://www.shiprocket.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NimbusPost', websiteUrl: 'https://www.nimbuspost.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shyplite', websiteUrl: 'https://www.shyplite.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'India Post (Speed Post)', websiteUrl: 'https://www.indiapost.gov.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aramex India', websiteUrl: 'https://www.aramex.com/in/en', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DHL Express India', websiteUrl: 'https://www.dhl.com/in-en/home.html', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FedEx India', websiteUrl: 'https://www.fedex.com/en-in/', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TNT India', websiteUrl: 'https://www.tnt.com/express/en_in/', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPS India', websiteUrl: 'https://www.ups.com/in/en/Home.page', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porter (Logistics)', websiteUrl: 'https://www.porter.in', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
];

// ========== TELECOMMUNICATIONS (50) ==========
const TELECOMMUNICATIONS: CompanyEntry[] = [
  { name: 'Reliance Jio', websiteUrl: 'https://www.jio.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharti Airtel', websiteUrl: 'https://www.airtel.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vodafone Idea (Vi)', websiteUrl: 'https://www.myvi.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BSNL', websiteUrl: 'https://www.bsnl.co.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Communications', websiteUrl: 'https://www.tatacommunications.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Teleservices', websiteUrl: 'https://www.tatatelesrvices.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sterlite Technologies (STL)', websiteUrl: 'https://www.stl.tech', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tejas Networks', websiteUrl: 'https://www.tejasnetworks.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HFCL Limited', websiteUrl: 'https://www.hfcl.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ITI Limited', websiteUrl: 'https://www.itiltd-india.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hughes India (Satellite)', websiteUrl: 'https://www.hughes.com/in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VSAT India (Airtel)', websiteUrl: 'https://www.airtelb2b.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ACT Fibernet', websiteUrl: 'https://www.actcorp.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hathway Cable & Datacom', websiteUrl: 'https://www.hathway.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DEN Networks', websiteUrl: 'https://www.dennetworks.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siti Networks', websiteUrl: 'https://www.siticable.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dish TV India', websiteUrl: 'https://www.dishtv.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Sky (Tata Play)', websiteUrl: 'https://www.tataplay.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sun Direct TV', websiteUrl: 'https://www.sundirect.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Videocon D2H', websiteUrl: 'https://www.d2h.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson India', websiteUrl: 'https://www.ericsson.com/en/careers/working-at-ericsson/india', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia India', websiteUrl: 'https://www.nokia.com/en_IN/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei India', websiteUrl: 'https://www.huawei.com/en/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZTE India', websiteUrl: 'https://www.zte.com.cn/india/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cisco Systems India', websiteUrl: 'https://www.cisco.com/c/en_in/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Juniper Networks India', websiteUrl: 'https://www.juniper.net/en-us/company/index.html', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CommScope India', websiteUrl: 'https://www.commscope.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corning India (Optical)', websiteUrl: 'https://www.corning.com/in/en/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amdocs India', websiteUrl: 'https://www.amdocs.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comviva Technologies', websiteUrl: 'https://www.comviva.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Subex Limited', websiteUrl: 'https://www.subex.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Comviva', websiteUrl: 'https://www.comviva.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Exotel', websiteUrl: 'https://www.exotel.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Knowlarity', websiteUrl: 'https://www.knowlarity.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ozonetel', websiteUrl: 'https://www.ozonetel.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Servetel', websiteUrl: 'https://www.servetel.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MyOperator', websiteUrl: 'https://www.myoperator.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Route Mobile', websiteUrl: 'https://www.routemobile.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tanla Platforms', websiteUrl: 'https://www.tanla.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Videocon Telecommunications', websiteUrl: 'https://www.videoconmobiles.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MTNL', websiteUrl: 'https://www.mtnl.net.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jio Fiber', websiteUrl: 'https://www.jio.com/en-in/fiber/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airtel Xstream Fiber', websiteUrl: 'https://www.airtel.in/broadband/', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spectranet', websiteUrl: 'https://www.spectranet.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GTPL Hathway', websiteUrl: 'https://www.gtpl.net', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Excitel Broadband', websiteUrl: 'https://excitel.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'You Broadband', websiteUrl: 'https://www.youbroadband.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Asianet Broadband', websiteUrl: 'https://www.asianetbroadband.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Docomo (Teleservices)', websiteUrl: 'https://www.tatadocomo.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BSNL FTTH', websiteUrl: 'https://www.bsnl.co.in/opencms/bsnl/BSNL/services/broadband/bsnl_fiber.html', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
];

const ALL_ENTRIES: CompanyEntry[] = [
  ...HOSPITALITY_TOURISM,
  ...AGRICULTURE,
  ...SECURITY_SERVICES,
  ...FACILITY_MANAGEMENT,
  ...METAL_STEEL,
  ...CHEMICALS_PLASTICS,
  ...ECOMMERCE_CARGO,
  ...TELECOMMUNICATIONS,
];

async function main() {
  const market = Market.IN;
  console.log(`Seeding ${ALL_ENTRIES.length} companies for IN market (part 2)...`);

  let count = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl ?? undefined, sector: entry.sector },
        create: {
          name: entry.name,
          slug,
          market,
          sector: entry.sector,
          websiteUrl: entry.websiteUrl,
          isActive: true,
        },
      });

      await prisma.crawlSource.upsert({
        where: { id: company.id },
        update: {},
        create: {
          id: company.id,
          companyId: company.id,
          name: `${entry.name} Job Listings`,
          type: entry.sourceType as any,
          crawlMethod: CrawlMethod.HTML,
          seedUrls: [],
          schedule: '0 3 * * *',
          agingDays: 14,
          market,
          isActive: true,
        },
      });
      count++;
    } catch (e: any) {
      console.error(`  ✗ ${entry.name}: ${e.message}`);
    }
  }

  console.log(`\n✓ Seeded ${count}/${ALL_ENTRIES.length} companies for IN (part 2)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
