import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  sector: Sector;
  sourceType: SourceType;
  websiteUrl?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[ä]/g, 'ae').replace(/[ö]/g, 'oe').replace(/[ü]/g, 'ue').replace(/[ß]/g, 'ss')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const ALL_ENTRIES: CompanyEntry[] = [
  // ========== LOGISTICS_TRANSPORTATION (28) ==========
  { name: 'Gebrüder Weiss', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.gw-world.com' },
  { name: 'Bertschi AG', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emons Spedition', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.emons.de' },
  { name: 'Hagedorn Logistik', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kühne Logistics University', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meyer & Meyer Transport', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.meyermeyer.com' },
  { name: 'VTG Rail Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.vtg.com' },
  { name: 'Noerpel Gruppe', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.noerpel.de' },
  { name: 'Schenker Deutschland AG', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wackler Holding', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zeitfracht Gruppe', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.zeitfracht.de' },
  { name: 'Kravag Logistik', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elflein Spedition', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rüdinger Spedition', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kontio Transport', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heinrich Koch Internationale', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mainfreight Deutschland', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bolloré Logistics Deutschland', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Duvenbeck', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.duvenbeck.de' },
  { name: 'Waberer\'s Deutschland', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berger Logistik', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LKW Walter Deutschland', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schrader T+A Fahrzeugbau', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nagel-Group Frische', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wincanton Deutschland', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spedition Brucker', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DB Cargo', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.dbcargo.com/de-de' },
  { name: 'SBB Cargo Deutschland', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },

  // ========== MANUFACTURING (28) ==========
  { name: 'Festo Automation', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Weidmüller Interface', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Phoenix Contact Electronics', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sick AG', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.sick.com' },
  { name: 'Beckhoff Automation', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.beckhoff.com' },
  { name: 'Turck', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.turck.de' },
  { name: 'SEW-Eurodrive', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.sew-eurodrive.de' },
  { name: 'Lenze', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.lenze.com' },
  { name: 'Stihl Kettenwerk', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Festool', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.festool.de' },
  { name: 'Heidenhain', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.heidenhain.de' },
  { name: 'Voith', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://voith.com/de' },
  { name: 'Heraeus', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.heraeus.com' },
  { name: 'Zeiss Gruppe', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.zeiss.de' },
  { name: 'Schott AG', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.schott.com' },
  { name: 'Drägerwerk', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leybold', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pfeiffer Vacuum', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuka', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.kuka.com' },
  { name: 'Dürkopp Adler', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Homag Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chiron Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Index-Werke', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emag', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.emag.com' },
  { name: 'Heller Maschinenfabrik', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grob-Werke', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.grobgroup.com' },
  { name: 'Manz AG', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eisenmann SE', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },

  // ========== RETAIL (28) ==========
  { name: 'Netto Supermarkt', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.netto-online.de' },
  { name: 'Norma', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.norma-online.de' },
  { name: 'Real', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dohle Handelsgruppe', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bartels-Langness', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bünting', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.buenting.de' },
  { name: 'Coop Schleswig-Holstein', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wasgau', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.wasgau.com' },
  { name: 'Feneberg', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Combi Verbrauchermarkt', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Famila Nordost', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hit Handelsgruppe', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.hit.de' },
  { name: 'Marktkauf', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'V-Markt', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Denn\'s Biomarkt', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.denns-biomarkt.de' },
  { name: 'Basic Bio-Supermarkt', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Superbiomarkt', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Budni', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.budni.de' },
  { name: 'Müller Handel', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thalia Bücher', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ernsting\'s Family Lager', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kik Textilien', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TEDi Handel', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Woolworth Warenhaus', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thomas Philipps', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.thomas-philipps.de' },
  { name: 'Action Deutschland Lager', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mäc-Geiz', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Strauss Innovation', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CONSTRUCTION (28) ==========
  { name: 'Wolff & Müller Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swietelsky Baugesellschaft', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porr Deutschland Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurovia Deutschland Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kemna Bau Andreae', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bauer Spezialtiefbau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marti Deutschland', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aarsleff Deutschland', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berger Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.bergerbau.de' },
  { name: 'Reif Bauunternehmung', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heinrich Schmid', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.heinrich-schmid.de' },
  { name: 'Gottlob Rommel', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heitkamp Erd- und Straßenbau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Friedrich Wassermann Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baresel GmbH', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Köster Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Depenbrock Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.depenbrock.de' },
  { name: 'Oevermann', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schütte Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Diringer & Scheidel', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.dus.de' },
  { name: 'Streif Baulogistik', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hentschke Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gundlach Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wolfferts Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nüssli Deutschland', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peri Schalung', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Doka Deutschland Bau', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hoch- und Tiefbau Leipzig', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },

  // ========== FOOD_BEVERAGE (28) ==========
  { name: 'Dr. Oetker Produktion', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.oetker.de' },
  { name: 'Hochland Deutschland', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rügenwalder Mühle', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.ruegenwalder.de' },
  { name: 'Zentis', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.zentis.de' },
  { name: 'Coppenrath & Wiese', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Westfleisch Produktion', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vion Schlachthof', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Herta', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wiesenhof Geflügel', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bell Deutschland', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Campina Deutschland', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arla Foods Werk', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Milram', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schwartau Werke', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Develey', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.develey.de' },
  { name: 'Homann Feinkost', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frosta', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.frosta.de' },
  { name: 'Iglo Deutschland', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Augustiner Bräu', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paulaner Brauerei', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.paulaner.com' },
  { name: 'Erdinger Weißbräu', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oettinger Brauerei', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Binding-Brauerei', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hasseröder Brauerei', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gerolsteiner Brunnen', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.gerolsteiner.de' },
  { name: 'Vilsa-Brunnen', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adelholzener Alpenquellen', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rotkäppchen-Mumm', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },

  // ========== AUTOMOTIVE (28) ==========
  { name: 'Porsche Werk Stuttgart', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BMW Werk Dingolfing', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercedes Werk Bremen', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Opel Rüsselsheim', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ford Werk Köln', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tesla Grünheide', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Webasto Fahrzeugtechnik', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hella Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leoni Bordnetz', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahle Filtersysteme', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mann+Hummel', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.mann-hummel.com' },
  { name: 'Eberspächer Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brose Fahrzeugteile', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Benteler Automobiltechnik', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAF-Holland Fahrzeugtechnik', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Knorr-Bremse Systeme', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huf Hülsbeck', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stabilus Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Getrag', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BorgWarner Arnstadt', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dräxlmaier Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.draexlmaier.com' },
  { name: 'Nifco Deutschland', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elring Klinger Dichtungen', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kolbenschmidt', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Federal-Mogul Deutschland', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mubea', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.mubea.com' },
  { name: 'Woco Gruppe', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Progress-Werk Oberkirch', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TEXTILE (28) ==========
  { name: 'Trigema Produktion', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schiesser Wäschefabrik', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olymp Hemden', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seidensticker Hemden', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mey Bodywear', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Falke Strumpfwerke', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kunert Fashion', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SternPartner', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gössl Tracht', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lodenfrey', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roeckl Handschuhe', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marc Cain', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.marc-cain.com' },
  { name: 'Gerry Weber Produktion', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Betty Barclay', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brax Leineweber', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bugatti Textil', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cinque Fashion', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Strellson', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carl Gross', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Van Laack', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Digel', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olymp Level Five', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eterna Mode', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER, websiteUrl: 'https://www.eterna.de' },
  { name: 'Gardeur', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Strenesse', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'René Lezard', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Windsor Fashion', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Drykorn', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },

  // ========== MINING_ENERGY (28) ==========
  { name: 'Vattenfall Wärme Berlin', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'E.ON Energie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RWE Power', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EnBW Kernkraft', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uniper Kraftwerke', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LEAG Tagebau', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wintershall Dea Bergbau', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'STEAG Fernwärme', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MVV Energie Mannheim', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mainova Netzdienste', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pfalzwerke Netz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SWM München Strom', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'N-Ergie Netz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SachsenEnergie Netz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Süwag Energie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TEAG Netz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Entega Energie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Badenova Netz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EWE Netz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enercon Windkraft', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nordex Windenergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vestas Windkraft DE', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SMA Solar Wechselrichter', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SolarEdge Deutschland Werk', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enpal Solar', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zolar Solar', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wpd Onshore', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PNE Wind', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },

  // ========== HEALTHCARE (28) ==========
  { name: 'Universitätsklinikum Charité', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum München LMU', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum Tübingen', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum Freiburg', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum Düsseldorf', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum Dresden', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum Göttingen', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Universitätsklinikum Bonn', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klinikum Stuttgart', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klinikum Nürnberg', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klinikum Augsburg', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klinikum Dortmund', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klinikum Braunschweig', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klinikum Region Hannover', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fresenius Kabi', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stryker Medizintechnik DE', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Medtronic Werk DE', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ottobock Prothesen', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paul Hartmann Medizin', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hartmann Verbandmaterial', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lohmann & Rauscher', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mölnlycke Deutschland', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coloplast Deutschland', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ameos Klinikum', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Median Kliniken Reha', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Korian Pflege DE', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kursana Seniorenresidenz', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pro Seniore Pflege', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },

  // ========== HOSPITALITY_TOURISM (28) ==========
  { name: 'TUI Reisecenter', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DER Touristik Reisebüro', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alltours Reisecenter', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FTI Touristik', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schauinsland-Reisen Büro', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Steigenberger Hotels Küche', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dorint Hotels Küche', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maritim Hotels Küche', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lindner Hotels Service', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'H-Hotels Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novum Hotels Service', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Motel One Service', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B&B Hotels Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'a&o Hostels Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MEININGER Hotels Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deutsche Jugendherberge Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Center Parcs Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Landal GreenParks Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roompot Betrieb DE', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peter Pane Restaurant', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hans im Glück Restaurants', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Block House Restaurants', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vapiano Restaurants', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'dean&david Restaurants', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nordsee Restaurants', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BackWerk Gastronomie', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ditsch Brezel', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Circus Krone Betrieb', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },

  // ========== AGRICULTURE (28) ==========
  { name: 'BayWa Agrar', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agravis Agrar', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Raiffeisen Landwirtschaft', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Landgard Gartenbau', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DLG Landwirtschaft', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KWS Saat Forschung', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Südzucker Landwirtschaft', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nordzucker Rübenbau', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pfeifer & Langen', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cosun Deutschland Landw.', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PHW Gruppe Geflügel', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EW Group Zucht', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lohmann Breeders Zucht', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Big Dutchman Stall', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GEA Farm Melktechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DeLaval Melktechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lemken Pflüge', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grimme Kartoffeltechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Krone Erntetechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Claas Erntemaschinen', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fendt Traktoren', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Horsch Bodenbearbeitung', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amazone Landtechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pöttinger Erntetechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kverneland Pflüge', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rauch Düngetechnik', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Väderstad Deutschland Saat', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Förster-Technik Kälber', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },

  // ========== SECURITY_SERVICES (28) ==========
  { name: 'Securitas Werkschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kötter Wachschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Picard Bewachung', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klüh Objektschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wisag Werkschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stölting Wachdienst', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Power Bewachung', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gegenbauer Wachschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DSW Wachdienst', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SGS Bewachung', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ziemann Wachschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Protectas Objektschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur Werkschutz DE', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allied Universal Werkschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bundespolizei Wachschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Landesbetrieb Sicherheit', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Sicherheitsdienst', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hikvision Systemtechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dahua Systemtechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axis Communications Sicherheit', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avigilon Videotechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dallmeier Videotechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mobotix Kameras', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hekatron Brandmeldetechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Minimax Brandschutz', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telenot Alarmtechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Esser Brandmeldetechnik', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schrack Seconet Sicherheit', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },

  // ========== FACILITY_MANAGEMENT (28) ==========
  { name: 'Dussmann Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Facility Deutschland', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Apleona Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wisag Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piepenbrock Gebäudereinigung', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gegenbauer Gebäudetechnik', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klüh Cleaning', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stölting Gebäudemanagement', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dr. Sasse FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Götz Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Niederberger Reinigung', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goldbeck FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bäumler FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vetter Gebäude', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zeppelin FM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alba FM Berlin', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman Wakefield FM DE', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE FM Deutschland', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL FM Deutschland', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caverion Gebäudetechnik', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie Gebäudetechnik', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spie Gebäudetechnik', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CWS Hygiene', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Initial Hygiene DE', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rentokil Schädlingsbekämpfung', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anticimex Schädling DE', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Remondis Entsorgung', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veolia Umweltservice DE', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== METAL_STEEL (28) ==========
  { name: 'Salzgitter Flachstahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ThyssenKrupp Steel Duisburg', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ArcelorMittal Bremen', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dillinger Hütte Saar', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saarstahl Stahlerzeugung', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deutsche Edelstahlwerke Siegen', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BGH Edelstahl Siegen', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buderus Edelstahl Werk', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Georgsmarienhütte Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Badische Stahlwerke Kehl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hüttenwerke Krupp Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klöckner Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Knauf Interfer Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schmolz Bickenbach Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vallourec Rohre DE', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mannesmann Rohre', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Benteler Rohre', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grillo Zink', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aurubis Kupfer', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trimet Aluminium Essen', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novelis Aluminium DE', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aleris Aluminium', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norsk Hydro Aluminium DE', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Otto Fuchs Metall', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wieland Kupfer', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KME Kupfer', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wickeder Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wuppermann Stahl', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CHEMICALS_PLASTICS (28) ==========
  { name: 'BASF Ludwigshafen Werk', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covestro Leverkusen', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evonik Chemie', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanxess Chemie', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wacker Chemie Burghausen', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Altana Chemie', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brenntag Chemiedistribution', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clariant Chemie DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Chemie DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DuPont Chemie DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ineos Köln', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LyondellBasell Chemie', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Symrise Aromen', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel Klebstoffwerk', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika Bauchemie DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caparol Farben', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brillux Lacke', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FreiLacke Farben', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axalta Lacke DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PPG Lacke DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pöppelmann Kunststoff', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rehau Kunststoff', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ensinger Kunststoff', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Simona Kunststoffplatten', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reifenhäuser Extrusion', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KraussMaffei Spritzguss', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arburg Spritzguss', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engel Spritzguss DE', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },

  // ========== ECOMMERCE_CARGO (28) ==========
  { name: 'Amazon Versandzentrum DE', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zalando Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Otto Versand Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonprix Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baur Versand Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'About You Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mytheresa Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wayfair Lager DE', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Home24 Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Westwing Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zooplus Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZooRoyal Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DocMorris Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shop Apotheke Lager', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flaconi Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'baby-walz Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'myToys Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'windeln.de Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limango Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thomann Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alternate Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mindfactory Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Notebooksbilliger Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cyberport Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conrad Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reichelt Logistik', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arvato Fulfillment', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiege E-Fulfillment', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },

  // ========== TELECOMMUNICATIONS (28) ==========
  { name: 'Deutsche Telekom Technik', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vodafone Technik DE', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telefónica Technik DE', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Drillisch Mobilfunk', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Freenet Technik', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Congstar Technik', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mobilcom-Debitel Shop', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldi Talk Service', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lidl Connect Service', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lebara Technik', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lycamobile Technik', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deutsche Glasfaser Ausbau', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GfTD Glasfaser Ausbau', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OXG Glasfaser Ausbau', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inexio Glasfaser', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NetCologne Netz', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'M-net Netz', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EWE TEL Netz', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wilhelm.tel Netz', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DNS:NET Netz', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tele Columbus Kabel', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kabel Deutschland Netz', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unitymedia Kabel', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vantage Towers Mast', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'American Tower Mast DE', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eltel Networks Technik', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axians Netzwerk', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mugler Fernmelde', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },

  // ========== OTHER (18) ==========
  { name: 'Deutsches Rotes Kreuz Rettung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johanniter Rettungsdienst', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Malteser Rettungsdienst', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arbeiter-Samariter-Bund Rettung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADAC Pannenhilfe', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TÜV Rheinland Prüfung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TÜV Süd Prüfung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DEKRA Prüfung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GTÜ Prüfung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Diakonie Sozialarbeit', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caritas Sozialarbeit', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AWO Sozialarbeit', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayerisches Rotes Kreuz Rettung', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DRF Luftrettung Einsatz', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rettungsdienst Berlin Einsatz', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lichtblick Energie', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Green Planet Energie', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Naturstrom Energie', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
];

async function main() {
  const market = Market.DE;
  console.log(`Seeding ${ALL_ENTRIES.length} additional companies for DE market (part 2)...`);
  let created = 0, existed = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl ?? undefined, sector: entry.sector },
        create: { name: entry.name, slug, market, sector: entry.sector, websiteUrl: entry.websiteUrl, isActive: true },
      });
      const src = await prisma.crawlSource.findFirst({ where: { companyId: company.id } });
      if (!src) {
        await prisma.crawlSource.create({
          data: {
            companyId: company.id,
            name: `${entry.name} Stellenangebote`,
            type: entry.sourceType as any,
            crawlMethod: CrawlMethod.HTML,
            seedUrls: [],
            schedule: '0 3 * * *',
            agingDays: 14,
            market,
            isActive: true,
          },
        });
        created++;
      } else { existed++; }
    } catch (e: any) {
      if (e.code === 'P2002') { existed++; } else { console.error(`Error: ${entry.name}:`, e.message); }
    }
  }
  console.log(`\nDone! Created: ${created}, Already existed: ${existed}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
