import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  sector: Sector;
  sourceType: SourceType;
  websiteUrl?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const ALL_ENTRIES: CompanyEntry[] = [
  // ========== LOGISTICS_TRANSPORTATION (48) ==========
  { name: 'Keolis', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transdev', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RATP', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chronopost', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colissimo', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norbert Dentressangle', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'STEF', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heppner', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FM Logistic', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ID Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GeoPost', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe CAT', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mory Global', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gefco', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savino Del Bene FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'XPO Logistics FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colis Privé', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Relais Colis', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondial Relay', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SNCF Voyageurs', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SNCF Réseau', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SNCF Gares & Connexions', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fret SNCF', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transalliance', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Charles André', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Dupessey', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mazet Groupe', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perrenot Groupe', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lahaye Global Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delanchy Transports', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Malherbe Groupe', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DHL FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FedEx FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPS FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dachser FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuehne+Nagel FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DB Schenker FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clasquin', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GLS FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DPD FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhenus FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sealogis', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CMA CGM Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brittany Ferries', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RATP Dev', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thalys FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurostar FR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corsica Linea', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },

  // ========== MANUFACTURING (48) ==========
  { name: 'Safran', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airbus FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dassault Aviation', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thales', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Naval Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexter', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alstom', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Legrand', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Somfy', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Faurecia', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Plastic Omnium', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valeo FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe SEB', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BIC', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Essilor', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zodiac Aerospace', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Latécoère', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Daher', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Figeac Aero', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mecachrome', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lisi Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexans', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rexel', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MBDA FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ariane Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lacroix Electronics', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mersen', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aubert & Duval', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manitou', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Haulotte', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beneteau', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trigano', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saverglass', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arc International', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lisi Aerospace', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Liebherr FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sidel Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pellenc', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clextral', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKF FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NTN-SNR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schneider Electric FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leroy-Somer', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Voltaire', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurocopter FR', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Turbomeca', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Souriau', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Radiall', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },

  // ========== RETAIL_WAREHOUSING (48) ==========
  { name: 'Intermarché', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Super U', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monoprix', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Franprix', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Picard Surgelés', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lidl FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldi FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colruyt FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grand Frais', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Biocoop', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Naturalia', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netto FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leader Price', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cora FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boulanger', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Darty', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fnac', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cultura', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leroy Merlin FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Castorama', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brico Dépôt', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mr.Bricolage', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kiabi', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Halle', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gémo', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Promod', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camaïeu', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maisons du Monde', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conforama', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'But', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alinéa', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nocibé', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marionnaud', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yves Rocher', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sephora FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decathlon FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Go Sport', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intersport FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sport 2000 FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Action FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gifi', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Centrakor', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stokomani', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Foir Fouille', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jardiland', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Truffaut', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IKEA FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro FR', sector: Sector.RETAIL_WAREHOUSING, sourceType: SourceType.COMPANY_CAREER },

  // ========== CONSTRUCTION (48) ==========
  { name: 'Eiffage Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinci Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spie Batignolles', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colas', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurovia', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NGE', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rabot Dutilleul', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Demathieu Bard', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Léon Grosse', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fayat', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GCC', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sogea', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chantiers de l Atlantique', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GTM Bâtiment', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dumez', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eiffage Route', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eiffage Énergie', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinci Autoroutes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASF Vinci', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cofiroute', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spie FR', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Snef', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ortec Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sogea-Satom', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Immobilier', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexity', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kaufman & Broad', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Icade', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Altarea Cogedim', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eiffage Immobilier', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pierre & Vacances Construction', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GA Smart Building', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sogaris', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Legendre', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Pichet', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Giboire', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Duval', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Pelletier', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Point P', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loxam', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kiloutou', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dalkia', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clemessy', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cegelec', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Energies & Services', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eiffage Génie Civil', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Soletanche Bachy', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },

  // ========== FOOD_BEVERAGE (48) ==========
  { name: 'Lactalis', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danone Produits Frais', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pernod Ricard', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rémy Cointreau', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bel Group', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savencia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonduelle', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fleury Michon', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bigard', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Charal', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Socopa', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LDC Volailles', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terrena', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodiaal', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Candia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yoplait FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Andros', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pasquier', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brossard', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Banette', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paul Boulangerie', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bridor', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tipiak', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Labeyrie', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marie Surgelés', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'William Saurin', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lustucru', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Panzani', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kronenbourg', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Castel Frères', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Moët Hennessy', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orangina Suntory FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coca-Cola FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nestlé FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McDonald\'s FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Burger King FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quick FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flunch', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buffalo Grill', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hippopotamus', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Courtepaille', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Del Arte', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brioche Dorée', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Class Croûte', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodexo FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elior FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group FR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pomona Group', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },

  // ========== AUTOMOTIVE (48) ==========
  { name: 'Renault Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stellantis FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Michelin FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valeo Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Faurecia Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Plastic Omnium Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Continental FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peugeot', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Citroën', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DS Automobiles', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alpine Cars', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renault Trucks', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Volvo Trucks FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MAN Truck FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DAF Trucks FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iveco FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toyota FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Volkswagen FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BMW FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercedes-Benz FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyundai FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kia FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nissan FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honda FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tesla FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NTN FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKF Automotive FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schaeffler FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZF FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delphi FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hutchinson', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mécaplast', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Le Bélier', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novares', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Akwel', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gaussin', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Symbio', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Navya', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norauto', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Midas FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Speedy FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euromaster FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Feu Vert', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Point S FR', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roady', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carter-Cash', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Autodistribution', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TEXTILE_APPAREL (48) ==========
  { name: 'Hermès', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chanel', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dior', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Louis Vuitton', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kering FR', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Givenchy', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saint Laurent', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Balenciaga', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celine', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lacoste', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Petit Bateau', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aigle', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Armor Lux', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sandro', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maje', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Claudie Pierlot', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'The Kooples', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zadig & Voltaire', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Isabel Marant', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'A.P.C.', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jacquemus', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Courrèges', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanvin', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Balmain', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chloé', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loewe FR', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bottega Veneta FR', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berluti', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonpoint', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tartine et Chocolat', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jacadi', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Okaïdi', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Catimini', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IKKS', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jules', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celio', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Devred', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brice', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Etam', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Undiz', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Princesse Tam Tam', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aubade', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dim', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chantelle', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lejaby', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Beaumanoir', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivarte', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mulliez Textile', sector: Sector.TEXTILE_APPAREL, sourceType: SourceType.COMPANY_CAREER },

  // ========== MINING_ENERGY (48) ==========
  { name: 'Engie FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TotalEnergies Raffinage', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EDF Énergies Nouvelles', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orano', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Framatome', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CEA', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IRSN', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GRTgaz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GRDF', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Storengy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enedis', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RTE', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CNR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Voltalia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neoen', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Akuo Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valorem', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quadran Énergies', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Technique Solaire', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lhyfe', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McPhy Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HDF Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air Liquide Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rubis', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maurel & Prom', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perenco', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vermilion Energy FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Imerys', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eramet', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Société Le Nickel', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tereos Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Albioma', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Séché Environnement Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paprec Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suez Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dalkia Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Idex', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coriance', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enertime', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Direct Énergie', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alpiq FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vattenfall FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eni FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shell FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BP FR', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primagaz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Butagaz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Antargaz', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },

  // ========== HEALTHCARE (48) ==========
  { name: 'Sanofi FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Servier', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pierre Fabre', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ipsen', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'bioMérieux', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Guerbet', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stallergenes Greer', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Théa Pharma', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boiron', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Biogaran', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mylan FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teva FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pfizer FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roche FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novartis FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AstraZeneca FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johnson & Johnson FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Korian', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orpea', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ramsay Santé', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elsan', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivalto Santé', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Hospitalier Paris Saint-Joseph', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AP-HP', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospices Civils de Lyon', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Bordeaux', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Toulouse', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Lille', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Nantes', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Montpellier', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Strasbourg', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Nice', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Rennes', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHU de Grenoble', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Générale de Santé', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LNA Santé', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Colisée', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DomusVi', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emera', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bastide Le Confort Médical', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurofins Scientific', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cerba HealthCare', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synlab FR', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Biomnis', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air Liquide Medical', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vygon', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thuasne', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Urgo Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },

  // ========== HOSPITALITY_TOURISM (48) ==========
  { name: 'Accor FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Club Med FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pierre & Vacances', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Center Parcs FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maeva', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belambra Clubs', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VVF Villages', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vacancéole', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Odalys', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lagrange Vacances', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Louvre Hotels Group', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B&B Hotels FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ibis FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novotel FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercure FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pullman FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sofitel FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Campanile', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Première Classe', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kyriad', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'InterContinental FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyatt FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Disneyland Paris', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Futuroscope', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parc Astérix', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Puy du Fou', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compagnie des Alpes', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UCPA', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Voyageurs du Monde', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TUI FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Misterfly', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Promovacances', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Havas Voyages', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Selectour', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fram', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corsair International', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air France FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transavia FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'easyJet FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ryanair FR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Volotea', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'French Bee', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air Caraïbes', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Compagnie', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aéroports de Paris', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aéroport de Lyon', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },

  // ========== AGRICULTURE (48) ==========
  { name: 'InVivo', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axéréal', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivescia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agrial', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terrena Agriculture', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maïsadour', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euralis', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limagrain', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Roullier', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Timac Agro', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RAGT Semences', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vilmorin', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Triskalia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Even', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cooperl', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Avril', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sanders', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sica Atlantique', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Soufflet Agriculture', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cristal Union', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tereos', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saint Louis Sucre', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grands Moulins de Paris', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roquette Frères', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lesaffre', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lallemand FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jouffray-Drillaud', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cérience', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Syngenta FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayer CropScience FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corteva FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF Agri FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'De Sangosse', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goëmar', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'John Deere FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CLAAS FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuhn Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manitou Agriculture', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pöttinger FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Massey Ferguson FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'New Holland FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kubota FR', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSA', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chambre d Agriculture', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'INRAE', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIRAD', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ONF', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'France Bois Forêt', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },

  // ========== SECURITY (48) ==========
  { name: 'Securitas FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Onet Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiducial Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seris Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brink\'s FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loomis FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Scutum', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stanley Security FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADT FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Verisure FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sogetrel', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gendarmerie Nationale', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Police Nationale', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brigade des Sapeurs-Pompiers', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SDIS', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sécurité Civile', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SNCF Sûreté', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RATP Sûreté', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aéroports de Paris Sûreté', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ICTS FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondial Protection', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Torann-France', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goron', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAMSIC Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Main Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lancry Protection Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Athéna Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RAS Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe SGP', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hélios Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Luxant Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Triomphe Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Action Sécurité Protection', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SSP Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neo Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delta Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Geos Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thales Sécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Idemia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atos Cybersécurité', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airbus CyberSecurity', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orange Cyberdefense', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stormshield', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wallix', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Systancia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ercom', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palo Alto Networks FR', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },

  // ========== FACILITY_MANAGEMENT (48) ==========
  { name: 'Onet Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAMSIC', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atalian FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie Solutions', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodexo Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinci Facilities FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eiffage Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elior Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Derichebourg Multiservices', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSF', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Nicollin', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veolia Propreté', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suez Recyclage', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paprec Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Séché Environnement', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coved', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pizzorno Environnement', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saur', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veolia Eau FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suez Eau FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman & Wakefield FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BNP Paribas Real Estate', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Foncia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexity Immobilier', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Citya Immobilier', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oralia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lamy Group', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rentokil FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anticimex FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hygiène Office', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Initial FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elis', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Majorel FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teleperformance', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Webhelp', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comdata FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Armatis', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Sarp', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Otis FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schindler FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kone FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ThyssenKrupp Ascenseurs', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johnson Controls FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honeywell Building FR', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== METAL_STEEL (48) ==========
  { name: 'ArcelorMittal FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vallourec FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aperam FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eramet Métaux', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Constellium', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Haulotte Metal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexans Métal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ugitech', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aubert & Duval Métal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Industeel', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ascométal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Laminoirs des Landes', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manoir Industries', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fonderie de Ruelle', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fonderies du Poitou', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferry Capitain', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peugeot Frères', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lisi Médical', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Poclain Hydraulics', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fives Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clestra Hauserman', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arcelor Packaging', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dillinger FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Salzgitter FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Outokumpu FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acerinox FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norsk Hydro FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novelis FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trimet Aluminium FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rio Tinto FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metaleurop', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Recylex', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Derichebourg Recyclage', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GDE Recyclage', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Galloo FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe Ecore', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Feralpi FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celsa FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swiss Steel FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ThyssenKrupp Materials FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klöckner FR', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Descours & Cabaud', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KDI Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Réseau Pro', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saint-Gobain PAM', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Framatome Métal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Creusot Forge', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forges de Bologne', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CHEMICALS_PLASTICS (48) ==========
  { name: 'Arkema FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air Liquide FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solvay FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhodia', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roquette Chimie', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synthomer FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bostik', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DuPont FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evonik FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanxess FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covestro FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Linde FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wacker Chemie FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kemira FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SNF Floerger', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novacap', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adisseo', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seqens', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Minakem', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novacel', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suez Chimie', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Total Petrochemicals FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Plastipak FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Albéa', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berry Global FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sealed Air FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amcor FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gerresheimer FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Verallia', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'O-I Glass FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saint-Gobain Emballage', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tarkett', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gerflor', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forbo FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PPG Industries FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AkzoNobel FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sherwin-Williams FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zolpan', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tollens', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cromology', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Materis Paints', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axalta FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cabot FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inovyn FR', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },

  // ========== ECOMMERCE_FULFILLMENT (48) ==========
  { name: 'Amazon FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cdiscount', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veepee', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Showroomprivé', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rue du Commerce', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fnac Darty Online', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ManoMano', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Back Market', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leboncoin', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinted FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rakuten FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Redoute', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: '3 Suisses', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sarenza', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spartoo', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zalando FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASOS FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deliveroo FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uber Eats FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Just Eat FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frichti', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Getir FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gorillas FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cajoo', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carrefour Drive', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leclerc Drive', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Auchan Drive', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intermarché Drive', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Picnic FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ocado FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mirakl', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vestiaire Collective', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Doctolib', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BlaBlaCar', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OVHcloud', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deezer', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dailymotion', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Criteo', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Datadog FR', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ContentSquare', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Algolia', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Qonto', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lydia', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swile', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PayFit', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sendinblue', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ivalua', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cegid', sector: Sector.ECOMMERCE_FULFILLMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== TELECOMMUNICATIONS (48) ==========
  { name: 'Orange FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SFR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Free (Iliad)', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colt Technology FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TDF', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covage', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axione', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Altitude Infrastructure', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netgem', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ekinops', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sierra Wireless FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sigfox', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Actility', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kerlink', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cisco FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Juniper FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atos FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capgemini', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sopra Steria', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dassault Systèmes', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ubisoft', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gameloft', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Voodoo', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Scaleway', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Outscale', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clever Cloud', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OBS (Orange Business)', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SFR Business', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bouygues Telecom Entreprises', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hub One', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jaguar Network', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Completel', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Keyyo', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sewan', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Foliateam', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adista', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celeste', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nerim', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alphalink', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Waycom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hexanet', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kosc Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netalis', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurofiber FR', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },

  // ========== OTHER (48) ==========
  { name: 'La Banque Postale', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BNP Paribas', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Société Générale', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crédit Agricole', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crédit Mutuel', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caisse d Épargne', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Banque Populaire', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LCL', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HSBC FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Natixis', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AXA FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupama', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MAIF', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MACIF', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MATMUT', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MMA FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allianz FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Generali FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swiss Life FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CNP Assurances', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AG2R La Mondiale', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Malakoff Humanis', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pôle Emploi', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CNRS', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'INSERM', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CEA Recherche', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CNES', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ONERA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EDF Recherche', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adecco FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manpower FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Randstad FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CRIT Intérim', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synergie', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Proman', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Actual Group', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groupe LIP', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Expectra', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spring FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Michael Page FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Robert Half FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hays FR', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Française des Jeux', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PMU', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'France Télévisions', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Radio France', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TF1 Group', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Canal+ Group', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
];

async function main() {
  const market = Market.FR;
  console.log(`Seeding ${ALL_ENTRIES.length} additional companies for FR market (part 2)...`);
  let created = 0, existed = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { sector: entry.sector },
        create: { name: entry.name, slug, market, sector: entry.sector, websiteUrl: null, isActive: true },
      });
      const src = await prisma.crawlSource.findFirst({ where: { companyId: company.id } });
      if (!src) {
        await prisma.crawlSource.create({
          data: {
            companyId: company.id,
            name: `${entry.name} Emplois`,
            type: entry.sourceType as any,
            crawlMethod: CrawlMethod.HTML,
            seedUrls: [],
            schedule: '0 3 * * *',
            agingDays: 14,
            market,
            isActive: true,
          },
        });
        created++;
      } else { existed++; }
    } catch (e: any) {
      if (e.code === 'P2002') { existed++; } else { console.error(`Error: ${entry.name}:`, e.message); }
    }
  }
  console.log(`\nDone! Created: ${created}, Already existed: ${existed}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
