import { PrismaClient, Market, Sector, CrawlMethod } from '@prisma/client';
import { randomUUID } from 'crypto';

type SourceType = 'COMPANY_CAREER' | 'GOVERNMENT';

interface CompanyEntry {
  name: string;
  sector: string;
  sourceType: SourceType;
  websiteUrl?: string;
  seedUrls?: string[];
}

const COMPANIES: CompanyEntry[] = [

// ========== GOVERNMENT (1) ==========
  { name: 'SINE / Portal Emprega Brasil', sector: 'OTHER', sourceType: 'GOVERNMENT', websiteUrl: 'https://empregabrasil.mte.gov.br' },

// ========== LOGISTICS_TRANSPORTATION (50) ==========
  { name: 'Correios', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.correios.com.br' },
  { name: 'Localiza', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.localiza.com' },
  { name: 'Movida', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.movida.com.br' },
  { name: 'JSL Logística', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.jsl.com.br' },
  { name: 'TNT Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tnt.com/express/pt_br' },
  { name: 'DHL Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dhl.com/br-pt' },
  { name: 'FedEx Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fedex.com/pt-br' },
  { name: 'UPS Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ups.com/br/pt' },
  { name: 'Jadlog', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.jadlog.com.br' },
  { name: 'Total Express', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.totalexpress.com.br' },
  { name: 'Sequoia Logística', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.sequoialog.com.br' },
  { name: 'Rapidão Cometa', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fedex.com/pt-br' },
  { name: 'Braspress', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.braspress.com' },
  { name: 'Tegma', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tegma.com.br' },
  { name: 'Transporte Bertolini', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bertolini.com.br' },
  { name: 'Comfortdelgro Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.comfortdelgro.com.br' },
  { name: 'DB Schenker Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dbschenker.com/br-pt' },
  { name: 'Kuehne+Nagel Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://br.kuehne-nagel.com' },
  { name: 'Maersk Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.maersk.com/local-information/brazil' },
  { name: 'MSC Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.msc.com/bra' },
  { name: 'CMA CGM Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cma-cgm.com/local/brazil' },
  { name: 'Grupo Comporte', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupocomporte.com.br' },
  { name: 'Itapemirim', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.itapemirim.com.br' },
  { name: 'Gol Linhas Aéreas', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.voegol.com.br' },
  { name: 'LATAM Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.latamairlines.com/br/pt' },
  { name: 'Azul Linhas Aéreas', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.voeazul.com.br' },
  { name: 'Embraer Serviços & Suporte', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.embraer.com' },
  { name: 'Infraero', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.infraero.gov.br' },
  { name: 'GRU Airport', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.gru.com.br' },
  { name: 'BH Airport', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bh.airport.com.br' },
  { name: 'CCR Aeroportos', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ccr.com.br' },
  { name: 'Tegma Gestão Logística', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tegma.com.br' },
  { name: 'Wilson Sons', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.wilsonsons.com.br' },
  { name: 'Santos Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.santosbrasil.com.br' },
  { name: 'Log-In Logística', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.log-in.com.br' },
  { name: 'Grupo Comfortrans', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.comfortrans.com.br' },
  { name: 'Ryder Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ryder.com/pt-br' },
  { name: 'GreenYellow Mobilidade', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.greenyellow.com.br' },
  { name: '99 (DiDi Brasil)', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://99app.com' },
  { name: 'iFood Entregadores', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ifood.com.br' },
  { name: 'Rappi Brasil', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.rappi.com.br' },
  { name: 'Loggi', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.loggi.com' },
  { name: 'TM3 Logística', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tm3.com.br' },
  { name: 'Cometa Transporte', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.viacaocometa.com.br' },
  { name: 'Plimor Transporte', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.plimor.com.br' },
  { name: 'Expresso Mercúrio', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.expressomercurio.com.br' },
  { name: 'Grupo Comporte Participações', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupocomporte.com.br' },
  { name: 'Metrô SP', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.metro.sp.gov.br' },
  { name: 'CPTM', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cptm.sp.gov.br' },
  { name: 'SuperVia', sector: 'LOGISTICS_TRANSPORTATION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.supervia.com.br' },

// ========== MANUFACTURING (50) ==========
  { name: 'Embraer', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.embraer.com' },
  { name: 'WEG', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.weg.net/br' },
  { name: 'Marcopolo', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.marcopolo.com.br' },
  { name: 'Gerdau', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.gerdau.com' },
  { name: 'Tupy', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tupy.com.br' },
  { name: 'Tramontina', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tramontina.com.br' },
  { name: 'Randon', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.randon.com.br' },
  { name: 'Romi', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.romi.com' },
  { name: 'Metalfrio', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.metalfrio.com.br' },
  { name: 'Schuler', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.schuler.com/br' },
  { name: 'Embraco', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.embraco.com' },
  { name: 'Whirlpool Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.whirlpool.com.br' },
  { name: 'Electrolux Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.electrolux.com.br' },
  { name: 'Brastemp', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.brastemp.com.br' },
  { name: 'Consul', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.consul.com.br' },
  { name: 'Philco', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.philco.com.br' },
  { name: 'Positivo Tecnologia', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.positivo.com.br' },
  { name: 'Intelbras', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.intelbras.com.br' },
  { name: 'Weg Automação', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.weg.net/br' },
  { name: 'Siemens Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.siemens.com/br/pt' },
  { name: 'ABB Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://new.abb.com/br' },
  { name: 'Schneider Electric Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.se.com/br/pt' },
  { name: 'Bosch Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bosch.com.br' },
  { name: '3M Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.3m.com.br' },
  { name: 'Dow Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dow.com/pt-br' },
  { name: 'BASF Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.basf.com/br/pt' },
  { name: 'Bayer Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bayer.com.br' },
  { name: 'Braskem', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.braskem.com.br' },
  { name: 'Oxiteno', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.oxiteno.com.br' },
  { name: 'Rhodia Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.solvay.com/pt' },
  { name: 'Saint-Gobain Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.saint-gobain.com.br' },
  { name: 'Owens-Illinois Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.o-i.com' },
  { name: 'Eternit', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eternit.com.br' },
  { name: 'Votorantim Cimentos', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.votorantimcimentos.com' },
  { name: 'Intercement Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.intercement.com' },
  { name: 'Usiminas', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.usiminas.com' },
  { name: 'CSN (Companhia Siderúrgica Nacional)', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.csn.com.br' },
  { name: 'ArcelorMittal Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://brasil.arcelormittal.com' },
  { name: 'Novelis Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.novelis.com/pt-br' },
  { name: 'Alunorte', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.alunorte.com.br' },
  { name: 'Pirelli Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pirelli.com/tyres/pt-br' },
  { name: 'Bridgestone Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bridgestone.com.br' },
  { name: 'Goodyear Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.goodyear.com.br' },
  { name: 'Michelin Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.michelin.com.br' },
  { name: 'Continental Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.continental.com/pt-br' },
  { name: 'Natura &Co', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.naturaco.com/br' },
  { name: 'Unilever Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.unilever.com.br' },
  { name: 'Procter & Gamble Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pg.com/pt_BR' },
  { name: 'Johnson & Johnson Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.jnj.com.br' },
  { name: 'Colgate-Palmolive Brasil', sector: 'MANUFACTURING', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.colgatepalmolive.com.br' },

// ========== RETAIL (50) ==========
  { name: 'Magazine Luiza', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.magazineluiza.com.br' },
  { name: 'Casas Bahia', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.casasbahia.com.br' },
  { name: 'Lojas Americanas', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.americanas.com.br' },
  { name: 'Renner', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lojasrenner.com.br' },
  { name: 'Riachuelo', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.riachuelo.com.br' },
  { name: 'Carrefour Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.carrefour.com.br' },
  { name: 'Grupo Pão de Açúcar (GPA)', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.gpabr.com' },
  { name: 'Extra Supermercados', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.extra.com.br' },
  { name: 'Assaí Atacadista', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.assai.com.br' },
  { name: 'Atacadão', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.atacadao.com.br' },
  { name: 'Havan', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.havan.com.br' },
  { name: 'Leroy Merlin Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.leroymerlin.com.br' },
  { name: 'C&A Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cea.com.br' },
  { name: 'Centauro', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.centauro.com.br' },
  { name: 'Decathlon Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.decathlon.com.br' },
  { name: 'Nike Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.nike.com.br' },
  { name: 'Adidas Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.adidas.com.br' },
  { name: 'Arezzo', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.arezzo.com.br' },
  { name: 'Grupo Soma', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.somagrupo.com.br' },
  { name: 'Osklen', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.osklen.com' },
  { name: 'Farm Rio', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.farmrio.com.br' },
  { name: 'Vivara', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vivara.com.br' },
  { name: 'Grupo Petz', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.petz.com.br' },
  { name: 'Cobasi', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cobasi.com.br' },
  { name: 'Drogasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.drogasil.com.br' },
  { name: 'Raia Drogasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.raiadrogasil.com.br' },
  { name: 'Ultrafarma', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ultrafarma.com.br' },
  { name: 'Pague Menos', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.paguemenos.com.br' },
  { name: 'Droga Raia', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.drogaraia.com.br' },
  { name: 'Mundo Verde', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mundoverde.com.br' },
  { name: 'O Boticário', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.boticario.com.br' },
  { name: 'Natura Cosméticos', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.natura.com.br' },
  { name: 'Avon Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.avon.com.br' },
  { name: 'Eudora', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eudora.com.br' },
  { name: 'Livraria Cultura', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.livrariacultura.com.br' },
  { name: 'Saraiva', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.saraiva.com.br' },
  { name: 'Kalunga', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.kalunga.com.br' },
  { name: 'Fast Shop', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fastshop.com.br' },
  { name: 'Ricardo Eletro', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ricardoeletro.com.br' },
  { name: 'Ponto (Via Varejo)', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pontofrio.com.br' },
  { name: 'Leader Magazine', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.leader.com.br' },
  { name: 'Ri Happy', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.rihappy.com.br' },
  { name: 'PBKids', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pbkids.com.br' },
  { name: 'Lojas Colombo', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.colombo.com.br' },
  { name: 'Lojas Quero-Quero', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.queroquero.com.br' },
  { name: 'Marisa', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.marisa.com.br' },
  { name: 'Grupo Mateus', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupomateus.com.br' },
  { name: 'DIA Brasil', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dia.com.br' },
  { name: 'Bemol', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bemol.com.br' },
  { name: 'Supermercados BH', sector: 'RETAIL', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.supermercadosbh.com.br' },

// ========== CONSTRUCTION (50) ==========
  { name: 'MRV Engenharia', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mrv.com.br' },
  { name: 'Cyrela', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cyrela.com.br' },
  { name: 'Construtora Tenda', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.construtendas.com.br' },
  { name: 'Direcional Engenharia', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.direcional.com.br' },
  { name: 'EZTec', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eztec.com.br' },
  { name: 'Even Construtora', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.even.com.br' },
  { name: 'Gafisa', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.gafisa.com.br' },
  { name: 'Helbor Empreendimentos', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.helbor.com.br' },
  { name: 'Tecnisa', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tecnisa.com.br' },
  { name: 'Brookfield Incorporações', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.brookfield.com.br' },
  { name: 'Camargo Corrêa', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.construcoes.camargocorrea.com.br' },
  { name: 'Andrade Gutierrez', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.agconcessoes.com.br' },
  { name: 'OAS Construtora', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.oas.com.br' },
  { name: 'Odebrecht Engenharia', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.novonor.com.br' },
  { name: 'Queiroz Galvão', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.queirozgalvao.com' },
  { name: 'Engevix', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.engevix.com.br' },
  { name: 'Constran', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.constran.com.br' },
  { name: 'Construtora Barbosa Mello', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cbm.com.br' },
  { name: 'Galvão Engenharia', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.galvaoengenharia.com.br' },
  { name: 'Grupo Cury', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cury.net.br' },
  { name: 'Plano&Plano', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.planoempreendimentos.com.br' },
  { name: 'Moura Dubeux', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mouradubeux.com.br' },
  { name: 'Calçada Empreendimentos', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.calcada.com.br' },
  { name: 'Viver Incorporadora', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.viver.com.br' },
  { name: 'PDG Realty', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pdgrealty.com.br' },
  { name: 'Rossi Residencial', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.rossiresidencial.com.br' },
  { name: 'Tegra Incorporadora', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tegra.com.br' },
  { name: 'Ecorodovias', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ecorodovias.com.br' },
  { name: 'CCR Rodovias', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ccr.com.br' },
  { name: 'Arteris', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.arteris.com.br' },
  { name: 'Encalso Construções', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.encalso.com.br' },
  { name: 'Construtora Ferreira Guedes', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ferreiraguedes.com.br' },
  { name: 'Sinco Engenharia', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.sinco.com.br' },
  { name: 'Tigre Brasil', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tigre.com.br' },
  { name: 'Deca (Duratex)', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.deca.com.br' },
  { name: 'Portobello', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.portobello.com.br' },
  { name: 'Eliane Revestimentos', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eliane.com' },
  { name: 'Ceusa', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ceusa.com.br' },
  { name: 'Duratex', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.duratex.com.br' },
  { name: 'Eucatex', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eucatex.com.br' },
  { name: 'Masisa Brasil', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.masisa.com/bra' },
  { name: 'Eternit Brasil', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eternit.com.br' },
  { name: 'Votorantim Cimentos Brasil', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.votorantimcimentos.com' },
  { name: 'Lafarge Brasil', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lafargeholcim.com.br' },
  { name: 'Cimento Nassau', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.nassau.com.br' },
  { name: 'Brennand Cimento', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.brennandcimento.com.br' },
  { name: 'Metso Brasil', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.metso.com/br' },
  { name: 'Fluidodinâmica', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fluidodinamica.com.br' },
  { name: 'Vivenda do Camarão (franquias)', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vivendadocamarao.com.br' },
  { name: 'Copel Distribuição', sector: 'CONSTRUCTION', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.copel.com' },

// ========== FOOD_BEVERAGE (50) ==========
  { name: 'Ambev', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ambev.com.br' },
  { name: 'BRF', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.brf-global.com' },
  { name: 'JBS', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.jbs.com.br' },
  { name: 'Marfrig', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.marfrig.com.br' },
  { name: 'Minerva Foods', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.minervafoods.com' },
  { name: 'Seara Alimentos', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.seara.com.br' },
  { name: 'Perdigão', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.perdigao.com.br' },
  { name: 'Sadia', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.sadia.com.br' },
  { name: 'Nestlé Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.nestle.com.br' },
  { name: 'Kraft Heinz Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.kraftheinzcompany.com/br' },
  { name: 'Mondelez Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mondelezinternational.com/pt-br' },
  { name: 'Coca-Cola Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cocacolabrasil.com.br' },
  { name: 'PepsiCo Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pepsico.com.br' },
  { name: 'Grupo Heineken Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.heinekenbrasil.com.br' },
  { name: 'Café do Ponto', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cafedoponto.com.br' },
  { name: 'Três Corações', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.3coracoes.com.br' },
  { name: 'Illy Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.illy.com/pt-br' },
  { name: 'Vigor Alimentos', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vigor.com.br' },
  { name: 'Lacta', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lacta.com.br' },
  { name: 'Garoto', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.garoto.com.br' },
  { name: 'M.Dias Branco', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mdiasbranco.com.br' },
  { name: 'Bimbo Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupobimbo.com/pt-br' },
  { name: 'Ana Maria Biscoitos', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.anamaria.com.br' },
  { name: 'Bauducco', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bauducco.com.br' },
  { name: 'Panco', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.panco.com.br' },
  { name: 'Habib\'s', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.habibs.com.br' },
  { name: 'Bob\'s', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bobs.com.br' },
  { name: 'Giraffas', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.giraffas.com.br' },
  { name: 'McDonald\'s Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mcdonalds.com.br' },
  { name: 'Burger King Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.burgerking.com.br' },
  { name: 'Subway Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.subway.com/pt-br' },
  { name: 'KFC Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.kfc.com.br' },
  { name: 'Pizza Hut Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pizzahut.com.br' },
  { name: 'Outback Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.outback.com.br' },
  { name: 'Madero Burger', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.restaurantemadero.com.br' },
  { name: 'Spoleto', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.spoleto.com.br' },
  { name: 'Forno de Minas', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fornominas.com.br' },
  { name: 'Laticínios Bela Vista', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.belavista.com.br' },
  { name: 'Danone Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.danone.com.br' },
  { name: 'Activia Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.activia.com.br' },
  { name: 'Forno de Minas Queijos', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fornominas.com.br' },
  { name: 'Copersucar', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.copersucar.com.br' },
  { name: 'Raízen', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.raizen.com.br' },
  { name: 'Bunge Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bunge.com.br' },
  { name: 'Cargill Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cargill.com.br' },
  { name: 'Louis Dreyfus Brasil', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ldcom.com/br/pt' },
  { name: 'Amaggi', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.amaggi.com.br' },
  { name: 'Caramuru Alimentos', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.caramuru.com' },
  { name: 'Grupo Petrópolis', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupopetropolis.com.br' },
  { name: 'Antarctica', sector: 'FOOD_BEVERAGE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ambev.com.br' },

// ========== AUTOMOTIVE (50) ==========
  { name: 'Volkswagen Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vw.com.br' },
  { name: 'Fiat Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fiat.com.br' },
  { name: 'General Motors Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.chevrolet.com.br' },
  { name: 'Toyota Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.toyota.com.br' },
  { name: 'Honda Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.honda.com.br' },
  { name: 'Stellantis Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.stellantis.com/pt-br' },
  { name: 'Renault Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.renault.com.br' },
  { name: 'Hyundai Caoa Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hyundai.com.br' },
  { name: 'Nissan Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.nissan.com.br' },
  { name: 'Ford Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ford.com.br' },
  { name: 'Mercedes-Benz Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mercedes-benz.com.br' },
  { name: 'BMW Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bmw.com.br' },
  { name: 'Audi Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.audi.com.br' },
  { name: 'Volvo Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.volvo.com/trucks/br' },
  { name: 'Scania Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.scania.com/br/pt' },
  { name: 'MAN Latin America', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.manlatinamerica.com' },
  { name: 'Iveco Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.iveco.com/brazil' },
  { name: 'Agrale', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.agrale.com.br' },
  { name: 'Troller (Ford)', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.troller.com.br' },
  { name: 'Harley-Davidson Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.harley-davidson.com/br' },
  { name: 'Yamaha Motor Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.yamaha-motor.com.br' },
  { name: 'Honda Motos Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.honda.com.br/motos' },
  { name: 'Grupo Comporte Veículos', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupocomporte.com.br' },
  { name: 'BYD Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.byd.com/pt-br' },
  { name: 'Caoa Chery Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.chery.com.br' },
  { name: 'GWM Brasil (Haval)', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.gwm.com.br' },
  { name: 'Jeep Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.jeep.com.br' },
  { name: 'RAM Trucks Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ramtrucks.com.br' },
  { name: 'Citroën Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.citroen.com.br' },
  { name: 'Peugeot Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.peugeot.com.br' },
  { name: 'Mahindra Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mahindra.com/brasil' },
  { name: 'Mitsubishi Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mitsubishi.com.br' },
  { name: 'Subaru Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.subaru.com.br' },
  { name: 'Kia Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.kia.com/br' },
  { name: 'Localfrio', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.localfrio.com.br' },
  { name: 'Auto Viação Catarinense', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.autocatarinense.com.br' },
  { name: 'Grupo Tegma Veículos', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tegma.com.br' },
  { name: 'Usina Santa Adélia (Etanol)', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.usinasantaadelia.com.br' },
  { name: 'Cosan Lubrificantes', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cosan.com.br' },
  { name: 'Ipiranga Produtos', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ipiranga.com.br' },
  { name: 'BR Distribuidora', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vibra.com.br' },
  { name: 'Bosch Brasil Automotive', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bosch.com.br' },
  { name: 'Denso Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.denso.com/br/pt' },
  { name: 'Valeo Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.valeo.com/br' },
  { name: 'Magneti Marelli Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.magnetimarelli.com/pt-br' },
  { name: 'TRW Automotive Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.zf.com/br/pt' },
  { name: 'Dana Incorporated Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dana.com' },
  { name: 'Muffler Center Brasil', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mufflercenter.com.br' },
  { name: 'Grupo Comil Ônibus', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.comil.com.br' },
  { name: 'Neobus', sector: 'AUTOMOTIVE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.neobus.com.br' },

// ========== TEXTILE (50) ==========
  { name: 'Hering', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hering.com.br' },
  { name: 'Malwee', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.malwee.com.br' },
  { name: 'Lupo', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lupo.com.br' },
  { name: 'Marisol', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.marisol.com.br' },
  { name: 'Karsten', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.karsten.com.br' },
  { name: 'Coteminas', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.coteminas.com.br' },
  { name: 'Springs Global', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.springsglobal.com.br' },
  { name: 'Buettner', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.buettner.com.br' },
  { name: 'Cedro Têxtil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cedrotextil.com.br' },
  { name: 'Vicunha Têxtil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vicunha.com.br' },
  { name: 'Teka Têxtil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.teka.com.br' },
  { name: 'Lepper', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lepper.com.br' },
  { name: 'Döhler', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dohler.com.br' },
  { name: 'Santanense Têxtil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.santanense.com.br' },
  { name: 'Grupo Cambuci', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cambuci.com.br' },
  { name: 'Alpargatas (Havaianas)', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.alpargatas.com.br' },
  { name: 'Grendene', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grendene.com.br' },
  { name: 'Vulcabras Azaléia', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vulcabras.com.br' },
  { name: 'Arezzo Indústria', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.arezzo.com.br' },
  { name: 'Calçados Via Uno', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.viauno.com.br' },
  { name: 'Beira Rio Calçados', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.beiraio.com.br' },
  { name: 'Usaflex', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.usaflex.com.br' },
  { name: 'Ramarim Calçados', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ramarim.com.br' },
  { name: 'Piccadilly Calçados', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.piccadilly.com.br' },
  { name: 'Bottero Calçados', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bottero.com.br' },
  { name: 'Dakota Calçados', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupodakota.com.br' },
  { name: 'Skechers Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.skechers.com.br' },
  { name: 'Puma Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.puma.com/pt-br' },
  { name: 'New Balance Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.newbalance.com.br' },
  { name: 'Under Armour Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.underarmour.com.br' },
  { name: 'Speedo Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.speedo.com.br' },
  { name: 'Topper Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.topper.com.br' },
  { name: 'Penalty Esportes', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.penalty.com.br' },
  { name: 'Olympikus', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.olympikus.com.br' },
  { name: 'Dafiti Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dafiti.com.br' },
  { name: 'Restoque (Le Lis Blanc)', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.restoque.com.br' },
  { name: 'Marisa Lojas', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.marisa.com.br' },
  { name: 'Zara Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.zara.com/br' },
  { name: 'H&M Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www2.hm.com/pt_br' },
  { name: 'Amaro Fashion', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.amaro.com' },
  { name: 'Animale', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.animale.com.br' },
  { name: 'Forum Moda', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.forum.com.br' },
  { name: 'Colcci', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.colcci.com.br' },
  { name: 'Ellus', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ellus.com.br' },
  { name: 'Richards', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.richards.com.br' },
  { name: 'Lacoste Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lacoste.com.br' },
  { name: 'Tommy Hilfiger Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tommy.com.br' },
  { name: 'Calvin Klein Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.calvinklein.com.br' },
  { name: 'Levi\'s Brasil', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.levis.com.br' },
  { name: 'Reserva Moda', sector: 'TEXTILE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.reserva.com.br' },

// ========== MINING_ENERGY (50) ==========
  { name: 'Petrobras', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.petrobras.com.br' },
  { name: 'Vale', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vale.com/pt' },
  { name: 'Eletrobras', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eletrobras.com' },
  { name: 'CPFL Energia', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cpfl.com.br' },
  { name: 'Energisa', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.energisa.com.br' },
  { name: 'Equatorial Energia', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.equatorialenergia.com.br' },
  { name: 'Enel Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.enel.com.br' },
  { name: 'Light S.A.', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.light.com.br' },
  { name: 'Cemig', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cemig.com.br' },
  { name: 'Copel', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.copel.com' },
  { name: 'Celesc', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.celesc.com.br' },
  { name: 'Coelba (Neoenergia)', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.neoenergia.com' },
  { name: 'Neoenergia', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.neoenergia.com' },
  { name: 'Eneva', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eneva.com.br' },
  { name: 'Engie Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.engieenergia.com.br' },
  { name: 'AES Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.aesbrasil.com.br' },
  { name: 'Omega Geração', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.omegageracao.com.br' },
  { name: 'Casa dos Ventos', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.casadosventos.com.br' },
  { name: 'Elera Renováveis', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.elera.com.br' },
  { name: 'Atlas Renewable Energy', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.atlasrenewable.com' },
  { name: 'TotalEnergies Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://totalenergies.com/brasil' },
  { name: 'Shell Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.shell.com.br' },
  { name: 'ExxonMobil Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.exxonmobil.com.br' },
  { name: 'Chevron Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.chevron.com/worldwide/brazil' },
  { name: 'BP Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bp.com/pt_br' },
  { name: 'Vibra Energia', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.vibra.com.br' },
  { name: 'Ômega Energia', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.omegaenergia.com.br' },
  { name: 'Samarco Mineração', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.samarco.com' },
  { name: 'Anglo American Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.angloamerican.com/brazil' },
  { name: 'Alcoa Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.alcoa.com/brasil/pt' },
  { name: 'Votorantim Metais', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.votorantim.com.br' },
  { name: 'Mineração Buritirama', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.buritirama.com.br' },
  { name: 'Kinross Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.kinross.com/locations/brazil' },
  { name: 'Yamana Gold Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.yamana.com/operations/brazil' },
  { name: 'Sigma Lithium', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.sigmalithiumresources.com' },
  { name: 'Nexa Resources Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.nexaresources.com/pt-br' },
  { name: 'Magnesita Refratários', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.rhi-magnesita.com/pt-br' },
  { name: 'Gás Natural Fenosa Brasil', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.naturgy.com.br' },
  { name: 'Comgás', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.comgas.com.br' },
  { name: 'Mitsui Gás e Energia', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.mitsui.com/br/pt' },
  { name: 'Transportadora Brasileira Gasoduto', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tbg.com.br' },
  { name: 'TAG (Transportadora Associada de Gás)', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.tagbr.com.br' },
  { name: 'Itaipu Binacional', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.itaipu.gov.br' },
  { name: 'Chesf', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.chesf.com.br' },
  { name: 'Furnas Centrais Elétricas', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.furnas.com.br' },
  { name: 'Eletronorte', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eletronorte.gov.br' },
  { name: 'CEEE-D', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ceee.com.br' },
  { name: 'Eletropaulo (Enel SP)', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.enel.com.br/pt-sao-paulo' },
  { name: 'Ampla Energia (Enel RJ)', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.enel.com.br/pt-rio-de-janeiro' },
  { name: 'Celpe (Neoenergia PE)', sector: 'MINING_ENERGY', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.neoenergia.com' },

// ========== HEALTHCARE (50) ==========
  { name: 'Rede D\'Or São Luiz', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.rededorsaoluiz.com.br' },
  { name: 'Hapvida NotreDame Intermédica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hapvida.com.br' },
  { name: 'Fleury Medicina Diagnóstica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.fleury.com.br' },
  { name: 'Dasa (Diagnósticos da América)', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.dasa.com.br' },
  { name: 'NotreDame Intermédica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.intermedica.com.br' },
  { name: 'Amil Assistência Médica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.amil.com.br' },
  { name: 'Unimed Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.unimed.com.br' },
  { name: 'SulAmérica Saúde', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.sulamerica.com.br' },
  { name: 'Bradesco Saúde', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bradescomaissaude.com.br' },
  { name: 'Prevent Senior', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.preventsenior.com.br' },
  { name: 'Hospital Albert Einstein', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.einstein.br' },
  { name: 'Hospital Sírio-Libanês', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hospitalsiriolibanes.org.br' },
  { name: 'Hospital das Clínicas SP', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hc.fm.usp.br' },
  { name: 'Santa Casa de Misericórdia SP', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.santacasasp.org.br' },
  { name: 'Hospital Mater Dei', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.materdei.com.br' },
  { name: 'Hospital Oswaldo Cruz', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hospitaloswaldocruz.org.br' },
  { name: 'Oncoclínicas do Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.oncologicadobrasil.com.br' },
  { name: 'CORA Saúde', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cora.com.br' },
  { name: 'Kora Saúde', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.korasaude.com.br' },
  { name: 'Americas Saúde', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.americassaude.com.br' },
  { name: 'Hermes Pardini', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hermespardini.com.br' },
  { name: 'Lavid Laboratórios', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.lavid.com.br' },
  { name: 'Sabin Medicina Diagnóstica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.labsabin.com.br' },
  { name: 'Grupo Alliar', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.alliar.com' },
  { name: 'Instituto de Diagnóstico por Imagem (IDI)', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.idi.com.br' },
  { name: 'Hypera Pharma', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.hypera.com.br' },
  { name: 'EMS Pharma', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ems.com.br' },
  { name: 'Eurofarma', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.eurofarma.com.br' },
  { name: 'Cristália Produtos Químicos', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.cristalia.com.br' },
  { name: 'Aché Laboratórios', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.ache.com.br' },
  { name: 'Biolab Farmacêutica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.biolab.com.br' },
  { name: 'Pfizer Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.pfizer.com.br' },
  { name: 'Sanofi Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.sanofi.com.br' },
  { name: 'Novartis Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.novartis.com.br' },
  { name: 'Roche Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.roche.com.br' },
  { name: 'AstraZeneca Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.astrazeneca.com.br' },
  { name: 'MSD Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.msd.com.br' },
  { name: 'Abbott Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.abbott.com.br' },
  { name: 'BD Brasil (Becton Dickinson)', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.bd.com/pt-br' },
  { name: 'Medtronic Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.medtronic.com/br-pt' },
  { name: 'Philips Healthcare Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.philips.com.br/healthcare' },
  { name: 'GE Healthcare Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.gehealthcare.com/pt-br' },
  { name: 'Siemens Healthineers Brasil', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.siemens-healthineers.com/br' },
  { name: 'Biomm', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.biomm.com' },
  { name: 'Grupo Oncoclínicas', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupooncoclinicas.com' },
  { name: 'Clínica de Olhos', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.clinicadeolhos.com.br' },
  { name: 'Instituto do Coração (InCor)', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.incor.org.br' },
  { name: 'GRAACC (Oncologia Pediátrica)', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.graacc.org.br' },
  { name: 'Grupo Marista Saúde', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.grupomarista.org.br' },
  { name: 'AFIP Medicina Diagnóstica', sector: 'HEALTHCARE', sourceType: 'COMPANY_CAREER', websiteUrl: 'https://www.afip.com.br' },

];

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function main() {
  const { PrismaClient: PC } = require('@prisma/client');
  const prisma = new PC();
  const market = 'BR';
  console.log(`Seeding ${COMPANIES.length} BR companies (part 1)...`);

  let created = 0, existed = 0;
  for (const entry of COMPANIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl || undefined, sector: entry.sector },
        create: {
          name: entry.name, slug, market,
          sector: entry.sector,
          websiteUrl: entry.websiteUrl || null,
          isActive: true,
        },
      });
      const existingSource = await prisma.crawlSource.findFirst({ where: { companyId: company.id } });
      if (!existingSource) {
        await prisma.crawlSource.create({
          data: {
            companyId: company.id,
            name: `${entry.name} Vagas`,
            type: entry.sourceType as any,
            crawlMethod: 'HTML',
            seedUrls: [],
            schedule: '0 3 * * *',
            agingDays: 14,
            market,
            isActive: true,
          },
        });
        created++;
      } else { existed++; }
    } catch (e: any) {
      if (e.code === 'P2002') { existed++; } else { console.error(`Error: ${entry.name}:`, e.message); }
    }
  }
  console.log(`Done! Created: ${created}, Already existed: ${existed}`);
  await prisma.$disconnect();
}
main();
