import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });
const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  websiteUrl: string | null;
  sector: Sector;
  sourceType: SourceType;
}

function slugify(text: string): string {
  return text.toLowerCase()
    .replace(/[áàâã]/g, 'a').replace(/[éèê]/g, 'e').replace(/[íì]/g, 'i')
    .replace(/[óòôõ]/g, 'o').replace(/[úù]/g, 'u').replace(/ç/g, 'c')
    .replace(/ñ/g, 'n')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// ========== HOSPITALITY_TOURISM (50) ==========
const HOSPITALITY_TOURISM: CompanyEntry[] = [
  { name: 'Accor Brasil', websiteUrl: 'https://www.accor.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atlantica Hotels', websiteUrl: 'https://www.atlanticahotels.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Blue Tree Hotels', websiteUrl: 'https://www.bluetree.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bourbon Hotéis', websiteUrl: 'https://www.bourbon.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Wish', websiteUrl: 'https://www.grupolist.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pestana Brasil', websiteUrl: 'https://www.pestana.com/br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott Brasil', websiteUrl: 'https://www.marriott.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton Brasil', websiteUrl: 'https://www.hilton.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyatt Brasil', websiteUrl: 'https://www.hyatt.com/pt-BR', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'InterContinental Brasil', websiteUrl: 'https://www.ihg.com/intercontinental/hotels/br/pt', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Radisson Brasil', websiteUrl: 'https://www.radissonhotels.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Windsor Hotéis', websiteUrl: 'https://www.windsorhoteis.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meliá Brasil', websiteUrl: 'https://www.melia.com/pt/brasil', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Golden Tulip Brasil', websiteUrl: 'https://www.goldentulip.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LATAM Airlines', websiteUrl: 'https://www.latamairlines.com/br/pt', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gol Linhas Aéreas', websiteUrl: 'https://www.voegol.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Azul Linhas Aéreas', websiteUrl: 'https://www.voeazul.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CVC Corp', websiteUrl: 'https://www.cvc.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decolar Brasil', websiteUrl: 'https://www.decolar.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Booking Brasil', websiteUrl: 'https://www.booking.com/country/br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hurb', websiteUrl: 'https://www.hurb.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trivago Brasil', websiteUrl: 'https://www.trivago.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Abreu Viagens Brasil', websiteUrl: 'https://www.abreu.pt/brasil', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sol Meliá Brasil', websiteUrl: 'https://www.melia.com/pt/brasil', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Posadas Brasil', websiteUrl: 'https://www.fiestamericana.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rede Mabu Hotéis', websiteUrl: 'https://www.mabu.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transamerica Hotéis', websiteUrl: 'https://www.transamerica.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nacional Inn', websiteUrl: 'https://www.nacionalinn.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bristol Hotéis', websiteUrl: 'https://www.bristolhoteis.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ibis Brasil', websiteUrl: 'https://all.accor.com/brand/ibis/ibis-brasil', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novotel Brasil', websiteUrl: 'https://www.novotel.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sofitel Brasil', websiteUrl: 'https://www.sofitel.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copacabana Palace', websiteUrl: 'https://www.belmond.com/hotels/south-america/brazil/rio-de-janeiro', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belmond Brasil', websiteUrl: 'https://www.belmond.com/br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GJP Hotéis', websiteUrl: 'https://www.gjphoteis.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Slaviero Hotéis', websiteUrl: 'https://www.slavierohoteis.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fogo de Chão', websiteUrl: 'https://www.fogodechao.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Localiza Hertz', websiteUrl: 'https://www.localiza.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unidas Locadora', websiteUrl: 'https://www.unidas.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Movida Locações', websiteUrl: 'https://www.movida.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hotéis Deville', websiteUrl: 'https://www.deville.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prodigy Hotels', websiteUrl: 'https://www.prodigyhotel.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wyndham Brasil', websiteUrl: 'https://www.wyndhamhotels.com/pt-br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Best Western Brasil', websiteUrl: 'https://www.bestwestern.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Club Med Brasil', websiteUrl: 'https://www.clubmed.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costa Cruzeiros Brasil', websiteUrl: 'https://www.costacruzeiros.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSC Cruzeiros Brasil', websiteUrl: 'https://www.msccruises.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Royal Caribbean Brasil', websiteUrl: 'https://www.royalcaribbean.com/bra/pt', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embratur', websiteUrl: 'https://www.embratur.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Comporte', websiteUrl: 'https://www.comporte.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
];

// ========== AGRICULTURE (50) ==========
const AGRICULTURE: CompanyEntry[] = [
  { name: 'Cargill Brasil', websiteUrl: 'https://www.cargill.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bunge Brasil', websiteUrl: 'https://www.bunge.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADM Brasil', websiteUrl: 'https://www.adm.com/pt-br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SLC Agrícola', websiteUrl: 'https://www.slcagricola.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BrasilAgro', websiteUrl: 'https://www.brasil-agro.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embrapa', websiteUrl: 'https://www.embrapa.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JBS Brasil', websiteUrl: 'https://www.jbs.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BRF Brasil', websiteUrl: 'https://www.brf.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marfrig Global Foods', websiteUrl: 'https://www.marfrig.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Minerva Foods', websiteUrl: 'https://www.minervafoods.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Raízen', websiteUrl: 'https://www.raizen.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'São Martinho Açúcar', websiteUrl: 'https://www.saomartinho.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Usina São João', websiteUrl: 'https://www.usinasaojoao.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Amaggi', websiteUrl: 'https://www.amaggi.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo André Maggi', websiteUrl: 'https://www.amaggi.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cocamar Cooperativa', websiteUrl: 'https://www.cocamar.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coamo Agroindustrial', websiteUrl: 'https://www.coamo.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cooxupé Café', websiteUrl: 'https://www.cooxupe.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Louis Dreyfus Brasil', websiteUrl: 'https://www.ldc.com/pt', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dreyfus Commodities', websiteUrl: 'https://www.ldc.com/pt', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mosaic Fertilizantes', websiteUrl: 'https://www.mosaicco.com/pt-br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yara Brasil', websiteUrl: 'https://www.yara.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nutrien Brasil', websiteUrl: 'https://www.nutrien.com/pt-br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Basf Agro Brasil', websiteUrl: 'https://www.agro.basf.com/pt-br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Syngenta Brasil', websiteUrl: 'https://www.syngenta.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayer CropScience Brasil', websiteUrl: 'https://www.bayer.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corteva Agriscience Brasil', websiteUrl: 'https://www.corteva.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FMC Brasil', websiteUrl: 'https://www.fmc.com/pt-br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPL Brasil', websiteUrl: 'https://www.upl-ltd.com/br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sumitomo Chemical Brasil', websiteUrl: 'https://www.sumitomochemical.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suzano Agro', websiteUrl: 'https://www.suzano.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cutrale Citrus', websiteUrl: 'https://www.cutrale.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Citrosuco', websiteUrl: 'https://www.citrosuco.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camil Alimentos', websiteUrl: 'https://www.camil.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Petrópolis', websiteUrl: 'https://www.grupopetropolis.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ambev Brasil', websiteUrl: 'https://www.ambev.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinhos Miolo', websiteUrl: 'https://www.miolo.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aurora Cooperativa', websiteUrl: 'https://www.auroraalimentos.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elegê Alimentos', websiteUrl: 'https://www.elege.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piracanjuba', websiteUrl: 'https://www.piracanjuba.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigor Alimentos', websiteUrl: 'https://www.vigor.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italac Laticínios', websiteUrl: 'https://www.italac.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Batavo Cooperativa', websiteUrl: 'https://www.batavo.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frisia Cooperativa', websiteUrl: 'https://www.frisia.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Granol Agroindústria', websiteUrl: 'https://www.granol.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Globoaves', websiteUrl: 'https://www.globoaves.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Doux Frangosul', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seara Alimentos', websiteUrl: 'https://www.seara.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copacol Cooperativa', websiteUrl: 'https://www.copacol.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agronegócio Atvos', websiteUrl: 'https://www.atvos.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== SECURITY_SERVICES (50) ==========
const SECURITY_SERVICES: CompanyEntry[] = [
  { name: 'Prosegur Brasil', websiteUrl: 'https://www.prosegur.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gocil Serviços', websiteUrl: 'https://www.gocil.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orsegups Segurança', websiteUrl: 'https://www.orsegups.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Segurpro', websiteUrl: 'https://www.segurpro.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brinks Brasil', websiteUrl: 'https://www.brinks.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'G4S Brasil', websiteUrl: 'https://www.g4s.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pinkerton Brasil', websiteUrl: 'https://www.pinkerton.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allied Terceirização', websiteUrl: 'https://www.alliedtecnologia.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Protege Segurança', websiteUrl: 'https://www.protege.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Cia de Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Secseg Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Golden Shield Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigilantes do Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens Security Brasil', websiteUrl: 'https://www.siemens.com/br/pt', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Security Brasil', websiteUrl: 'https://www.boschsecurity.com/br/pt', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honeywell Security Brasil', websiteUrl: 'https://www.honeywell.com/br/pt', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tyco Brasil', websiteUrl: 'https://www.johnsoncontrols.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axis Communications Brasil', websiteUrl: 'https://www.axis.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hikvision Brasil', websiteUrl: 'https://www.hikvision.com/br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dahua Brasil', websiteUrl: 'https://www.dahuasecurity.com/br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intelbras Segurança', websiteUrl: 'https://www.intelbras.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JFL Alarmes', websiteUrl: 'https://www.jflalarm.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Senstar Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Segware', websiteUrl: 'https://www.segware.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Central de Alarmes Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alarm.com Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nice Brasil Automação', websiteUrl: 'https://www.nicebrasil.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PPA Automação', websiteUrl: 'https://www.ppa.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garen Tecnologia', websiteUrl: 'https://www.garen.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Control iD', websiteUrl: 'https://www.controlid.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henry Soluções', websiteUrl: 'https://www.henry.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Topdata Sistemas', websiteUrl: 'https://www.topdata.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anviz Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suprema Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Motorola Solutions Brasil', websiteUrl: 'https://www.motorolasolutions.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kenwood Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sepura Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hytera Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Icom Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Europ Assistance Brasil', websiteUrl: 'https://www.europ-assistance.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ICTS Protiviti Brasil', websiteUrl: 'https://www.protiviti.com/br-pt', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kroll Brasil', websiteUrl: 'https://www.kroll.com/pt-br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Control Risks Brasil', websiteUrl: 'https://www.controlrisks.com/br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beltis Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sasp Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GPD Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo IPV Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celta Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OmniSec Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Guardia Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
];

// ========== FACILITY_MANAGEMENT (50) ==========
const FACILITY_MANAGEMENT: CompanyEntry[] = [
  { name: 'Sodexo Brasil', websiteUrl: 'https://www.sodexo.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Facility Services Brasil', websiteUrl: 'https://br.issworld.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman & Wakefield Brasil', websiteUrl: 'https://www.cushmanwakefield.com/pt-br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE Brasil', websiteUrl: 'https://www.cbre.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL Brasil', websiteUrl: 'https://www.jll.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savills Brasil', websiteUrl: 'https://www.savills.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aramark Brasil', websiteUrl: 'https://www.aramark.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group Brasil', websiteUrl: 'https://www.compass-group.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elior Brasil', websiteUrl: 'https://www.elior.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Selecta Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Planservi Engenharia', websiteUrl: 'https://www.planservi.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viplex Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Tegma', websiteUrl: 'https://www.tegma.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Multiplan Empreendimentos', websiteUrl: 'https://www.multiplan.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iguatemi Empresa Shopping', websiteUrl: 'https://www.iguatemi.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BrMalls Participações', websiteUrl: 'https://www.brmalls.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allos Shopping Centers', websiteUrl: 'https://www.allos.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sonae Sierra Brasil', websiteUrl: 'https://www.sonaesierra.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ancar Ivanhoe Brasil', websiteUrl: 'https://www.ancarivanhoe.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hemisfério Sul Investimentos', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CCP Cyrela Commercial', websiteUrl: 'https://www.ccp.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JHSF Participações', websiteUrl: 'https://www.jhsf.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WTorre Empreendimentos', websiteUrl: 'https://www.wtorre.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pátria Investimentos Imob', websiteUrl: 'https://www.patria.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BR Properties', websiteUrl: 'https://www.brpr.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Log Commercial Properties', websiteUrl: 'https://www.logcp.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GLP Brasil', websiteUrl: 'https://www.glp.com/br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vbi Real Estate', websiteUrl: 'https://www.vbire.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colliers Brasil', websiteUrl: 'https://www.colliers.com/pt-br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Newmark Knight Frank Brasil', websiteUrl: 'https://www.nmrk.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buildings Inteligência', websiteUrl: 'https://www.buildings.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSA Engenharia Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uniflex Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bravo Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tesis Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Heleno e Fonseca', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limpeza Total Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belclean Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capital Clean Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Solve Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ativa Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Liq Facility', websiteUrl: 'https://www.liq.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Servicemaster Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodexo On-Site Brasil', websiteUrl: 'https://www.sodexo.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lume Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SG Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nortia Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Tegma Facilities', websiteUrl: 'https://www.tegma.com.br', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prime Facilities Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Infraservice Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
];

// ========== METAL_STEEL (50) ==========
const METAL_STEEL: CompanyEntry[] = [
  { name: 'Gerdau', websiteUrl: 'https://www.gerdau.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Usiminas', websiteUrl: 'https://www.usiminas.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CSN Companhia Siderúrgica', websiteUrl: 'https://www.csn.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ArcelorMittal Brasil', websiteUrl: 'https://brasil.arcelormittal.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vallourec Tubos', websiteUrl: 'https://www.vallourec.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenaris Brasil', websiteUrl: 'https://www.tenaris.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Villares Metals', websiteUrl: 'https://www.villaresmetals.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferbasa Ferro-Ligas', websiteUrl: 'https://www.ferbasa.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBM Companhia Brasileira Metalurgia', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Votorantim Metais', websiteUrl: 'https://www.nexa.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexa Resources', websiteUrl: 'https://www.nexa.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBA Companhia Brasileira Alumínio', websiteUrl: 'https://www.cba.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hydro Alumínio Brasil', websiteUrl: 'https://www.hydro.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novelis Brasil', websiteUrl: 'https://www.novelis.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcoa Brasil', websiteUrl: 'https://www.alcoa.com/brasil', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cinpal Alumínio', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dubal Brasil', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mangels Industrial', websiteUrl: 'https://www.mangels.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiat Metals Brasil', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schulz Compressores', websiteUrl: 'https://www.schulz.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cia Siderúrgica de Volta Redonda', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belgo Bekaert Arames', websiteUrl: 'https://www.arcelormittal.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prysmian Cabos Brasil', websiteUrl: 'https://www.prysmian.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexans Brasil', websiteUrl: 'https://www.nexans.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ficap Cabos Elétricos', websiteUrl: 'https://www.ficap.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WEG Brasil Motores', websiteUrl: 'https://www.weg.net/br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emerson Brasil', websiteUrl: 'https://www.emerson.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ABB Brasil', websiteUrl: 'https://new.abb.com/pt/br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eaton Brasil', websiteUrl: 'https://www.eaton.com/br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schneider Electric Brasil', websiteUrl: 'https://www.se.com/br/pt', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thyssen Krupp Brasil', websiteUrl: 'https://www.thyssenkrupp.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Condor Metalúrgica', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aço Cearense', websiteUrl: 'https://www.acocearense.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siderúrgica Barra Mansa', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Simpar Metais', websiteUrl: 'https://www.grupojsimpar.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tupy Fundições', websiteUrl: 'https://www.tupy.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rexnord Brasil', websiteUrl: 'https://www.rexnord.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKF Brasil', websiteUrl: 'https://www.skf.com/br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NSK Brasil', websiteUrl: 'https://www.nsk.com/br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schaeffler Brasil', websiteUrl: 'https://www.schaeffler.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Timken Brasil', websiteUrl: 'https://www.timken.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Confab Industrial', websiteUrl: 'https://www.tenaris.com/pt-br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camargo Corrêa Cimentos', websiteUrl: 'https://www.camargocorrea.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sumitomo Brasil Aços', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JFE Steel Brasil', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nippon Steel Brasil', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'POSCO Brasil', websiteUrl: 'https://www.posco.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metalúrgica Gerdau Aços', websiteUrl: 'https://www.gerdau.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vega do Sul Aços', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cia Siderúrgica Nacional Aços', websiteUrl: 'https://www.csn.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
];

// ========== CHEMICALS_PLASTICS (50) ==========
const CHEMICALS_PLASTICS: CompanyEntry[] = [
  { name: 'Braskem', websiteUrl: 'https://www.braskem.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oxiteno Ultrapar', websiteUrl: 'https://www.oxiteno.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elekeiroz Química', websiteUrl: 'https://www.elekeiroz.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unigel Químicos', websiteUrl: 'https://www.unigel.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Borealis Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Brasil', websiteUrl: 'https://www.dow.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF Brasil', websiteUrl: 'https://www.basf.com/br/pt', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayer Brasil', websiteUrl: 'https://www.bayer.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LANXESS Brasil', websiteUrl: 'https://www.lanxess.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clariant Brasil', websiteUrl: 'https://www.clariant.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solvay Brasil', websiteUrl: 'https://www.solvay.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evonik Brasil', websiteUrl: 'https://www.evonik.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huntsman Brasil', websiteUrl: 'https://www.huntsman.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhodia Brasil', websiteUrl: 'https://www.rhodia.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Momentive Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel Brasil', websiteUrl: 'https://www.henkel.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: '3M Brasil', websiteUrl: 'https://www.3m.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dupont Brasil', websiteUrl: 'https://www.dupont.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eastman Chemical Brasil', websiteUrl: 'https://www.eastman.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celanese Brasil', websiteUrl: 'https://www.celanese.com/br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cabot Brasil', websiteUrl: 'https://www.cabotcorp.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quiminova Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Petroquímica Suape', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultrapar Participações', websiteUrl: 'https://www.ultra.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quattor Petroquímica', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Politeno Indústria', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pronor Petroquímica', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Innova Petroquímica', websiteUrl: 'https://www.innova.ind.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IPQ Petroquímica', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deten Química', websiteUrl: 'https://www.deten.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ciquine Petroquímica', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covestro Brasil', websiteUrl: 'https://www.covestro.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toray Brasil', websiteUrl: 'https://www.toray.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LyondellBasell Brasil', websiteUrl: 'https://www.lyondellbasell.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Total Petrochemicals Brasil', websiteUrl: 'https://www.totalenergies.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inovyn Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mexichem Brasil', websiteUrl: 'https://www.orbia.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika Brasil', websiteUrl: 'https://bra.sika.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RPM International Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sherwin-Williams Brasil', websiteUrl: 'https://www.sherwin-williams.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Akzo Nobel Brasil', websiteUrl: 'https://www.akzonobel.com/pt/br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coral Tintas', websiteUrl: 'https://www.coral.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tintas Suvinil', websiteUrl: 'https://www.suvinil.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novos Materiais Eliokem', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kraton Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GreenVif Química Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Liqtech Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novaquim Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quaker Houghton Brasil', websiteUrl: 'https://www.quakerhoughton.com/pt-br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'W.R. Grace Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
];

// ========== ECOMMERCE_CARGO (50) ==========
const ECOMMERCE_CARGO: CompanyEntry[] = [
  { name: 'Mercado Livre Brasil', websiteUrl: 'https://www.mercadolivre.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magazine Luiza', websiteUrl: 'https://www.magazineluiza.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shopee Brasil', websiteUrl: 'https://shopee.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'iFood', websiteUrl: 'https://www.ifood.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rappi Brasil', websiteUrl: 'https://www.rappi.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amazon Brasil', websiteUrl: 'https://www.amazon.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Americanas', websiteUrl: 'https://www.americanas.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Submarino', websiteUrl: 'https://www.submarino.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shoptime', websiteUrl: 'https://www.shoptime.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carrefour Brasil E-commerce', websiteUrl: 'https://www.carrefour.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Casas Bahia Online', websiteUrl: 'https://www.casasbahia.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ponto (Pontofrio)', websiteUrl: 'https://www.pontofrio.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Extra Hipermercados Online', websiteUrl: 'https://www.extra.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netshoes', websiteUrl: 'https://www.netshoes.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dafiti Brasil', websiteUrl: 'https://www.dafiti.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zattini Moda', websiteUrl: 'https://www.zattini.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kanui Brasil', websiteUrl: 'https://www.kanui.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OLX Brasil', websiteUrl: 'https://www.olx.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enjoei', websiteUrl: 'https://www.enjoei.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elo7 Marketplace', websiteUrl: 'https://www.elo7.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Correios Brasil', websiteUrl: 'https://www.correios.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loggi Tecnologia', websiteUrl: 'https://www.loggi.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Total Express', websiteUrl: 'https://www.totalexpress.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jadlog Transportes', websiteUrl: 'https://www.jadlog.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Azul Cargo Express', websiteUrl: 'https://www.azulcargo.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LATAM Cargo Brasil', websiteUrl: 'https://www.latamcargo.com/pt-br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gol Cargo', websiteUrl: 'https://www.voegol.com.br/cargo', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercado Envios', websiteUrl: 'https://www.mercadolivre.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mandaê Logística', websiteUrl: 'https://www.mandae.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intelipost', websiteUrl: 'https://www.intelipost.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frenet Logística', websiteUrl: 'https://www.frenet.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Melhor Envio', websiteUrl: 'https://melhorenvio.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olist Brasil', websiteUrl: 'https://olist.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VTEX Brasil', websiteUrl: 'https://vtex.com/pt-br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wake Commerce', websiteUrl: 'https://www.wake.tech', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Linx Commerce', websiteUrl: 'https://www.linx.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tray E-commerce', websiteUrl: 'https://www.tray.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuvemshop Brasil', websiteUrl: 'https://www.nuvemshop.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loja Integrada', websiteUrl: 'https://www.lojaintegrada.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shopify Brasil', websiteUrl: 'https://www.shopify.com/br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buscapé Brasil', websiteUrl: 'https://www.buscape.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zoom Produtos', websiteUrl: 'https://www.zoom.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mosaico Tecnologia', websiteUrl: 'https://www.mosaico.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercado Pago Brasil', websiteUrl: 'https://www.mercadopago.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PagSeguro', websiteUrl: 'https://pagseguro.uol.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Getnet Brasil', websiteUrl: 'https://www.getnet.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stone Pagamentos', websiteUrl: 'https://www.stone.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PicPay', websiteUrl: 'https://www.picpay.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ame Digital', websiteUrl: 'https://www.amedigital.com', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cielo Brasil', websiteUrl: 'https://www.cielo.com.br', sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
];

// ========== TELECOMMUNICATIONS (50) ==========
const TELECOMMUNICATIONS: CompanyEntry[] = [
  { name: 'Vivo Telefônica Brasil', websiteUrl: 'https://www.vivo.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Claro Brasil', websiteUrl: 'https://www.claro.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TIM Brasil', websiteUrl: 'https://www.tim.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oi Telecom', websiteUrl: 'https://www.oi.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Algar Telecom', websiteUrl: 'https://www.algartelecom.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sercomtel Telecom', websiteUrl: 'https://www.sercomtel.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brisanet Telecomunicações', websiteUrl: 'https://www.brisanet.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Desktop Sigmanet', websiteUrl: 'https://www.desktop.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sumicity Telecom', websiteUrl: 'https://www.sumicity.net.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Virtua NET', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hughes Network Brasil', websiteUrl: 'https://www.hughes.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starlink Brasil', websiteUrl: 'https://www.starlink.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embratel', websiteUrl: 'https://www.embratel.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GVT Serviços', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NET Brasil', websiteUrl: 'https://www.claro.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sky Brasil', websiteUrl: 'https://www.sky.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson Brasil', websiteUrl: 'https://www.ericsson.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia Brasil', websiteUrl: 'https://www.nokia.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei Brasil', websiteUrl: 'https://www.huawei.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZTE Brasil', websiteUrl: 'https://www.zte.com.cn/brazil', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cisco Brasil', websiteUrl: 'https://www.cisco.com/c/pt_br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Qualcomm Brasil', websiteUrl: 'https://www.qualcomm.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samsung Networks Brasil', websiteUrl: 'https://www.samsung.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intelbras Telecom', websiteUrl: 'https://www.intelbras.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Totvs Brasil', websiteUrl: 'https://www.totvs.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CI&T', websiteUrl: 'https://www.ciandt.com/br-pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stefanini Brasil', websiteUrl: 'https://stefanini.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Accenture Brasil', websiteUrl: 'https://www.accenture.com/br-pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capgemini Brasil', websiteUrl: 'https://www.capgemini.com/br-pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IBM Brasil', websiteUrl: 'https://www.ibm.com/br-pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oracle Brasil', websiteUrl: 'https://www.oracle.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAP Brasil', websiteUrl: 'https://www.sap.com/brazil', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Microsoft Brasil', websiteUrl: 'https://www.microsoft.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Google Brasil', websiteUrl: 'https://www.google.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meta Brasil', websiteUrl: 'https://www.meta.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amazon Web Services Brasil', websiteUrl: 'https://aws.amazon.com/pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NTT Data Brasil', websiteUrl: 'https://br.nttdata.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wipro Brasil', websiteUrl: 'https://www.wipro.com/pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HCL Technologies Brasil', websiteUrl: 'https://www.hcltech.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Infosys Brasil', websiteUrl: 'https://www.infosys.com/br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TCS Brasil', websiteUrl: 'https://www.tcs.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unisys Brasil', websiteUrl: 'https://www.unisys.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DXC Technology Brasil', websiteUrl: 'https://dxc.com/br/pt', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teleperformance Brasil', websiteUrl: 'https://www.teleperformance.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atento Brasil', websiteUrl: 'https://www.atento.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Almaviva Brasil', websiteUrl: 'https://www.almaviva.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Concentrix Brasil', websiteUrl: 'https://www.concentrix.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'iQSTEL Brasil', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sinch Brasil', websiteUrl: 'https://www.sinch.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Twilio Brasil', websiteUrl: 'https://www.twilio.com/pt-br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
];

const ALL_ENTRIES: CompanyEntry[] = [
  ...HOSPITALITY_TOURISM,
  ...AGRICULTURE,
  ...SECURITY_SERVICES,
  ...FACILITY_MANAGEMENT,
  ...METAL_STEEL,
  ...CHEMICALS_PLASTICS,
  ...ECOMMERCE_CARGO,
  ...TELECOMMUNICATIONS,
];

async function main() {
  const market = Market.BR;
  console.log(`Seeding ${ALL_ENTRIES.length} companies for BR market (part 2)...`);

  let count = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl ?? undefined, sector: entry.sector },
        create: {
          name: entry.name,
          slug,
          market,
          sector: entry.sector,
          websiteUrl: entry.websiteUrl,
          isActive: true,
        },
      });

      await prisma.crawlSource.upsert({
        where: { id: company.id },
        update: {},
        create: {
          id: company.id,
          companyId: company.id,
          name: `${entry.name} Vagas`,
          type: entry.sourceType as any,
          crawlMethod: CrawlMethod.HTML,
          seedUrls: [],
          schedule: '0 3 * * *',
          agingDays: 14,
          market,
          isActive: true,
        },
      });
      count++;
    } catch (e: any) {
      console.error(`  ✗ ${entry.name}: ${e.message}`);
    }
  }

  console.log(`\n✓ Seeded ${count}/${ALL_ENTRIES.length} companies for BR (part 2)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
