import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });
const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  websiteUrl: string | null;
  sector: Sector;
  sourceType: SourceType;
}

function slugify(text: string): string {
  return text.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// ========== LOGISTICS_TRANSPORTATION (30) ==========
const LOGISTICS: CompanyEntry[] = [
  { name: 'Rivigo', websiteUrl: 'https://www.rivigo.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TCI Freight', websiteUrl: 'https://www.tcil.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Patel Integrated Logistics', websiteUrl: 'https://www.patelintegrated.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spoton Logistics', websiteUrl: 'https://www.spoton.co.in', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loadshare Networks', websiteUrl: 'https://www.loadshare.net', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delhivery Freight', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Blackbuck (Zinka)', websiteUrl: 'https://www.blackbuck.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ElasticRun', websiteUrl: 'https://www.elastic.run', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Logistics Express', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bangalore Metropolitan Transport', websiteUrl: 'https://www.mybmtc.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chennai Metro Rail', websiteUrl: 'https://chennaimetrorail.org', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lucknow Metro', websiteUrl: 'https://www.luckknowmetrorail.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kochi Metro', websiteUrl: 'https://kochimetro.org', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nagpur Metro', websiteUrl: 'https://www.metrorailnagpur.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jaipur Metro', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyderabad Metro Rail', websiteUrl: 'https://www.ltmetro.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat State Road Transport', websiteUrl: 'https://www.gsrtc.in', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rajasthan State Road Transport', websiteUrl: 'https://www.rsrtc.rajasthan.gov.in', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UP State Road Transport', websiteUrl: 'https://www.upsrtc.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Punjab Roadways', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kerala State Road Transport', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Madhya Pradesh State Road Transport', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cochin Shipyard', websiteUrl: 'https://www.cochinshipyard.in', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shipping Corporation of India', websiteUrl: 'https://www.shipindia.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inland Waterways Authority', websiteUrl: 'https://www.iwai.nic.in', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kolkata Metro', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ahmedabad Metro', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pune Metro', websiteUrl: 'https://www.punemetrorail.org', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Namma Yatri', websiteUrl: 'https://www.nammayatri.in', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LoadExx', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
];

// ========== MANUFACTURING (30) ==========
const MANUFACTURING: CompanyEntry[] = [
  { name: 'Tata Advanced Systems Limited', websiteUrl: 'https://www.tataadvancedsystems.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thermax Limited', websiteUrl: 'https://www.thermaxglobal.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kirloskar Oil Engines', websiteUrl: 'https://www.kirloskar.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elgi Equipments', websiteUrl: 'https://www.elgi.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Triveni Turbine', websiteUrl: 'https://www.triveniturbines.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mazagon Dock Shipbuilders', websiteUrl: 'https://www.mazagondock.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garden Reach Shipbuilders', websiteUrl: 'https://www.grse.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BEL Optronic Devices', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HMT Machine Tools', websiteUrl: 'https://www.hmtindia.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BEML Limited', websiteUrl: 'https://www.bemlindia.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CG Power Industrial', websiteUrl: 'https://www.cgglobal.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Finolex Pipes', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Batliboi Limited', websiteUrl: 'https://www.batliboi.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grindwell Norton', websiteUrl: 'https://www.grindwellnorton.co.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AIA Engineering', websiteUrl: 'https://www.aiaengineering.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Praj Industries', websiteUrl: 'https://www.praj.net', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kennametal India', websiteUrl: 'https://www.kennametal.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharat Dynamics Limited', websiteUrl: 'https://www.bdl-india.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ordnance Factory Board', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DRDO Labs', websiteUrl: 'https://www.drdo.gov.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Timken India', websiteUrl: 'https://www.timken.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKF India', websiteUrl: 'https://www.skf.com/in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NRB Bearings', websiteUrl: 'https://www.nrbbearings.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Minda Corporation', websiteUrl: 'https://www.sparkminda.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sundram Fasteners', websiteUrl: 'https://www.sundram.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amara Raja Energy', websiteUrl: 'https://www.amararajabatteries.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hindustan Aeronautics Limited', websiteUrl: 'https://www.hal-india.co.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cochin Shipyard Manufacturing', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goa Shipyard Limited', websiteUrl: 'https://www.goashipyard.in', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharat Earth Movers', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
];

// ========== RETAIL (30) ==========
const RETAIL: CompanyEntry[] = [
  { name: 'Aditya Birla Retail', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trent Limited (Westside)', websiteUrl: 'https://www.trentlimited.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avenue Supermarts (DMart)', websiteUrl: 'https://www.dmartindia.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Future Enterprises', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vishal Mega Mart', websiteUrl: 'https://www.vishalmegamart.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Star Bazaar (Trent)', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro Cash & Carry India', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spar India', websiteUrl: 'https://www.sparindia.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nature\'s Basket', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Easyday Club', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JioMart Retail', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FirstCry', websiteUrl: 'https://www.firstcry.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nykaa Fashion', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata CLiQ Luxury', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chroma Retail', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reliance Trends', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Max Retail (Landmark Group)', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Central Shopping Mall', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brand Factory India', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hamleys India', websiteUrl: 'https://www.hamleys.in', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chumbak', websiteUrl: 'https://www.chumbak.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lenskart', websiteUrl: 'https://www.lenskart.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CaratLane', websiteUrl: 'https://www.caratlane.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Malabar Gold India', websiteUrl: 'https://www.malabargoldanddiamonds.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Titan Eye Plus', websiteUrl: 'https://www.titaneyeplus.com', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crossword Bookstores', websiteUrl: 'https://www.crossword.in', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hamley\'s Hamleys', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chai Point Retail', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reliance Fresh', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heritage Fresh', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
];

// ========== CONSTRUCTION (30) ==========
const CONSTRUCTION: CompanyEntry[] = [
  { name: 'Tata Projects Limited', websiteUrl: 'https://www.tataprojects.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nagarjuna Construction', websiteUrl: 'https://www.nccltd.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HCC Concessions', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ITD Cementation India', websiteUrl: 'https://www.itdcem.co.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ahluwalia Contracts', websiteUrl: 'https://www.acaborwal.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'B L Kashyap & Sons', websiteUrl: 'https://www.blkashyap.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capacit\'e Infraprojects', websiteUrl: 'https://www.capacite.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PSP Projects', websiteUrl: 'https://www.pspprojects.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Voltas Projects', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Megha Engineering (MEIL)', websiteUrl: 'https://www.meghaengineering.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Apco Infratech', websiteUrl: 'https://www.apcoinfraltd.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ashoka Buildcon', websiteUrl: 'https://www.ashokabuildcon.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Welspun Enterprises Construction', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JMC Projects', websiteUrl: 'https://www.jmcprojects.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Man Infraconstruction', websiteUrl: 'https://www.maninfra.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gammon Engineers', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Montecarlo Limited', websiteUrl: 'https://www.montecarlo.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EPC Construction India', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RPS Group India', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gayatri Projects', websiteUrl: 'https://www.gayatri.co.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ramky Infrastructure', websiteUrl: 'https://www.ramkyinfrastructure.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Navayuga Engineering', websiteUrl: 'https://www.navayuga.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kalpataru Projects International', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hiranandani Constructions', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DB Realty Construction', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NBCC Construction', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rail Vikas Nigam', websiteUrl: 'https://www.rvnl.org', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NHPC Limited', websiteUrl: 'https://www.nhpcindia.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WAPCOS Limited', websiteUrl: 'https://www.wapcos.gov.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CPWD India', websiteUrl: 'https://cpwd.gov.in', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
];

// ========== FOOD_BEVERAGE (30) ==========
const FOOD_BEVERAGE: CompanyEntry[] = [
  { name: 'Varun Beverages', websiteUrl: 'https://www.varunbeverages.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hatsun Agro Products', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dodla Dairy', websiteUrl: 'https://www.dodladairy.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parag Milk Foods Ltd', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Venky\'s India', websiteUrl: 'https://www.vfrsindia.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Godrej Tyson Foods', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suguna Foods', websiteUrl: 'https://www.sugunafoods.co.in', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKM Egg Products', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lotte India', websiteUrl: 'https://www.lotteindia.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Consumer Products Ltd', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prataap Snacks', websiteUrl: 'https://www.prataapsnacks.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DFM Foods', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jubilant FoodWorks', websiteUrl: 'https://www.jubilantfoodworks.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Devyani International', websiteUrl: 'https://www.devyaniinternational.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sapphire Foods India', websiteUrl: 'https://www.sapphirefoods.in', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Westlife Foodworld (McDonald\'s)', websiteUrl: 'https://www.westlife.co.in', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Starbucks', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hector Beverages (Paper Boat)', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zydus Wellness', websiteUrl: 'https://www.zyduswellness.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adani Wilmar', websiteUrl: 'https://www.adaniwilmar.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emami Agrotech', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ruchi Soya Industries', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Creambell Ice Cream', websiteUrl: 'https://www.creambell.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kwality Limited', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schreiber Dynamix Dairies', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Keventers Dairy', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frooti (Parle Agro)', websiteUrl: 'https://www.parleagro.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paper Boat Beverages', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nandini Milk (KMF)', websiteUrl: 'https://www.kmfnandini.coop', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aavin Dairy', websiteUrl: 'https://www.aavinmilk.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== AUTOMOTIVE (30) ==========
const AUTOMOTIVE: CompanyEntry[] = [
  { name: 'Tata Motors Passenger', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bajaj Auto Pune', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TVS Motor Hosur', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Electric', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Motors EV', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piaggio India', websiteUrl: 'https://www.piaggio.co.in', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Isuzu Motors India', websiteUrl: 'https://www.isuzuindia.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MG Motor India Halol', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Citroen India Thiruvallur', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BYD India', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Probiking (Bajaj)', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hero Electric India', websiteUrl: 'https://www.heroelectric.in', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Okinawa Autotech', websiteUrl: 'https://www.okinawascooters.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Greaves Electric', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultraviolette Automotive', websiteUrl: 'https://www.ultraviolette.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Simple Energy', websiteUrl: 'https://www.simpleenergy.in', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Omega Seiki Mobility', websiteUrl: 'https://www.omegaseiki.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euler Motors', websiteUrl: 'https://www.eulermotors.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Switch Mobility (Ashok Leyland)', websiteUrl: 'https://www.switchmobility.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olectra Greentech', websiteUrl: 'https://www.olectra.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JBM Electric Vehicles', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sona BLW Precision', websiteUrl: 'https://www.sonablw.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharat Forge Automotive', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samvardhana Motherson', websiteUrl: 'https://www.motherson.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Varroc Engineering', websiteUrl: 'https://www.varroc.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wheels India', websiteUrl: 'https://www.wheelsindia.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rane Holdings', websiteUrl: 'https://www.rfrsa.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lumax Auto Technologies', websiteUrl: 'https://www.lumaxautotech.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shriram Pistons', websiteUrl: 'https://www.shrirampiston.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ucal Fuel Systems', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== TEXTILE (30) ==========
const TEXTILE: CompanyEntry[] = [
  { name: 'Arvind SmartSpaces', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Welspun Living', websiteUrl: 'https://www.welspunliving.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bombay Rayon Fashions', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'S.P. Apparels', websiteUrl: 'https://www.spapparels.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pearl Global Industries', websiteUrl: 'https://www.pearlglobal.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PDS Limited (Fashion)', websiteUrl: 'https://www.pdsmultinational.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siyaram Woollen Mills', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monte Carlo Textiles', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rupa Knitwear', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jockey India (Page Industries)', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lux Cozi (Lux Industries)', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Himatsingka Textiles', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Donear Industries', websiteUrl: 'https://www.doneargroup.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nahar Spinning Mills', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suryalakshmi Cotton Mills', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nitin Spinners Ltd', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trident Textiles', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DCM Nouvelle', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lakshmi Machine Works', websiteUrl: 'https://www.lakshmimach.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rieter India', websiteUrl: 'https://www.rieter.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nahar Industrial Textiles', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sangam Spinners', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Super Spinning Mills', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loyal Textile Exports', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sutherland Global Textiles', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ambika Cotton Exports', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Precot Limited', websiteUrl: 'https://www.precot.com', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KG Denim Ltd', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Premier Polyfilm', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Best Cotton Mills', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== MINING_ENERGY (30) ==========
const MINING_ENERGY: CompanyEntry[] = [
  { name: 'JSW Energy Renewable', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Power Solar', websiteUrl: 'https://www.tatapowersolar.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Waaree Energies', websiteUrl: 'https://www.waaree.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Premier Energies', websiteUrl: 'https://www.premierenergies.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vikram Solar', websiteUrl: 'https://www.vikramsolar.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hero Future Energies', websiteUrl: 'https://www.herofutureenergies.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CleanMax Solar', websiteUrl: 'https://www.cleanmax.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fourth Partner Energy', websiteUrl: 'https://www.fourthpartnerenergy.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amp Energy India', websiteUrl: 'https://www.ampenergy.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'O2 Power', websiteUrl: 'https://www.o2power.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SB Energy (SoftBank)', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CESC Green', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahanadi Coalfields', websiteUrl: 'https://www.mahanadicoal.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Northern Coalfields', websiteUrl: 'https://www.nclcil.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'South Eastern Coalfields', websiteUrl: 'https://www.secl.gov.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Central Coalfields', websiteUrl: 'https://www.centralcoalfields.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharat Coking Coal', websiteUrl: 'https://www.bcclweb.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Western Coalfields', websiteUrl: 'https://www.westerncoal.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Singareni Collieries', websiteUrl: 'https://www.scclmines.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neyveli Lignite (NLC India)', websiteUrl: 'https://www.nlcindia.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MOIL Mining', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hindustan Copper Mining', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uranium Corporation of India', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indian Rare Earths', websiteUrl: 'https://www.irel.co.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GMDC Gujarat', websiteUrl: 'https://www.gmdcltd.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KIOCL Limited', websiteUrl: 'https://www.kiocl.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SJVN Limited', websiteUrl: 'https://www.sjvn.nic.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'THDC India', websiteUrl: 'https://www.thdc.co.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NHDC Limited', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'North Eastern Electric Power', websiteUrl: 'https://www.neepco.co.in', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
];

// ========== HEALTHCARE (30) ==========
const HEALTHCARE: CompanyEntry[] = [
  { name: 'AIIMS Delhi', websiteUrl: 'https://www.aiims.edu', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PGIMER Chandigarh', websiteUrl: 'https://pgimer.edu.in', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CMC Vellore', websiteUrl: 'https://www.cmch-vellore.edu', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sanjay Gandhi Memorial Hospital', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Safdarjung Hospital', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JIPMER Puducherry', websiteUrl: 'https://jipmer.edu.in', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NIMHANS Bangalore', websiteUrl: 'https://nimhans.ac.in', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Memorial Hospital Mumbai', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cloudnine Hospitals', websiteUrl: 'https://www.cloudninecare.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sahyadri Hospitals Pune', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sterling Hospitals Gujarat', websiteUrl: 'https://www.sterlinghospitals.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paras Hospitals', websiteUrl: 'https://www.parashospitals.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aakash Healthcare', websiteUrl: 'https://www.aakashhealthcare.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zydus Hospitals', websiteUrl: 'https://www.zydushospitals.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HCG Oncology', websiteUrl: 'https://www.hcgoncology.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primus Hospital', websiteUrl: 'https://www.primushospital.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jaslok Hospital', websiteUrl: 'https://www.jaslokhospital.net', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Breach Candy Hospital', websiteUrl: 'https://www.breachcandyhospital.org', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lilavati Hospital', websiteUrl: 'https://www.lilavatihospital.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Global Hospitals Hyderabad', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gleneagles Hospital India', websiteUrl: 'https://www.gleneaglesglobalhospitals.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KIMS Hospital Hyderabad', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aster MIMS Kerala', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baby Memorial Hospital', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shalby Hospitals', websiteUrl: 'https://www.shalby.org', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amrita Hospital', websiteUrl: 'https://www.amritahospital.org', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sir Ganga Ram Hospital', websiteUrl: 'https://www.sgrh.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BLK-Max Hospital', websiteUrl: 'https://www.blkmaxhospital.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dharamshila Narayana Hospital', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sakra World Hospital', websiteUrl: 'https://www.sakraworldhospital.com', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== HOSPITALITY_TOURISM (30) ==========
const HOSPITALITY_TOURISM: CompanyEntry[] = [
  { name: 'Sarovar Hotels Group', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Apeejay Surrendra Park Hotels', websiteUrl: 'https://www.theparkhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sinclairs Hotels', websiteUrl: 'https://www.sinclairshotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Royal Orchid Hotels', websiteUrl: 'https://www.royalorchidhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vistara Hotels', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lords Hotels & Resorts', websiteUrl: 'https://www.lordshotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pride Hotels', websiteUrl: 'https://www.pridehotel.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fortune Hotels (ITC)', websiteUrl: 'https://www.fortunehotels.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivanta Hotels', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ginger Hotels', websiteUrl: 'https://www.gingerhotels.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Club Mahindra Resorts', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jungle Lodges Karnataka', websiteUrl: 'https://www.junglelodges.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kerala Tourism (KTDC)', websiteUrl: 'https://www.ktdc.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ITDC (India Tourism)', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Niraamaya Retreats', websiteUrl: 'https://www.niraamaya.in', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CGH Earth Hotels', websiteUrl: 'https://www.cghearth.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evolve Back Resorts', websiteUrl: 'https://www.evolveback.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SeleQtions (IHCL)', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ibis India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novotel India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Holiday Inn India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Four Points by Sheraton India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crowne Plaza India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JW Marriott India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ritz-Carlton India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'W Hotels India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conrad India', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thomas Cook India Travel', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yatra Online Travel', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EaseMyTrip', websiteUrl: 'https://www.easemytrip.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
];

// ========== AGRICULTURE (30) ==========
const AGRICULTURE: CompanyEntry[] = [
  { name: 'National Dairy Development Board', websiteUrl: 'https://www.nddb.coop', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IFFCO Tokio', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Godrej Agrovet Ltd', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPL Crop Protection', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Krishi Vigyan Kendra Network', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Seeds Corporation', websiteUrl: 'https://www.indiaseeds.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rashtriya Chemicals Fertilizers', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat State Fertilizers', websiteUrl: 'https://www.gsfclimited.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Southern Petrochemical Agri', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paradeep Phosphates', websiteUrl: 'https://www.paradeepphosphates.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mangalore Chemicals Fertilizers', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Chemicals Agri', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EM3 AgriServices', websiteUrl: 'https://www.em3agri.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TartanSense', websiteUrl: 'https://www.tartansense.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CropIn Technology', websiteUrl: 'https://www.cropin.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intello Labs', websiteUrl: 'https://www.intello.ai', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SatSure', websiteUrl: 'https://www.satsure.co', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stellapps', websiteUrl: 'https://www.stellapps.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Promethean Power Systems', websiteUrl: 'https://www.prometheanpower.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'S4S Technologies', websiteUrl: 'https://www.s4stechnologies.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ergos Business Solutions', websiteUrl: 'https://www.ergos.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SuperZop', websiteUrl: 'https://www.superzop.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Otipy (CROFARM)', websiteUrl: 'https://www.otipy.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Licious Agri Supply', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'InfyU Labs', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arya.ag', websiteUrl: 'https://www.arya.ag', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gramophone (Agri)', websiteUrl: 'https://www.gramophone.in', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samunnati Financial', websiteUrl: 'https://www.samunnati.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sahyadri Farmer Producer', websiteUrl: 'https://www.sahyadrifarms.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'INI Farms', websiteUrl: 'https://www.inifarms.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
];

// ========== SECURITY_SERVICES (30) ==========
const SECURITY_SERVICES: CompanyEntry[] = [
  { name: 'SIS Security Solutions', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tops Group Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Checkmate Security Services', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Group 4 India', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Securitas India Services', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur India Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultimate Security Alliance', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gorkha Security Services', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gurukrupa Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shield India Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Topsgrup India', websiteUrl: 'https://www.topsgrup.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KSS Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WPSI Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VProtect Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenon Group India', websiteUrl: 'https://www.tenonfm.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Matrix Business Services Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NSSG Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lancers Network', websiteUrl: 'https://www.lancersnetwork.com', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Centurion Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agile Security India', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rapid Security Force', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Security Guards Board', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'National Security Guard', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CISF (Airport Security)', websiteUrl: 'https://www.cisf.gov.in', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro One Loss Prevention', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Premier Vigilance Services', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valor Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SafeHouse Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'United Security Alliance India', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samson Security', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
];

// ========== FACILITY_MANAGEMENT (30) ==========
const FACILITY_MANAGEMENT: CompanyEntry[] = [
  { name: 'BVG India FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quess Facility Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embassy Services FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RMZ FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mindspace FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mace India FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Varmora FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Godrej Housekeeping', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OCS India FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS India Facility Mgmt', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dusters Total Solutions', websiteUrl: 'https://www.dusterstotalsolutions.com', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenon FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SFO Technologies FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Macro FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Updater Services FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'White Knight FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Writer Relocations FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahindra Susten FM', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colliers FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Knight Frank FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savills FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brookfield FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Blackstone FM India', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Realty FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hiranandani FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DLF FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prestige FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brigade FM Services', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
];

// ========== METAL_STEEL (30) ==========
const METAL_STEEL: CompanyEntry[] = [
  { name: 'Vedanta Aluminium Jharsuguda', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NALCO Smelter Plant', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hindalco Aditya Birla', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Steel BSL (Bhushan)', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JSW Vijayanagar', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAIL Bokaro', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAIL Bhilai', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAIL Rourkela', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAIL Durgapur', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAIL Burnpur', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Steel Jamshedpur', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Steel Kalinganagar', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Electrosteel Steels', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Visa Steel', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gallantt Metal', websiteUrl: 'https://www.gallanttmetal.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shyam Steel Industries', websiteUrl: 'https://www.shyamsteel.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSP Steel and Power', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aarti Steels', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kamdhenu Limited', websiteUrl: 'https://www.kamdhenulimited.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'APL Apollo Tube Mills', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Surya Roshni Steel', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hi-Tech Pipes', websiteUrl: 'https://www.hitechpipes.in', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pennar Industries', websiteUrl: 'https://www.pennarindia.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Welspun Pipes', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MAN Industries India', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rathi Steel & Power', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sarda Energy & Minerals Ltd', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monnet Ispat & Energy', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adhunik Metaliks', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bhushan Steel Works', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
];

// ========== CHEMICALS_PLASTICS (30) ==========
const CHEMICALS_PLASTICS: CompanyEntry[] = [
  { name: 'Pidilite Chemical Division', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SRF Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aarti Industries Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deepak Nitrite Ltd', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alkyl Amines Ltd', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinati Organics Ltd', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Navin Fluorine Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gujarat Fluorochemicals Ltd', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tatva Chintan Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clean Science Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fine Organic Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Laxmi Organic Industries', websiteUrl: 'https://www.laxmiorganic.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neogen Chemicals', websiteUrl: 'https://www.neogenchemicals.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anupam Rasayan', websiteUrl: 'https://www.anupamrasayan.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aether Industries', websiteUrl: 'https://www.aetherindustries.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supreme Petrochem', websiteUrl: 'https://www.supremepetrochem.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Astral Polymers', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prince Pipes Plastics', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Finolex Plastic Industries', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supreme Industries Plastics', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nilkamal Plastics Division', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Time Technoplast', websiteUrl: 'https://www.timetechnoplast.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mold-Tek Packaging', websiteUrl: 'https://www.moldtekpackaging.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uflex Limited Plastics', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cosmo Films', websiteUrl: 'https://www.cosmofilms.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Polyplex Corporation', websiteUrl: 'https://www.polyplex.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SRF Packaging Films', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ester Industries', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garware Technical Fibres', websiteUrl: 'https://www.garwarefibres.com', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nocil Rubber Chemicals', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
];

// ========== ECOMMERCE_CARGO (30) ==========
const ECOMMERCE_CARGO: CompanyEntry[] = [
  { name: 'Amazon India Fulfillment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flipkart Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meesho Fulfillment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JioMart Fulfillment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Myntra Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Snapdeal Fulfilment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nykaa Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Blinkit Dark Stores', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zepto Dark Stores', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swiggy Instamart Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BigBasket Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Udaan Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IndiaMART Logistics', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ShopClues Fulfilment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paytm Mall Fulfilment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limeroad Logistics', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FirstCry Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pepperfry Logistics', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Urban Ladder Delivery', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lenskart Fulfilment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CaratLane Delivery', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cred Merchant Logistics', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PharmEasy Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netmeds Fulfilment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata 1mg Warehouse', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porter Last Mile', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dunzo Delivery Hub', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shadowfax Last Mile', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ecom Express Hub', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'XpressBees Sorting Center', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
];

// ========== TELECOMMUNICATIONS (30) ==========
const TELECOMMUNICATIONS: CompanyEntry[] = [
  { name: 'Reliance Jio Towers', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bharti Infratel', websiteUrl: 'https://www.bhartiinfratel.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indus Towers', websiteUrl: 'https://www.industowers.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'American Tower India', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Summit Digitel (Tower)', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GTL Infrastructure', websiteUrl: 'https://www.gtl.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RailTel Corporation', websiteUrl: 'https://www.railtelindia.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Power Grid Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tikona Infinet', websiteUrl: 'https://www.tikona.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spectra (Broadband)', websiteUrl: 'https://www.spectra.co', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netplus Broadband', websiteUrl: 'https://www.netplus.co.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alliance Broadband', websiteUrl: 'https://www.alliancebroadband.co.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Railwire (RailTel WiFi)', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TCIL (Telecom Consultants)', websiteUrl: 'https://www.tcil-india.com', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'C-DOT Telecom', websiteUrl: 'https://www.cdot.in', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BSNL Fiber', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airtel Xstream Box', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jio Fiber Installation', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vi (Vodafone Idea) Retail', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Teleservices Retail', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dishnet Wireless', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'D2H DTH Services', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tata Play Installation', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airtel DTH Installation', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sun Direct DTH', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jio Platforms Field', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sterlite Technologies Field', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Polycab India Cables Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HFCL Fiber Deployment', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tejas Networks Deployment', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
];

// ========== OTHER (31) ==========
const OTHER: CompanyEntry[] = [
  { name: 'Municipal Corporation Delhi', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BMC Mumbai', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BBMP Bangalore', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GHMC Hyderabad', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chennai Corporation', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PMC Pune', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMC Ahmedabad', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KMC Kolkata', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NDMC New Delhi', websiteUrl: 'https://www.ndmc.gov.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indian Army Recruitment', websiteUrl: 'https://www.joinindianarmy.nic.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indian Navy Recruitment', websiteUrl: 'https://www.joinindiannavy.gov.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indian Air Force Recruitment', websiteUrl: 'https://afcat.cdac.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SSC Recruitment', websiteUrl: 'https://ssc.nic.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Railway Recruitment Board', websiteUrl: 'https://www.rrbcdg.gov.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'India Post Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delhi Police Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UP Police Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maharashtra Police Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'State Bank of India (Peon/Clerk)', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Punjab National Bank (Peon)', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Canara Bank (Sub-staff)', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FCI Recruitment', websiteUrl: 'https://www.fci.gov.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ONGC Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BHEL Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HAL Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISRO Technical Staff', websiteUrl: 'https://www.isro.gov.in', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BEL Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DRDO Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ECIL Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NLC Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NTPC Recruitment', websiteUrl: null, sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
];

const ALL_ENTRIES: CompanyEntry[] = [
  ...LOGISTICS,
  ...MANUFACTURING,
  ...RETAIL,
  ...CONSTRUCTION,
  ...FOOD_BEVERAGE,
  ...AUTOMOTIVE,
  ...TEXTILE,
  ...MINING_ENERGY,
  ...HEALTHCARE,
  ...HOSPITALITY_TOURISM,
  ...AGRICULTURE,
  ...SECURITY_SERVICES,
  ...FACILITY_MANAGEMENT,
  ...METAL_STEEL,
  ...CHEMICALS_PLASTICS,
  ...ECOMMERCE_CARGO,
  ...TELECOMMUNICATIONS,
  ...OTHER,
];

async function main() {
  const market = Market.IN;
  console.log(`Seeding ${ALL_ENTRIES.length} companies for IN market (part 3)...`);

  let count = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl ?? undefined, sector: entry.sector },
        create: {
          name: entry.name,
          slug,
          market,
          sector: entry.sector,
          websiteUrl: entry.websiteUrl,
          isActive: true,
        },
      });

      await prisma.crawlSource.upsert({
        where: { id: company.id },
        update: {},
        create: {
          id: company.id,
          companyId: company.id,
          name: `${entry.name} Job Listings`,
          type: entry.sourceType as any,
          crawlMethod: CrawlMethod.HTML,
          seedUrls: [],
          schedule: '0 3 * * *',
          agingDays: 14,
          market,
          isActive: true,
        },
      });
      count++;
    } catch (e: any) {
      console.error(`  ✗ ${entry.name}: ${e.message}`);
    }
  }

  console.log(`\n✓ Seeded ${count}/${ALL_ENTRIES.length} companies for IN (part 3)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
