import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });
const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  websiteUrl: string | null;
  sector: Sector;
  sourceType: SourceType;
}

function slugify(text: string): string {
  return text.toLowerCase()
    .replace(/[áàâã]/g, 'a').replace(/[éèê]/g, 'e').replace(/[íì]/g, 'i')
    .replace(/[óòôõ]/g, 'o').replace(/[úù]/g, 'u').replace(/ç/g, 'c')
    .replace(/ñ/g, 'n')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

const ALL_ENTRIES: CompanyEntry[] = [
// ========== LOGISTICS_TRANSPORTATION (30) ==========
  { name: 'Rumo Logística', websiteUrl: 'https://www.rumolog.com', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VLI Multimodal', websiteUrl: 'https://www.vli-logistica.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MRS Logística', websiteUrl: 'https://www.mrs.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ALL Logística', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transnordestina Logística', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flecha Bus Brasil', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação Garcia', websiteUrl: 'https://www.garciabraga.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação Águia Branca', websiteUrl: 'https://www.aguiabranca.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação 1001', websiteUrl: 'https://www.autoviacao1001.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação Progresso', websiteUrl: 'https://www.progressoonline.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação São Geraldo', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação Kaissara', websiteUrl: 'https://www.kaissara.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viação Gontijo', websiteUrl: 'https://www.gontijo.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TNT Mercúrio', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Patrus Transportes', websiteUrl: 'https://www.patrus.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rodonaves Transportes', websiteUrl: 'https://www.rodonaves.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jamef Transportes', websiteUrl: 'https://www.jamef.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savar Logística', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AGV Logística', websiteUrl: 'https://www.agv.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coopercarga', websiteUrl: 'https://www.coopercarga.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cargo X Brasil', websiteUrl: 'https://www.cargox.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Translovato', websiteUrl: 'https://www.translovato.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Transpes', websiteUrl: 'https://www.transpes.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Expresso Jundiaí', websiteUrl: 'https://www.expressojundiai.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Libra Logística', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rapidão Transportes', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transdata Logística', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MAP Transportes', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rápido 900', websiteUrl: null, sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Luft Logística', websiteUrl: 'https://www.luft.com.br', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },

// ========== MANUFACTURING (30) ==========
  { name: 'Neobus Ônibus', websiteUrl: 'https://www.neobus.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iochpe-Maxion', websiteUrl: 'https://www.iochpe.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahle Metal Leve', websiteUrl: 'https://www.mahle.com/pt/brazil', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZF do Brasil', websiteUrl: 'https://www.zf.com/brazil', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Faber-Castell Brasil', websiteUrl: 'https://www.faber-castell.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tigre Tubos e Conexões', websiteUrl: 'https://www.tigre.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Docol Metais Sanitários', websiteUrl: 'https://www.docol.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deca Louças', websiteUrl: 'https://www.deca.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lorenzetti', websiteUrl: 'https://www.lorenzetti.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Duratex Madeiras', websiteUrl: 'https://www.duratex.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Klabin Embalagens', websiteUrl: 'https://www.klabin.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suzano Papel', websiteUrl: 'https://www.suzano.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cenibra', websiteUrl: 'https://www.cenibra.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eldorado Brasil Celulose', websiteUrl: 'https://www.eldoradobrasil.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fibria (Suzano)', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embraco Compressores', websiteUrl: 'https://www.embraco.com', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schneider Electric Brasil Fab', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens Brasil Fábrica', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vulcabras Fábrica', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nadir Figueiredo', websiteUrl: 'https://www.nadirfigueiredo.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Panasonic Brasil', websiteUrl: 'https://www.panasonic.com/br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LG Electronics Brasil', websiteUrl: 'https://www.lg.com/br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brastemp Fábrica', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Taurus Armas', websiteUrl: 'https://www.taurusarmas.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forjas Taurus', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Weg Tintas', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jacto Máquinas', websiteUrl: 'https://www.jacto.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pial Legrand', websiteUrl: 'https://www.pfrlegrand.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Votorantim Energia', websiteUrl: null, sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Termotécnica', websiteUrl: 'https://www.termotecnica.com.br', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },

// ========== RETAIL (30) ==========
  { name: 'Leroy Merlin Brasil Varejo', websiteUrl: 'https://www.leroymerlin.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telhanorte', websiteUrl: 'https://www.telhanorte.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'C&C Casa e Construção', websiteUrl: 'https://www.cec.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tumelero', websiteUrl: 'https://www.tumelero.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivara Joias', websiteUrl: 'https://www.vivara.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cacau Show', websiteUrl: 'https://www.cacaushow.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'O Boticário Lojas', websiteUrl: 'https://www.boticario.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tok&Stok', websiteUrl: 'https://www.tokstok.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Madeira Madeira', websiteUrl: 'https://www.madeiramadeira.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pernambucanas', websiteUrl: 'https://www.pernambucanas.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenda Atacado', websiteUrl: 'https://www.tendaatacado.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supermercados Nacional', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supermercados Zona Sul', websiteUrl: 'https://www.zonasul.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supermercados Pague Menos', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Angeloni Supermercados', websiteUrl: 'https://www.angeloni.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bretas Supermercados', websiteUrl: 'https://www.bretas.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cencosud Brasil', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dia Supermercados', websiteUrl: 'https://www.dia.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Condor Supermercados', websiteUrl: 'https://www.condor.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Makro Atacadista', websiteUrl: 'https://www.makro.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fort Atacadista', websiteUrl: 'https://www.fortatacadista.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nagumo Supermercados', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prezunic Supermercados', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sonda Supermercados', websiteUrl: 'https://www.sfronda.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zaffari Supermercados', websiteUrl: 'https://www.zfraffari.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Muffato Supermercados', websiteUrl: 'https://www.supermuffato.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savegnago Supermercados', websiteUrl: 'https://www.savegnago.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oba Hortifruti', websiteUrl: 'https://www.obahortifruti.com.br', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultrabox Supermercados', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ABC Supermercados', websiteUrl: null, sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },

// ========== CONSTRUCTION (30) ==========
  { name: 'Cyrela Engenharia', websiteUrl: 'https://www.cyrela.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MRV Construtora', websiteUrl: 'https://www.mrv.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenda Construtora', websiteUrl: 'https://www.tfrenda.com', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Even Engenharia', websiteUrl: 'https://www.even.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EZTec Construtora', websiteUrl: 'https://www.eztec.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tecnisa', websiteUrl: 'https://www.tecnisa.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gafisa Construtora', websiteUrl: 'https://www.gafisa.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Helbor Construtora', websiteUrl: 'https://www.helbor.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rossi Construtora', websiteUrl: 'https://www.rossiresidencial.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viver Engenharia', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PDG Construtora', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Queiroz Galvão Construção', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OAS Engenharia', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Odebrecht Construção', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Serveng Civilsan', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mendes Júnior Engenharia', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cury Construtora', websiteUrl: 'https://www.cfrury.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Plano&Plano Construtora', websiteUrl: 'https://www.planoplano.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Moura Dubeux Construtora', websiteUrl: 'https://www.mouradubeux.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JHSF Construção', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WTorre Construção', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tegra Engenharia', websiteUrl: 'https://www.tegra.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MPD Engenharia', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MAC Engenharia', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Patriani Construtora', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kallas Incorporações', websiteUrl: 'https://www.kallas.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brookfield Construção', websiteUrl: null, sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKR Construtora', websiteUrl: 'https://www.skr.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mitre Realty', websiteUrl: 'https://www.mifrtrerealty.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lavvi Construtora', websiteUrl: 'https://www.lavvi.com.br', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },

// ========== FOOD_BEVERAGE (30) ==========
  { name: 'Coca-Cola Andina Brasil', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Heineken Brasil', websiteUrl: 'https://www.heinekenbrasil.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Diageo Brasil', websiteUrl: 'https://www.diageo.com/pt-br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pernod Ricard Brasil', websiteUrl: 'https://www.pernod-ricard.com/br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danone Brasil Alimentos', websiteUrl: 'https://www.danone.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'General Mills Brasil', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kellogg Brasil', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bob\'s Hamburgers', websiteUrl: 'https://www.bfrobs.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Habib\'s Restaurantes', websiteUrl: 'https://www.habibs.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spoleto Restaurantes', websiteUrl: 'https://www.spoleto.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Madero Restaurantes', websiteUrl: 'https://www.restaurantemadero.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'China In Box', websiteUrl: 'https://www.chinainbox.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Subway Brasil Restaurantes', websiteUrl: 'https://www.subway.com/pt-BR', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starbucks Brasil Cafés', websiteUrl: 'https://www.starbucks.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dominos Pizza Brasil', websiteUrl: 'https://www.dominos.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Trigo Restaurantes', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coco Bambu', websiteUrl: 'https://www.cocobambu.com', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rede Giraffas Restaurantes', websiteUrl: 'https://www.giraffas.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Le Biscuit', websiteUrl: 'https://www.lebiscuit.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pão de Açúcar Alimentos', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forno de Minas Alimentos', websiteUrl: 'https://www.fornodeminas.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wickbold', websiteUrl: 'https://www.wickbold.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pullman Pães', websiteUrl: null, sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seven Boys', websiteUrl: 'https://www.sevenboys.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Itambé Alimentos', websiteUrl: 'https://www.itambe.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigor Laticínios', websiteUrl: 'https://www.vigor.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tirol Laticínios', websiteUrl: 'https://www.tirol.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piracanjuba Laticínios', websiteUrl: 'https://www.piracanjuba.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tirolez Queijos', websiteUrl: 'https://www.tirolez.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embaré Laticínios', websiteUrl: 'https://www.embare.com.br', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },

// ========== AUTOMOTIVE (30) ==========
  { name: 'Volkswagen Brasil Fábrica', websiteUrl: 'https://www.vw.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiat Chrysler Brasil', websiteUrl: 'https://www.fiat.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'General Motors Brasil Fábrica', websiteUrl: 'https://www.chevrolet.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ford Brasil Fábrica', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toyota Brasil Fábrica', websiteUrl: 'https://www.toyota.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honda Brasil Automóveis', websiteUrl: 'https://www.honda.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renault do Brasil Fábrica', websiteUrl: 'https://www.renault.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nissan do Brasil', websiteUrl: 'https://www.nissan.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jeep Brasil Fábrica', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Scania do Brasil', websiteUrl: 'https://www.scania.com/br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Volvo do Brasil', websiteUrl: 'https://www.volvo.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MAN Latin America Caminhões', websiteUrl: 'https://www.man-la.com', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iveco do Brasil', websiteUrl: 'https://www.iveco.com/brasil', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DAF Caminhões Brasil', websiteUrl: 'https://www.dfrraf.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agrale Tratores', websiteUrl: 'https://www.agrale.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Randon Implementos', websiteUrl: 'https://www.randon.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marcopolo Ônibus', websiteUrl: 'https://www.marcopolo.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caoa Montadora', websiteUrl: 'https://www.caoa.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BYD do Brasil', websiteUrl: 'https://www.bfryd.com/br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GWM Brasil Montadora', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Brasil Autopeças', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Continental Brasil Pneus', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bridgestone Brasil Pneus', websiteUrl: 'https://www.bridgestone.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pirelli Brasil Pneus', websiteUrl: 'https://www.pirelli.com/br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goodyear Brasil Pneus', websiteUrl: 'https://www.goodyear.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Michelin Brasil Pneus', websiteUrl: 'https://www.michelin.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dana Brasil Autopeças', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sabó Autopeças', websiteUrl: 'https://www.sabo.com.br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magneti Marelli Brasil Peças', websiteUrl: null, sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valeo do Brasil', websiteUrl: 'https://www.valeo.com/br', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },

// ========== TEXTILE (29) ==========
  { name: 'Malwee Moda', websiteUrl: 'https://www.malwee.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marisol Confecções', websiteUrl: 'https://www.marisol.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hering Indústria', websiteUrl: 'https://www.hering.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renner Indústria', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Riachuelo Confecções', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coteminas Tecidos', websiteUrl: 'https://www.coteminas.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Springs Global Têxtil', websiteUrl: 'https://www.springs.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Santanense Tecidos', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teka Industrial', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Döhler Têxtil', websiteUrl: 'https://www.dohler.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Karsten Têxtil', websiteUrl: 'https://www.karsten.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buettner Têxtil', websiteUrl: 'https://www.buettner.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cedro Têxtil Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vicunha Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alpargatas Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grendene Fábrica', websiteUrl: 'https://www.grendene.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arezzo Calçados Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beira Rio Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dakota Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piccadilly Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ramarim Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Usaflex Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'West Coast Calçados', websiteUrl: 'https://www.westcoast.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferracini Calçados', websiteUrl: 'https://www.ferracini.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Democrata Calçados', websiteUrl: 'https://www.democrata.com.br', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olympikus Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Penalty Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cambuci Esportes', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lupo Fábrica', websiteUrl: null, sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },

// ========== MINING_ENERGY (29) ==========
  { name: 'Vale Mineração', websiteUrl: 'https://www.vale.com', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Petrobras Energia', websiteUrl: 'https://www.petrobras.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samarco Mineração Ferro', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anglo American Brasil Mineração', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kinross Brasil Mineração', websiteUrl: 'https://www.kinross.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yamana Gold Brasil Mineração', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AngloGold Ashanti Brasil', websiteUrl: 'https://www.anglogoldashanti.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mineração Paragominas', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nexa Resources Mineração', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sigma Lithium Mineração', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eletrobras Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cemig Energia', websiteUrl: 'https://www.cemig.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CPFL Energia Geração', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Neoenergia Geração', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Equatorial Energia Distribuição', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Energisa Distribuição', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eneva Energia', websiteUrl: 'https://www.eneva.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie Brasil Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Raízen Energia', websiteUrl: 'https://www.raizen.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AES Brasil Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TotalEnergies Brasil Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shell Brasil Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BP Brasil Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Itaipu Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Furnas Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chesf Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eletronorte Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Omega Energia Renováveis', websiteUrl: 'https://www.omfrenegaenergia.com.br', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Casa dos Ventos Energia', websiteUrl: null, sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },

// ========== HEALTHCARE (29) ==========
  { name: 'Rede D\'Or São Luiz', websiteUrl: 'https://www.rfrededorsaoluiz.com.br', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hapvida Saúde', websiteUrl: 'https://www.hapvida.com.br', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NotreDame Intermédica Saúde', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unimed Saúde', websiteUrl: 'https://www.unimed.coop.br', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SulAmérica Saúde Planos', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amil Saúde Planos', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prevent Senior Hospitais', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kora Saúde Hospitais', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital Albert Einstein Equipe', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital Sírio Libanês Equipe', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dasa Diagnósticos', websiteUrl: 'https://www.dfrasa.com.br', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fleury Diagnósticos', websiteUrl: 'https://www.fleury.com.br', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hermes Pardini Diagnósticos', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sabin Diagnósticos', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurofarma Laboratório', websiteUrl: 'https://www.eurofarma.com.br', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aché Laboratório', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EMS Laboratório', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hypera Laboratório', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Biolab Laboratório', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cristália Laboratório', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Raia Drogasil Farmácias', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pague Menos Farmácias', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultrafarma Farmácias', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pacheco Farmácias', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Venâncio Farmácias', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indiana Farmácias', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pfizer Brasil Farmacêutica', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novartis Brasil Farmacêutica', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roche Brasil Farmacêutica', websiteUrl: null, sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },

// ========== HOSPITALITY_TOURISM (29) ==========
  { name: 'Ibis Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novotel Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pullman Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sofitel Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyatt Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wyndham Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nacional Inn Hotéis', websiteUrl: 'https://www.nacionalinn.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Slaviero Hotéis Rede', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Windsor Hotéis Rede', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deville Hotéis Rede', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transamerica Hotéis Rede', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bristol Hotéis Rede', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mabu Hotéis Rede', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Golden Tulip Brasil Hotéis', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CVC Corp Viagens', websiteUrl: 'https://www.cvc.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decolar Brasil Viagens', websiteUrl: 'https://www.decolar.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hurb Viagens', websiteUrl: 'https://www.hurb.com', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costa Cruzeiros Turismo', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSC Cruzeiros Turismo', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Royal Caribbean Brasil Turismo', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belmond Brasil Turismo', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copacabana Palace Turismo', websiteUrl: null, sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beach Park', websiteUrl: 'https://www.beachpark.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beto Carrero World', websiteUrl: 'https://www.betocarrero.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hot Beach Olímpia', websiteUrl: 'https://www.hotbeach.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thermas dos Laranjais', websiteUrl: 'https://www.thermasdeolimpia.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aviva Grupo Parques', websiteUrl: 'https://www.avfripa.com.br', sector: Sector.HOSPITALITY_TOURISM, sourceType: SourceType.COMPANY_CAREER },

// ========== AGRICULTURE (29) ==========
  { name: 'SLC Agrícola Fazendas', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BrasilAgro Fazendas', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amaggi Soja', websiteUrl: 'https://www.amaggi.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copersucar Açúcar', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'São Martinho Usina', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Raízen Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atvos Bioenergia', websiteUrl: 'https://www.atvos.com', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BP Bunge Bioenergia', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Citrosuco Suco', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cutrale Suco', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Louis Dreyfus Commodities BR', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cargill Brasil Grãos', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADM Brasil Grãos', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bunge Brasil Grãos', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coamo Cooperativa Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cocamar Cooperativa Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copacol Cooperativa Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'C.Vale Cooperativa', websiteUrl: 'https://www.cvale.com.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cooxupé Cooperativa Café', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lar Cooperativa', websiteUrl: 'https://www.lar.ind.br', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aurora Cooperativa Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Friboi JBS Pecuária', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marfrig Pecuária', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Minerva Pecuária', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BRF Avicultura', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seara Avicultura', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Syngenta Brasil Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corteva Brasil Agro', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yara Brasil Fertilizantes', websiteUrl: null, sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },

// ========== SECURITY_SERVICES (29) ==========
  { name: 'Prosegur Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Protege Serviços', websiteUrl: 'https://www.protfrege.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gocil Segurança', websiteUrl: 'https://www.gocil.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orsegups Segurança Patrimonial', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brinks Brasil Segurança', websiteUrl: 'https://www.brinks.com.br', sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pinkerton Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Secseg Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Segurpro Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beltis Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celta Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GPD Serviços Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Golden Shield Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Guardia Segurança Patrimonial', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IPV Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OmniSec Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sasp Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigilantes do Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intelbras Segurança Eletrônica', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hikvision Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dahua Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Security Brasil Serviços', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tyco Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Honeywell Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ICTS Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kroll Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Control Risks Brasil Segurança', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alarm Brasil', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Central Alarmes', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suprema Segurança Eletrônica', websiteUrl: null, sector: Sector.SECURITY_SERVICES, sourceType: SourceType.COMPANY_CAREER },

// ========== FACILITY_MANAGEMENT (29) ==========
  { name: 'Sodexo Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colliers Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savills Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Newmark Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Solve Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lume Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nortia Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viplex Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Infraservice Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bravo Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capital Clean Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belclean Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limpeza Total Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uniflex Brasil Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allied Serviços', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Almaviva Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atento Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Concentrix Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teleperformance Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tesis Brasil', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSA Brasil Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prime Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Servicemaster Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Liq Facilities', websiteUrl: null, sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },

// ========== METAL_STEEL (29) ==========
  { name: 'Gerdau Aços Longos', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CSN Aços Planos', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Usiminas Aços', websiteUrl: 'https://www.usiminas.com', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ArcelorMittal Brasil Aços', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aperam Brasil Aços', websiteUrl: 'https://www.aperam.com/southamerica', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Villares Metals Aços', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aço Cearense Siderurgia', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Votorantim Metais Siderurgia', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBA Alumínio', websiteUrl: 'https://www.cba.com.br', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alunorte Alumínio', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hydro Alumínio Brasil Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novelis Brasil Alumínio', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcoa Brasil Alumínio', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferbasa Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tupy Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mangels Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Confab Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenaris Brasil Tubos', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vallourec Brasil Tubos', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siderúrgica Barra Mansa Aço', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belgo Bekaert Arames Aço', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vega do Sul Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sumitomo Brasil Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JFE Steel Brasil Aço', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'POSCO Brasil Aço', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nippon Steel Brasil Aço', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Condor Metalúrgica Aço', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cinpal Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schulz Metais', websiteUrl: null, sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },

// ========== CHEMICALS_PLASTICS (29) ==========
  { name: 'Braskem Petroquímica', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oxiteno Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unigel Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elekeiroz Química Industrial', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhodia Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DuPont Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clariant Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evonik Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solvay Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanxess Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arkema Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covestro Brasil Química', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel Brasil Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Procter Gamble Brasil Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colgate Brasil Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unilever Brasil Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Natura Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'O Boticário Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coral Tintas Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suvinil Tintas', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sherwin-Williams Brasil Tintas', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'WEG Tintas Químicos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kraton Brasil Polímeros', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LyondellBasell Brasil Polímeros', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Momentive Brasil', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika Brasil', websiteUrl: 'https://www.sika.com.br', sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Politeno Plásticos', websiteUrl: null, sector: Sector.CHEMICALS_PLASTICS, sourceType: SourceType.COMPANY_CAREER },

// ========== ECOMMERCE_CARGO (29) ==========
  { name: 'Mercado Livre Envios', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amazon Brasil Fulfillment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shopee Brasil Fulfillment', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magazine Luiza Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Americanas Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Casas Bahia Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dafiti Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Netshoes Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zattini Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OLX Brasil Marketplace', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enjoei Marketplace', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuvemshop Marketplace', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olist Marketplace', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VTEX Plataforma', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Linx Commerce Plataforma', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tray Plataforma', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loja Integrada Plataforma', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loggi Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mandaê Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Melhor Envio Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frenet Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intelipost Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Correios E-commerce', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Azul Cargo Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jadlog Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Total Express Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sequoia Entregas', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'iFood Entregas Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rappi Entregas Logística', websiteUrl: null, sector: Sector.ECOMMERCE_CARGO, sourceType: SourceType.COMPANY_CAREER },

// ========== TELECOMMUNICATIONS (29) ==========
  { name: 'Vivo Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Claro Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TIM Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oi Telecom Rede', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Algar Telecom Rede', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brisanet Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Desktop Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sumicity Telecom Rede', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unifique Telecom', websiteUrl: 'https://www.unifique.com.br', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copel Telecom Rede', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sercomtel Rede', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZTE Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samsung Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Motorola Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cisco Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Qualcomm Brasil', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Positivo Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intelbras Telecom Rede', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sinch Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hughes Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starlink Brasil', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Embratel Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sky TV Brasil', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NET Brasil TV', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Virtua NET Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GVT Brasil Telecom', websiteUrl: null, sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
];

async function main() {
  const market = Market.BR;
  console.log(`Seeding ${ALL_ENTRIES.length} companies for BR market (part 3)...`);

  let count = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { websiteUrl: entry.websiteUrl ?? undefined, sector: entry.sector },
        create: {
          name: entry.name,
          slug,
          market,
          sector: entry.sector,
          websiteUrl: entry.websiteUrl,
          isActive: true,
        },
      });

      await prisma.crawlSource.upsert({
        where: { id: company.id },
        update: {},
        create: {
          id: company.id,
          companyId: company.id,
          name: `${entry.name} Vagas`,
          type: entry.sourceType as any,
          crawlMethod: CrawlMethod.HTML,
          seedUrls: [],
          schedule: '0 3 * * *',
          agingDays: 14,
          market,
          isActive: true,
        },
      });
      count++;
    } catch (e: any) {
      console.error(`  ✗ ${entry.name}: ${e.message}`);
    }
  }

  console.log(`\n✓ Seeded ${count}/${ALL_ENTRIES.length} companies for BR (part 3)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
