import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  sector: Sector;
  sourceType: SourceType;
  websiteUrl?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[áà]/g, 'a').replace(/[éè]/g, 'e').replace(/[íì]/g, 'i')
    .replace(/[óò]/g, 'o').replace(/[úù]/g, 'u').replace(/[ñ]/g, 'n')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const ALL_ENTRIES: CompanyEntry[] = [
  // ========== LOGISTICS_TRANSPORTATION (48) ==========
  { name: 'Correos', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MRW', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SEUR', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nacex', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renfe', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TMB Barcelona', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EMT Madrid', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alsa', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro de Madrid', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FGC Barcelona', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro Bilbao', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metrovalencia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro de Sevilla', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro de Málaga', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tussam Sevilla', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EMT Valencia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dbus San Sebastián', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avanza Grupo', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transdev España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DHL Express España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FedEx España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPS España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GLS Spain', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TNT España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sending', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tipsa', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Correos Express', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CTT Express España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Geodis España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuehne Nagel España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DSV España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DB Schenker España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'XPO Logistics España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CEVA Logistics España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhenus España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sesé Group', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Salvesen Logística', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palletways España', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primafrio', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Disfrimur', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transportes Azkar', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Carreras', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transportes Ochoa', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Alfil Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Autoridad Portuaria Barcelona', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Puerto de Valencia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Puerto de Algeciras', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baleària', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },

  // ========== MANUFACTURING (48) ==========
  { name: 'Gestamp', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIE Automotive', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondragón Corporación', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fagor Electrodomésticos', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CAF Construcciones', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Talgo', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Técnicas Reunidas', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubacex', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubos Reunidos', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ulma Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Irizar Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orbea', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Joma Sport', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fluidra', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roca Sanitario', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Simon Electric', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Antolín', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ficosa International', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zanini Auto Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Celsa', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gamesa Eólica', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Navantia', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Indra Sistemas', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aciturri Aeronáutica', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ITP Aero', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Airbus España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alstom España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stadler Rail Valencia', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens Mobility España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Thales España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schneider Electric España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ABB España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Balay', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BSH España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Electrolux España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Koxka Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fagor Industrial', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copreci', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danobat Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Batz Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Luzuriaga Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Faiveley España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vidrala', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ence Energía', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Europac Packaging', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Saica', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smurfit Kappa España', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },

  // ========== RETAIL (48) ==========
  { name: 'Mercadona', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'El Corte Inglés', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Día Supermercados', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lidl España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eroski', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Consum', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leroy Merlin España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carrefour España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldi España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcampo', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hipercor', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonpreu', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gadis', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alimerka', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BM Supermercados', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Condis', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caprabo', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ahorramas', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mas Supermercados', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covirán', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IKEA España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Media Markt España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fnac España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Worten España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decathlon España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sprinter Deporte', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forum Sport', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primor Perfumerías', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Druni', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sephora España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Douglas España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bricomart', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bricodepot España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AKI Bricolaje', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kiwoko', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tiendanimal', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Casa Viva', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maisons du Monde España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toys R Us España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kiabi España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primark España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Action España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tiger España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Normal España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cash Converter España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Game España', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Casa del Libro', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Natura Selection', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CONSTRUCTION (48) ==========
  { name: 'ACS Construcción', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferrovial Construcción', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciona Construcción', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FCC Construcción', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sacyr', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OHL Construcción', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dragados', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo San José', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lantania', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldesa Construcciones', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Copasa', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comsa Corporación', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Villar Mir', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sando Construcciones', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Ortiz', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CHM Infraestructuras', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rover Alcisa', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Puentes', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vías y Construcciones', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Assignia Infraestructuras', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cementos Portland Valderrivas', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cementos Molins', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LafargeHolcim España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cemex España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uralita', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porcelanosa', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roca Corporación', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cosentino', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pamesa Cerámica', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Keraben Grupo', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gres de Aragón', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Weber Saint-Gobain España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Knauf España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pladur', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Isover España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rockwool España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danosa', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Impermeabilizaciones Soprema ES', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prefabricados Delta', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Precon Prefabricados', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Puma', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parex Group España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilti España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Velux España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Technal España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cortizo', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schüco España', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },

  // ========== FOOD_BEVERAGE (48) ==========
  { name: 'Telepizza', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Vips', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McDonald\'s España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Burger King España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: '100 Montaditos', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KFC España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Domino\'s Pizza España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starbucks España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rodilla', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pans Company', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Goiko Grill', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lateral Restaurantes', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Restalia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Taco Bell España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Five Guys España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grosso Napoletano', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Popeyes España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tim Hortons España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Areas Restauración', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Autogrill España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Campofrío', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'El Pozo Alimentación', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Fuertes', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo AN Alimentación', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ebro Foods', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'García Carrión', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pescanova', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Calvo Conservas', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahou San Miguel', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Estrella Damm', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Estrella Galicia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coca-Cola Europacific ES', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danone España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nestlé España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondelez España', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unilever España Alimentos', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pascual', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Central Lechera Asturiana', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Lence', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gallina Blanca', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gallo Alimentación', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carbonell Aceites', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aceites Borges', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Osborne', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Torres Wines', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Freixenet', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Codorníu', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valor Chocolate', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },

  // ========== AUTOMOTIVE (48) ==========
  { name: 'SEAT Cupra', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ford Almussafes', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renault Valladolid', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iveco España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercedes-Benz Vitoria', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Volkswagen Navarra', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stellantis Vigo', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stellantis Zaragoza', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nissan Barcelona', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toyota España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Antolín Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ficosa Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gestamp Automoción', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIE Automotive Parts', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zanini Auto Grup', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maier Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondragón Automoción', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Continental España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bridgestone Burgos', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Michelin España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Automotive España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valeo España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZF España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Faurecia España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magna España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lear Corporation España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Denso España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Benteler España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Plastic Omnium España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Martinrea España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Batz Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teknia Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SMP Automotive España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hutchinson España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magna Seating España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tower Automotive España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delphi España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aptiv España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dana España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BorgWarner España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mahle España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Schaeffler España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SKF España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NSK España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NTN-SNR España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Webasto España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huf España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adient España', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TEXTILE (48) ==========
  { name: 'Inditex Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mango Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Desigual', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tendam Cortefiel', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Mayoral', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pronovias', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tous Joyería', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camper Calzado', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pikolinos', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Panama Jack', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loewe Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Balenciaga Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adolfo Domínguez', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pepe Jeans España', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Textil Inditex Logística', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zara Logistics', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Massimo Dutti Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pull Bear Logística', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bershka Logística', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stradivarius Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Oysho Logística', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Women\'secret Producción', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Springfield', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pedro del Hierro', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Punto Roma', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inside Moda', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trucco Moda', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bimba y Lola', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Scalpers', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'El Ganso', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Silbon', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Textil Santanderina', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tavex Tejidos', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tejidos Royo', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gratacós Tejidos', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilaturas Ferre', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Textil Olius', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Antex Textil', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jeanología', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kelme Sport', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Munich Sports', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'J\'Hayber', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Callaghan Zapatos', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fluchos', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Martinelli Calzados', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hispanitas', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unisa Calzados', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pablosky', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },

  // ========== MINING_ENERGY (48) ==========
  { name: 'Repsol', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Endesa', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iberdrola', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Naturgy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cepsa', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Red Eléctrica', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enagás', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciona Energía', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solaria Energía', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Audax Renovables', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Greenalia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Opdenergy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capital Energy', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Naturgy Renovables', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iberdrola Renovables', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Endesa X', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens Gamesa España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vestas España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nordex España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EDP España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TotalEnergies España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BP España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shell España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Galp España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Repsol Química', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CLH Logística Hidrocarburos', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Redexis Gas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Madrileña Red de Gas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nortegas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gas Natural Distribución', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iberdrola Distribución', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'E-Distribución Endesa', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UFD Unión Fenosa', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viesgo', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EiDF Solar', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Soltec Power', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grenergy Renovables', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cox Energy España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enerfín', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Villar Mir Energía', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forestalia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Jorge Energía', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axpo Iberia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Statkraft España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ørsted España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enel Green Power España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RWE Renewables España', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },

  // ========== HEALTHCARE (48) ==========
  { name: 'Quirónsalud', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HM Hospitales', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vithas', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ribera Salud', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Hospiten', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sanitas Hospitales', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viamed Salud', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital San Juan de Dios', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clínica Universidad de Navarra', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fundación Jiménez Díaz', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital Vall d\'Hebron', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital Clínic Barcelona', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital La Paz', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital 12 de Octubre', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital Gregorio Marañón', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospital Ramón y Cajal', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Recoletas', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Policlínica', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo IMED Hospitales', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clínica Baviera', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vitaldent', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Asisa', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adeslas', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cruz Roja Española', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DomusVi España', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orpea España', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ballesol Residencias', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Albertia', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clece Salud', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Eulen Salud', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grifols', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Almirall', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Esteve Farmacéutica', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferrer Internacional', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rovi Farmacéutica', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PharmaMar', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Faes Farma', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cinfa Laboratorios', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kern Pharma', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Normon Laboratorios', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synlab España', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Megalab', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unilabs España', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reference Laboratory', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ambulancias Tenorio', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ambuvital', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transalud Ambulancias', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'HTG Molecular Diagnostics ES', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },

  // ========== HOSPITALITY (48) ==========
  { name: 'Meliá Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NH Hotel Group', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barceló Hotel Group', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RIU Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iberostar Group', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paradores', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurostars Hotel Company', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palladium Hotel Group', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vincci Hoteles', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sercotel Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Catalonia Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'H10 Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hotusa Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Princess Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Globalia Turismo', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lopesan Hotel Group', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Playa Senator Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Piñero', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hesperia Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Room Mate Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Only YOU Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Accor España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IHG España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyatt España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Four Seasons España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mandarin Oriental España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kempinski España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hospes Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Petit Palace Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Playasol Ibiza Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Spring Hotels Tenerife', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hotel Fuerteventura Palace', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SBH Hotels Canarias', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gloria Hotels Gran Canaria', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Club Med España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transhotel', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Halcón Viajes', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Viajes El Corte Inglés', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Logitravel', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ávoris Corporación', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pullmantur Cruceros', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baleària Ferries', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trasmediterránea', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fred Olsen España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camping Yelloh Village ES', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Campings Sandaya España', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },

  // ========== AGRICULTURE (48) ==========
  { name: 'ElPozo Alimentación', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Fuertes Agro', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo AN', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ebro Foods Producción', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'García Carrión Producción', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Dcoop', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Hojiblanca', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aceites del Sur Coosur', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo SOS Aceite', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coren', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Leche Pascual', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covap', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Entrepinares', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lactalis España', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Capsa Food', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Incarlopsa', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Jorge', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costa Food Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grup Alimentari Guissona', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BonÀrea', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nufri Frutas', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Anecoop', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Caparrós', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Paloma', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Primaflor', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Verdimed', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unica Group', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Cosentino Agro', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAT Gruventa', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Agroponiente', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMC Natural Drinks', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Congelados de Navarra', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ultracongelados Virto', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Findus España', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Feiraco', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jealsa Rianxeira', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conservas Garavilla', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Calvo Pesca', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nueva Pescanova', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Profand', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Importaco', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Siro', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gullón Galletas', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Dulcesol', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Panrico', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bimbo España', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Europastry', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berlys Alimentación', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },

  // ========== SECURITY (48) ==========
  { name: 'Prosegur', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Securitas España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ilunion Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Control Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Segur Ibérica', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Securitas Direct España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur Cash', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur Alarmas', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loomis España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CSS Vigilancia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gunnebo España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'G4S España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinsa Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Protección y Custodia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ombuds Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seguridad Integral Canaria', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trablisa Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eulen Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marsegur', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sur Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Segurisa', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigilant Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Austral Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magasegur', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Servicios Integrales Levante', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Serviseg España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur Servicios Empresariales', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tyco España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADT España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Movistar Prosegur Alarmas', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ariete Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seguriber', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sevitren Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dallmeier España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcatraz Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nordés Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Efitec Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sabico Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monelec Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ICTS España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compañía Seguridad Aérea', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Norte Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Castellana Seguridad', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garda World España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Allied Universal España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johnson Controls España Seg', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siemens Seguridad España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Seguridad España', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },

  // ========== FACILITY_MANAGEMENT (48) ==========
  { name: 'Clece', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eulen', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferrovial Servicios', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodexo España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aramark España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ilunion Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciona Facility Services', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Quirón Limpieza', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sacyr Facilities', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FCC Medio Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Urbaser', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cespa Medio Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valoriza Medio Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferrovial Medio Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Norte Servicios', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Lar Servicios', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Samsic España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limpiezas Abrillantado', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limasa Málaga', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emaya Palma', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Madrid Destino Limpieza', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barcelona Serveis Municipals', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lipasam Sevilla', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emulsa Gijón', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cogersa Asturias', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tirme Mallorca', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ecoembes Reciclaje', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ecovidrio', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Serunion Restauración', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mediterránea Catering', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Albie Servicios', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldesa Servicios', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brillosa Limpieza', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adecco Outsourcing España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Randstad Facility España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manpower Servicios España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gi Group España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tempo Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cofely España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Johnson Controls Facility ES', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CBRE España Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'JLL España Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cushman Wakefield España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savills España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Suez España Medio Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veolia España', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== METAL_STEEL (48) ==========
  { name: 'ArcelorMittal España', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acerinox', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Celsa Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sidenor', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubacex Acero', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubos Reunidos Acero', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Gallardo Balboa', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corrugados Azpeitia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Megasa Siderúrgica', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Global Steel Wire', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siderúrgica Sevillana', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nervacero', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acería de Álava', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fundiciones del Estanda', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fundición Dúctil Benito', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fundiciones de Roda', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcoa España', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hydro Aluminium España', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alucoil', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Exlabesa Extrusión', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perfiles de Aluminio', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atlantic Copper', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Farga Lacambra', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Outokumpu España', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roldán Aceros Inoxidables', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Abengoa Metal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tallers Alzina', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forjas de Iraeta', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIE Galfor', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forjas Ariznabarreta', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Matrici', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Batz Troquelería', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Estampaciones Mayo', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metaldyne España', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Befesa Reciclaje', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lointek', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Urssa Estructuras', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Calderería López Hermanos', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Talleres Zigor', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bellota Herramientas', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Irizar Forge', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Egaña Metal', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ecenarro Fundición', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fagor Ederlan', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fundiciones de Usurbil', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Precicast Bilbao', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ITP Forja Aerostar', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metalúrgica Cerrajera', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CHEMICALS (48) ==========
  { name: 'Repsol Química Producción', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ercros', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fertiberia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Seda Barcelona', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Chemical Ibérica', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayer España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solvay España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Covestro España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Clariant España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika España Química', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Crespo', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Procter Gamble España Prod', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unilever España Prod', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colgate Palmolive España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SC Johnson España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reckitt España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Linde Gas España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Air Liquide España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Messer Ibérica', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nippon Gases España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cepsa Química', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sabic España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'LyondellBasell España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanxess España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evonik España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Givaudan España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IFF España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Firmenich España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Puig Producción', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Antonio Puig Fragancias', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Laboratorios Maverick', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Persan Detergentes', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pinturas Titan', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pinturas Isaval', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valentine Pinturas', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jotun España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AkzoNobel España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PPG España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sherwin Williams España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Almacenes Generales España', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Quimiplas', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aiscondel', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Derivados del Flúor', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maxam Explosivos', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo Celulosa', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Torrecid', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },

  // ========== ECOMMERCE_WAREHOUSE (48) ==========
  { name: 'Amazon España Logística', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PcComponentes', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Privalia España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wallapop Logística', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Miravia España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AliExpress Plaza España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'eBay España Operations', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zalando España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Shein España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Temu España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'El Corte Inglés Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercadona Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carrefour Online España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dia Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ulabox', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Glovo España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deliveroo España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Just Eat España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uber Eats España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stuart Delivery España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NACEX E-commerce', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SEUR E-commerce', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MRW E-commerce', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Correos E-commerce', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Paack Delivery', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ontime Logistics España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ID Logistics España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Logista España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MediaMarkt Online España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decathlon Online España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leroy Merlin Online España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IKEA Online España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zara Online Logística', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mango Online Logística', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sprinter Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PromoFarma', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mifarma', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dosfarma', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zooplus España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kiwoko Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ManoMano España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vinted España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Back Market España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Refurbed España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CashConverters Online ES', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Worten Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fnac Online España', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Casa del Libro Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TELECOMMUNICATIONS (48) ==========
  { name: 'Telefónica', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orange España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vodafone España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MásMóvil', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Digi España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yoigo', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pepephone', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lowi', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'O2 España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Simyo', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Jazztel', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lycamobile España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Finetwork', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euskaltel', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'R Cable Galicia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telecable Asturias', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adamo Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avatel Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MasOrange', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cellnex España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telxius Torres España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'American Tower España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZTE España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teldat', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dominion Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ezentis', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elecnor Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amper', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kapsch España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Televes', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ikusi', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Digicel España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adam Telecom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aruba España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OVHcloud España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Equinix España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Interxion España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Data4 España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nabiax Data Centers', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acens Telefónica', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stackscale', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gigas Hosting', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arsys', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colt Technology España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BT España', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },

  // ========== OTHER (44) ==========
  { name: 'AENA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agbar Aguas', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Canal de Isabel II', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Renfe Mantenimiento', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADIF', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ADIF Alta Velocidad', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Puertos del Estado', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enaire', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aeropuerto de Barcelona', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aeropuerto de Palma', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iberia Handling', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Swissport España', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Groundforce España', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciona Agua', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aqualia', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sacyr Agua', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aigües de Barcelona', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'EMASESA Sevilla', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Emivasa Valencia', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RTVE', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atresmedia Producción', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mediaset España', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Movistar Plus Producción', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grupo PRISA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vocento', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loterías y Apuestas Estado', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ONCE', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Codere España', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Correos Gestión', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TRAGSA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TRAGSATEC', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Navantia Reparaciones', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trasmediterránea Naviera', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baleària Naviera', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Armas Trasmediterránea', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fred Olsen Express', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Protección Civil España', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bomberos Comunidad Madrid', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bomberos Barcelona', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Policía Local Madrid', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Guardia Urbana Barcelona', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro Ligero Madrid', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cercanías Renfe', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AVE Renfe Mantenimiento', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
];

async function main() {
  const market = Market.ES;
  console.log(`Seeding ${ALL_ENTRIES.length} additional companies for ES market (part 2)...`);
  let created = 0, existed = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { sector: entry.sector },
        create: { name: entry.name, slug, market, sector: entry.sector, websiteUrl: null, isActive: true },
      });
      const src = await prisma.crawlSource.findFirst({ where: { companyId: company.id } });
      if (!src) {
        await prisma.crawlSource.create({
          data: {
            companyId: company.id,
            name: `${entry.name} Empleo`,
            type: entry.sourceType as any,
            crawlMethod: CrawlMethod.HTML,
            seedUrls: [],
            schedule: '0 3 * * *',
            agingDays: 14,
            market,
            isActive: true,
          },
        });
        created++;
      } else { existed++; }
    } catch (e: any) {
      if (e.code === 'P2002') { existed++; } else { console.error(`Error: ${entry.name}:`, e.message); }
    }
  }
  console.log(`\nDone! Created: ${created}, Already existed: ${existed}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
