import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  sector: Sector;
  sourceType: SourceType;
  websiteUrl?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[àáâ]/g, 'a').replace(/[èéê]/g, 'e').replace(/[ìíî]/g, 'i')
    .replace(/[òóô]/g, 'o').replace(/[ùúû]/g, 'u')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const ALL_ENTRIES: CompanyEntry[] = [
  // ========== LOGISTICS_TRANSPORTATION (48) ==========
  { name: 'Poste Italiane', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BRT Corriere Espresso', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GLS Italy', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SDA Express Courier', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TNT Italy', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trenitalia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italo NTV', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ATM Milano', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ATAC Roma', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GTT Torino', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ANM Napoli', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tper Bologna', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ACTV Venezia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Busitalia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arriva Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fercam Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arcese Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savino Del Bene', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Torello Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palletways Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Number 1 Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'XPO Logistics Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DHL Express Italy', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FedEx Italy', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UPS Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bartolini Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Geodis Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuehne Nagel Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DSV Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rhenus Logistics Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gruber Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Autamarocchi', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smet Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lannutti Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maganetti Spedizioni', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ceva Logistics Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DB Schenker Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiege Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Codognotto Trasporti', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Transmec Group', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CTL Livorno', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Contship Italia', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terminal Container Ravenna', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PSA Genova', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mercitalia Logistics', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trenord', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cotral Lazio', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMT Genova', sector: Sector.LOGISTICS_TRANSPORTATION, sourceType: SourceType.COMPANY_CAREER },

  // ========== MANUFACTURING (48) ==========
  { name: 'Leonardo SpA', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fincantieri', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pirelli', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brembo', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Luxottica', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'De Longhi', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Candy Hoover', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ariston Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Whirlpool Italia', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Electrolux Italia', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Smeg', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elica SpA', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saeco International', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cimbali Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuova Simonelli', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beretta Armi', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Benelli Armi', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prysmian Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Datalogic', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comau Robotics', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danieli Officine Meccaniche', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IMA Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sacmi Imola', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coesia Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SCM Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Biesse Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carel Industries', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Interpump Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trevi Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Permasteelisa', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Techint Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ansaldo Energia', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuovo Pignone', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonfiglioli Riduttori', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carraro Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marposs SpA', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pedrollo Pompe', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comer Industries', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Itema Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Salvagnini', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prima Industrie', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maccaferri Group', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rold Electronics', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fantini Cosmi', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saer Elettropompe', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savio Macchine Tessili', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gildemeister Italiana', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mecc Alte Generatori', sector: Sector.MANUFACTURING, sourceType: SourceType.COMPANY_CAREER },

  // ========== RETAIL (48) ==========
  { name: 'Esselunga', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conad', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coop Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurospin', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lidl Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MD Discount', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Penny Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aldi Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carrefour Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pam Panorama', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Despar Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sigma Supermercati', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bennet Supermercati', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iper La Grande i', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tigre Supermercati', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Todis', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crai Supermercati', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dico Supermercati', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leroy Merlin Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brico Io', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OBI Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IKEA Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mediaworld', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unieuro', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Expert Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trony', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decathlon Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cisalfa Sport', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acqua e Sapone', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tigotà', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Douglas Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sephora Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Feltrinelli', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondadori Store', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gamestop Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maxi Zoo Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arcaplanet', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'NaturaSì', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eataly', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Flying Tiger Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kasanova', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Risparmio Casa', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bricocenter', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bricoman Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conforama Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maisons du Monde Italia', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pittarello', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Scarpe e Scarpe', sector: Sector.RETAIL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CONSTRUCTION (48) ==========
  { name: 'Webuild', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Astaldi', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CMC Ravenna', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pizzarotti', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Condotte SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ghella SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Itinera SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rizzani de Eccher', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vianini Lavori', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toto Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Strabag Italia', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maltauro', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ICM SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carron Cav Angelo', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Collini Lavori', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cimolai SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costruzioni Dondi', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pavimental', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Technital', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonatti SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saipem Onshore', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maire Tecnimont', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trevi Fondazioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Soilmec', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mapei Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buzzi Unicem', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italcementi', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cementir Holding', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Calcestruzzi SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colacem', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Borio Mangiarotti', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pessina Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ediliziacrobatica', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cogeis SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SELI Overseas', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Impresa Pizzarotti', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cooperative Muratori Reggiolo', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manelli Group', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'D\'Agostino Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lombardi Ingegneria', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Net Engineering', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ativa Engineering', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fagioli SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SIC Società Italiana Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tecnis SpA', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ferretti International', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garboli Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cossi Costruzioni', sector: Sector.CONSTRUCTION, sourceType: SourceType.COMPANY_CAREER },

  // ========== FOOD_BEVERAGE (48) ==========
  { name: 'Ferrero', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Barilla', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lavazza', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Illy Caffè', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Autogrill', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'McDonald\'s Italia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cremonini Group', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Burger King Italia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KFC Italia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Domino\'s Pizza Italia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starbucks Italia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pret A Manger Italia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alice Pizza', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rossopomodoro', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Panino Giusto', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Piadineria', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Old Wild West', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roadhouse Restaurant', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cigierre Group', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gruppo Campari', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Perfetti Van Melle', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'De Cecco', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Divella', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mutti SpA', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cirio', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Star Alimentare', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rummo Pasta', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garofalo Pasta', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'San Benedetto', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sanpellegrino', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lurisia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Peroni Birra', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Birra Moretti', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ichnusa Birra', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fabbri 1905', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rigoni di Asiago', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loacker', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bauli', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Motta Alimentare', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Galbusera', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colussi Group', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Delverde Pasta', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Buitoni', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Giovanni Rana', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sarni Ristorazione', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MyChef Ristorazione', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chef Express', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dispensa Emilia', sector: Sector.FOOD_BEVERAGE, sourceType: SourceType.COMPANY_CAREER },

  // ========== AUTOMOTIVE (48) ==========
  { name: 'Ferrari', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lamborghini', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maserati', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ducati Motor', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Piaggio Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Magneti Marelli', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CNH Industrial', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stellantis Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iveco Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dallara Automobili', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pagani Automobili', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alfa Romeo Produzione', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiat Professional', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lancia Produzione', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aprilia Racing', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Moto Guzzi', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vespa Piaggio', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brembo Freni', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marelli Motorsport', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sogefi Filtrazione', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiamm', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Landi Renzo', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pininfarina', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Giugiaro Design', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Avio Aero', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Freni Brembo Aftermarket', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UFI Filters', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marangoni Pneumatici', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adler Pelzer Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CLN Group', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Streparava SpA', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aetna Group Auto', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OZ Racing Wheels', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ognibene Power', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Industrie Saleri Italo', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olsa Illuminazione', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dell\'Orto Carburatori', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euroricambi', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bosch Italia Automotive', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Continental Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZF Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valeo Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Webasto Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Denso Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Toyota Material Handling Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hyundai Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Volvo Trucks Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Scania Italia', sector: Sector.AUTOMOTIVE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TEXTILE (48) ==========
  { name: 'Benetton Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Calzedonia Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Max Mara', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ermenegildo Zegna', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prada Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Moncler Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brunello Cucinelli', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loro Piana', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valentino Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Salvatore Ferragamo', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tod\'s Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gucci Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bottega Veneta Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Armani Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Versace Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dolce Gabbana Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Diesel Produzione', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'OVS SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teddy Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Miroglio Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Golden Goose', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stone Island', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Herno', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Canali', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corneliani', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kiton', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brioni', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zegna Baruffa Lane', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reda SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Albini Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Limonta SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marzotto Group', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Canepa SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ratti SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mantero Seta', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Botto Giuseppe Filati', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fulgar SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eurojersey', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Candiani Denim', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tessitura Monti', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vitale Barberis Canonico', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tintoria di Quaregna', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanificio Cerruti', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lanificio Fratelli Piacenza', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carvico SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Millefili SpA', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Maglificio Maggia', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Filatura di Pollone', sector: Sector.TEXTILE, sourceType: SourceType.COMPANY_CAREER },

  // ========== MINING_ENERGY (48) ==========
  { name: 'Eni', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enel', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Edison', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Snam', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terna', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'A2A', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hera Group', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iren SpA', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acea', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enel Green Power', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ERG SpA', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Falck Renewables', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sorgenia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Illumia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axpo Italia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alperia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dolomiti Energia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CVA Energia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Agsm AIM', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Engie Italia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TotalEnergies Italia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saras Raffineria', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'API Raffineria', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Esso Italiana', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kuwait Petroleum Italia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tamoil Italia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IP Gruppo Api', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Saipem', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italgas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eni Plenitude', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enel X', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'E-Distribuzione', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gridspertise', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enel Produzione', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ansaldo Nucleare', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sogin', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSE Gestore Servizi', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acquirente Unico', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gestore Mercati Energetici', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RSE Ricerca Sistema Energetico', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ENEA Energia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terna Plus', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Snam Rete Gas', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stogit', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GNL Italia', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adriatic LNG', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Enipower', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Versalis Raffinazione', sector: Sector.MINING_ENERGY, sourceType: SourceType.COMPANY_CAREER },

  // ========== HEALTHCARE (48) ==========
  { name: 'Humanitas', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'San Raffaele', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Policlinico Gemelli', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KOS Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GVM Care Research', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gruppo San Donato', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Istituto Clinico Humanitas', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Auxologico', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MultiMedica', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Casa di Cura San Pio X', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ospedali Privati Forlì', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Korian Italia', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orpea Italia', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sereni Orizzonti', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Giomi Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Villa Maria Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Garofalo Health Care', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synlab Italia', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cerba HealthCare Italia', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lifebrain Laboratori', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Centro Diagnostico Italiano', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Menarini Diagnostics', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chiesi Farmaceutici', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Recordati', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Angelini Pharma', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zambon Group', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bracco Imaging', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dompé Farmaceutici', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italfarmaco', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mediolanum Farmaceutici', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alfasigma', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Abiogen Pharma', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fondazione Don Gnocchi', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lega del Filo d\'Oro', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fondazione Maugeri', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Istituti Clinici Zucchi', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Policlinico di Milano', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Azienda Ospedaliera Padova', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ospedale Niguarda', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Istituto Nazionale Tumori', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bambino Gesù Ospedale', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meyer Ospedale Pediatrico', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gaslini Ospedale', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Croce Rossa Italiana', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ANPAS Ambulanze', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Misericordie Ambulanze', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cooperativa OSA', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elsan Italia', sector: Sector.HEALTHCARE, sourceType: SourceType.COMPANY_CAREER },

  // ========== HOSPITALITY (48) ==========
  { name: 'NH Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Starhotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alpitour World', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Costa Crociere', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MSC Crociere', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boscolo Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Baglioni Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sina Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Atahotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'UNA Group Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Best Western Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hilton Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Marriott Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Accor Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IHG Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Meliá Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Blu Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Club Med Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veratour', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eden Viaggi', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'I Grandi Viaggi', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nicolaus Tour', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Futura Vacanze', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Settemari Club', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Human Company Camping', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hu Openair Camping', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Village Camping Jonio', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'TH Resorts', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valtur', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'VOI Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arbatax Park Resort', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forte Village Resort', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lefay Resorts', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rosewood Castiglion del Bosco', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Belmond Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Four Seasons Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mandarin Oriental Milano', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Park Hyatt Milano', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palazzo Versace Dubai ops Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bulgari Hotel Milano', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rocco Forte Hotels Italia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lungarno Collection', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Planetaria Hotels', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Borgo Egnazia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Masseria San Domenico', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grotta Giusti Resort', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Terme di Saturnia', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'QC Terme', sector: Sector.HOSPITALITY, sourceType: SourceType.COMPANY_CAREER },

  // ========== AGRICULTURE (48) ==========
  { name: 'Parmalat', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Amadori', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Granarolo', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conserve Italia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mutti Pomodoro', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Latteria Soresina', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grana Padano Consorzio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Parmigiano Reggiano Consorzio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Galbani', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zanetti Formaggi', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Auricchio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mila Latteria', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sterilgarda Alimenti', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosciutto di Parma Consorzio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'San Daniele Consorzio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rovagnati', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Beretta Salumi', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Citterio Salumi', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fiorucci Salumi', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aia Veronesi', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fileni Alimentare', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bolton Alimentari', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nostromo Tonno', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rio Mare', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Callipo Tonno', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orogel Surgelati', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bonduelle Italia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Findus Italia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Surgital', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fruttagel', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zuegg', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yoga Conserve', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monini Olio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carapelli Olio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Farchioni Olio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'De Rica Pomodoro', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Doria', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pastificio Rana', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Riso Scotti', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Riso Gallo', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grandi Riso', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mielizia Apicoltura', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Consorzio Melinda', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Consorzio VOG', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Apofruit Italia', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mazzoni Group Frutta', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Orsero SpA', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Almaverde Bio', sector: Sector.AGRICULTURE, sourceType: SourceType.COMPANY_CAREER },

  // ========== SECURITY (48) ==========
  { name: 'Securitalia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IVRI Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metronotte Italia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Civis SpA', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sicuritalia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Axitea SpA', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigilanza Group', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KSM Security', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cosmopol Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Battistolli Servizi', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondialpol', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coopservice Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italpol Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Vigile Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rangers Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'All System Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GPG Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fidelitas Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'New Security Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Body Guard Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Securitas Italia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'G4S Italia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Prosegur Italia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Loomis Italia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CSM Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'La Patria Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vedetta 2 Mondialpol', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'International Security Service', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euro Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigile Giurata Servizi', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Istituto Vigilanza Argo', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigilantes Group', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Servizi Fiduciari Milano', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corpo Vigili Giurati', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Security Service Italia', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nuova Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SOS Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Istituto Vigilanza Notturna', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alfa Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sorveglianza Italiana', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gruppo Investigativo Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roma Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Napoli Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Torino Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Firenze Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bologna Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Genova Sicurezza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Palermo Vigilanza', sector: Sector.SECURITY, sourceType: SourceType.COMPANY_CAREER },

  // ========== FACILITY_MANAGEMENT (48) ==========
  { name: 'Manutencoop Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CNS Consorzio', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dussmann Service Italia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sodexo Italia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ISS Italia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Compass Group Italia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Elior Ristorazione', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Camst Ristorazione', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIR Food', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Markas Srl', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rekeep', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coopservice', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Formula Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pellegrini SpA', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gemeaz Elior', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Serenissima Ristorazione', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vivenda SpA', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ladisa Ristorazione', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CIRFOOD Impresa Sociale', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SIR Servizi Integrati', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GSA Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Team Service', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Roma Multiservizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMA Roma', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMSA Milano', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ASIA Napoli', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Veritas Venezia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMIU Genova', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Hera Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'A2A Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iren Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Contarina SpA', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eco-Ricicli Veritas', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sei Toscana', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alia Servizi Ambientali', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ACSM-AGAM', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Savno Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mantova Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gelsia Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GAIA SpA Ambiente', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SCS Gestioni', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Idealservice', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manpower Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Randstad Facility', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gi Group Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Adecco Facility Italia', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Synergie Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Umana Servizi', sector: Sector.FACILITY_MANAGEMENT, sourceType: SourceType.COMPANY_CAREER },

  // ========== METAL_STEEL (48) ==========
  { name: 'Marcegaglia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Arvedi Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Danieli Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tenaris Dalmine', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Feralpi Group', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciaierie d\'Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ori Martin', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alfa Acciai', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Riva Acciaio', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pittini Acciai', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciaieria Arvedi', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cogne Acciai Speciali', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciaierie Venete', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Duferco Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fonderie di Montorso', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fonderie Cooperative', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Teksid Fonderie', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fonderie Mario Mazzucconi', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fondital SpA', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'KME Italy', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Profilati Alluminio', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metra Alluminio', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aluberg', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novelis Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Alcoa Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metinvest Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Silcotub Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tubificio di Terni', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dalmine SpA', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ilva Laminati Piani', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciaierie di Calvisano', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stefana SpA', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciaierie di Sicilia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IRE Omba Fonderie', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fonderie Zanardi', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italtractor ITM', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Berco SpA', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Officine Meccaniche Rezzatesi', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forgiatura Mamè', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Forge Monchieri', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zoppelletto SpA', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metalcastello', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Silgan Metal Packaging', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Crown Holdings Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ball Packaging Italia', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siderurgica Latina', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acciaierie Valbruna', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Rodacciai SpA', sector: Sector.METAL_STEEL, sourceType: SourceType.COMPANY_CAREER },

  // ========== CHEMICALS (48) ==========
  { name: 'Mapei', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Versalis', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Radici Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SOL Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bracco Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lamberti SpA', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Polynt Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Novamont', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aquafil SpA', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mossi Ghisolfi', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Polimeri Europa', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SIAD SpA', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sapio Industrie', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Esseco Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Italmatch Chemicals', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Endurance Mitsui Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colorobbia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sasol Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BASF Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Henkel Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Solvay Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Evonik Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dow Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Bayer Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sika Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Kerakoll', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cromology Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'San Marco Vernici', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Boero Bartolomeo', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IVM Chemicals', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gruppo Saviola', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fantoni SpA', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Frati Luigi SpA', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gruppo Mauro Saviola', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sadepan Chimica', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Norda SpA', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zobele Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ICR Industrie Cosmetiche', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Intercos Group', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Chromavis', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ancorotti Cosmetics', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mane Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Givaudan Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Firmenich Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IFF Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Procter Gamble Italia Prod', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unilever Italia Prod', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colgate Palmolive Italia', sector: Sector.CHEMICALS, sourceType: SourceType.COMPANY_CAREER },

  // ========== ECOMMERCE_WAREHOUSE (48) ==========
  { name: 'Amazon Italia Logistica', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Zalando Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Yoox Net-a-Porter', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unieuro Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ePrice', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Privalia Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vente-privee Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Subito.it Logistica', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Farfetch Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'eBay Italia Operations', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Poste Italiane E-commerce', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SDA E-commerce Delivery', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GLS E-commerce Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BRT E-commerce', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Milkman Last Mile', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Glovo Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Deliveroo Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Just Eat Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Uber Eats Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Getir Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Gorillas Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Everli Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cortilia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tannico Wine', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vino.com', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Esselunga Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Conad Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Carrefour Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Coop Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'IBS.it Libreria', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Libraccio Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Feltrinelli Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mondadori Store Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Manomano Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Leroy Merlin Online IT', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Decathlon Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Pittarosso Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cisalfa Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Douglas Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sephora Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Notino Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Farmacia Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Dr Max Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mediaworld Online', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Euronics Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Expert Online Italia', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Monclick', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Trovaprezzi Fulfillment', sector: Sector.ECOMMERCE_WAREHOUSE, sourceType: SourceType.COMPANY_CAREER },

  // ========== TELECOMMUNICATIONS (48) ==========
  { name: 'TIM', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vodafone Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Wind Tre', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Fastweb', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Open Fiber', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Iliad Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'PosteMobile', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tiscali', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Linkem', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Eolo SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FiberCop', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Infratel Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Inwit', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cellnex Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ericsson Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Nokia Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Huawei Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ZTE Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sirti SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sielte SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Site SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Valtellina SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Ceit Impianti', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Comitel Telecomunicazioni', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telebit Group', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Retelit', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Irideos', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Brennercom', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Unidata SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CDLAN', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mix Milano', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aruba SpA', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Register.it', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Seeweb', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Naquadria', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Supernap Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Equinix Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Data4 Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Stack Infrastructure Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Telxius Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Colt Technology Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'BT Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lumen Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sparkle TIM', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Noovle TIM', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Olivetti', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Reply Telco', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Accenture Telco Italia', sector: Sector.TELECOMMUNICATIONS, sourceType: SourceType.COMPANY_CAREER },

  // ========== OTHER (47) ==========
  { name: 'Autostrade per l\'Italia', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'FS Italiane', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RFI Rete Ferroviaria', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ANAS SpA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ENAV', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Aeroporti di Roma', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SEA Aeroporti Milano', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAVE Aeroporto Venezia', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SACBO Bergamo Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GESAC Napoli Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SAC Catania Airport', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Autorità Portuale Genova', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porto di Trieste', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porto di Ravenna', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porto di Livorno', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Porto di Napoli', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Tirrenia Navigazione', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Grimaldi Lines', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'GNV Grandi Navi Veloci', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Moby Lines', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Corsica Sardinia Ferries', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Caronte Tourist', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Siremar', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMAT Palermo', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CTM Cagliari', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMTAB Bari', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Azienda Napoletana Mobilità', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Circumvesuviana', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metro Napoli', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Metropolitana Milanese', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'MM SpA', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'CAP Holding Acqua', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Acquedotto Pugliese', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'AMAP Palermo Acqua', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'SMAT Torino', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Publiacqua Firenze', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'ACOSET Catania', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Vigili del Fuoco Volontari', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Protezione Civile', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Polizia Municipale Milano', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'RAI Radiotelevisione', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Mediaset Produzione', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sky Italia Operazioni', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'DAZN Italia', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Cinecittà Studios', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Lottomatica', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
  { name: 'Sisal', sector: Sector.OTHER, sourceType: SourceType.COMPANY_CAREER },
];

async function main() {
  const market = Market.IT;
  console.log(`Seeding ${ALL_ENTRIES.length} additional companies for IT market (part 2)...`);
  let created = 0, existed = 0;
  for (const entry of ALL_ENTRIES) {
    const slug = slugify(entry.name);
    try {
      const company = await prisma.company.upsert({
        where: { slug_market: { slug, market } },
        update: { sector: entry.sector },
        create: { name: entry.name, slug, market, sector: entry.sector, websiteUrl: null, isActive: true },
      });
      const src = await prisma.crawlSource.findFirst({ where: { companyId: company.id } });
      if (!src) {
        await prisma.crawlSource.create({
          data: {
            companyId: company.id,
            name: `${entry.name} Lavoro`,
            type: entry.sourceType as any,
            crawlMethod: CrawlMethod.HTML,
            seedUrls: [],
            schedule: '0 3 * * *',
            agingDays: 14,
            market,
            isActive: true,
          },
        });
        created++;
      } else { existed++; }
    } catch (e: any) {
      if (e.code === 'P2002') { existed++; } else { console.error(`Error: ${entry.name}:`, e.message); }
    }
  }
  console.log(`\nDone! Created: ${created}, Already existed: ${existed}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
