import { PrismaClient, Market, Sector, SourceType, CrawlMethod } from '@prisma/client';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const prisma = new PrismaClient();

interface CompanyEntry {
  name: string;
  sector: Sector;
  sourceType: SourceType;
  websiteUrl?: string;
  seedUrls?: string[];
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const COMPANIES: CompanyEntry[] = [
  // ========== GOVERNMENT (1) ==========
  { name: 'Find a Job (DWP)', sector: 'OTHER' as Sector, sourceType: 'GOVERNMENT' as SourceType, websiteUrl: 'https://www.gov.uk/find-a-job', seedUrls: ['https://findajob.dwp.gov.uk/'] },

  // ========== LOGISTICS_TRANSPORTATION (50) ==========
  { name: 'Royal Mail', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.royalmail.com' },
  { name: 'Evri', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.evri.com' },
  { name: 'DPD', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dpd.co.uk' },
  { name: 'DHL Express', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dhl.co.uk' },
  { name: 'UPS', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ups.com/gb' },
  { name: 'FedEx', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.fedex.com/en-gb' },
  { name: 'Yodel', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.yodel.co.uk' },
  { name: 'Parcelforce', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.parcelforce.com' },
  { name: 'XPO Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.xpo.com' },
  { name: 'Wincanton', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.wincanton.co.uk' },
  { name: 'Eddie Stobart', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.eddiestobart.com' },
  { name: 'Clipper Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.clippergroup.co.uk' },
  { name: 'Bibby Distribution', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bibbydist.co.uk' },
  { name: 'GXO Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gxo.com' },
  { name: 'Palletways', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.palletways.com' },
  { name: 'Kuehne+Nagel', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.kuehne-nagel.com' },
  { name: 'CEVA Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.cevalogistics.com' },
  { name: 'DB Schenker', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dbschenker.com/gb-en' },
  { name: 'TNT', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tnt.com/express/en_gb' },
  { name: 'Rhenus Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.rhenus.com/gb/en' },
  { name: 'Hermes (Evri Legacy)', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.evri.com' },
  { name: 'Amazon Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://logistics.amazon.co.uk' },
  { name: 'Ocado Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ocado.com' },
  { name: 'Stagecoach', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.stagecoachgroup.com' },
  { name: 'First Bus', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.firstbus.co.uk' },
  { name: 'Arriva', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.arriva.co.uk' },
  { name: 'National Express', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.nationalexpress.com' },
  { name: 'Go-Ahead Group', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.go-ahead.com' },
  { name: 'Transport for London', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://tfl.gov.uk' },
  { name: 'Network Rail', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.networkrail.co.uk' },
  { name: 'Avanti West Coast', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.avantiwestcoast.co.uk' },
  { name: 'LNER', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.lner.co.uk' },
  { name: 'Great Western Railway', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gwr.com' },
  { name: 'CrossCountry', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.crosscountrytrains.co.uk' },
  { name: 'Southeastern Railway', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.southeasternrailway.co.uk' },
  { name: 'Northern Trains', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.northernrailway.co.uk' },
  { name: 'ScotRail', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.scotrail.co.uk' },
  { name: 'Stobart Group', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.stobartgroup.com' },
  { name: 'Gregory Distribution', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gregorydistribution.com' },
  { name: 'Hovis (logistics)', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.hovis.co.uk' },
  { name: 'Aggregate Industries', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.aggregate.com' },
  { name: 'Howard Tenens', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.howardtenens.co.uk' },
  { name: 'Turners Group', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.turnersgroup.co.uk' },
  { name: 'Abbey Logistics', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.abbeylogisticsgroup.com' },
  { name: 'Culina Group', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.culina.co.uk' },
  { name: 'Fowler Welch', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.fowlerwelch.co.uk' },
  { name: 'Pall-Ex', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.pallex.co.uk' },
  { name: 'Manfreight', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.manfreight.com' },
  { name: 'Maritime Transport', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.maritimetransport.com' },
  { name: 'Freight Transport Association', sector: 'LOGISTICS_TRANSPORTATION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://logistics.org.uk' },

  // ========== MANUFACTURING (50) ==========
  { name: 'BAE Systems', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.baesystems.com' },
  { name: 'Rolls-Royce', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.rolls-royce.com' },
  { name: 'JCB', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jcb.com' },
  { name: 'Dyson', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dyson.co.uk' },
  { name: 'Jaguar Land Rover', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jaguarlandrover.com' },
  { name: 'Nissan Sunderland', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.nissan.co.uk' },
  { name: 'Toyota Derbyshire', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.toyota.co.uk' },
  { name: 'Airbus Broughton', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.airbus.com' },
  { name: 'GlaxoSmithKline', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gsk.com' },
  { name: 'AstraZeneca', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.astrazeneca.co.uk' },
  { name: 'Unilever', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.unilever.co.uk' },
  { name: 'Reckitt', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.reckitt.com' },
  { name: 'Siemens', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.siemens.com/uk' },
  { name: 'Caterpillar', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.caterpillar.com' },
  { name: 'Tata Steel', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tatasteeleurope.com' },
  { name: 'Liberty Steel', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://libertysteelgroup.com' },
  { name: 'British Steel', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://britishsteel.co.uk' },
  { name: 'Mondi Group', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mondigroup.com' },
  { name: 'DS Smith', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dssmith.com' },
  { name: 'Smurfit Kappa', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.smurfitkappa.com' },
  { name: 'Diageo', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.diageo.com' },
  { name: 'Coca-Cola Europacific Partners', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.cocacolaep.com' },
  { name: 'Britvic', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.britvic.com' },
  { name: 'Nestlé UK', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.nestle.co.uk' },
  { name: 'Mars Wrigley', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mars.com' },
  { name: 'Mondelez International', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mondelezinternational.com' },
  { name: 'Premier Foods', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.premierfoods.co.uk' },
  { name: 'Associated British Foods', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.abf.co.uk' },
  { name: 'Müller UK', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.muller.co.uk' },
  { name: 'Arla Foods', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.arlafoods.co.uk' },
  { name: 'Warburtons', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.warburtons.co.uk' },
  { name: 'Kimberly-Clark', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.kimberly-clark.com' },
  { name: 'Smith & Nephew', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.smith-nephew.com' },
  { name: 'Renishaw', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.renishaw.com' },
  { name: 'Spirax-Sarco', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.spiraxsarcoengineering.com' },
  { name: 'IMI plc', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.imiplc.com' },
  { name: 'Smiths Group', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.smiths.com' },
  { name: 'GKN Aerospace', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gknaerospace.com' },
  { name: 'Meggitt', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.meggitt.com' },
  { name: 'Cobham Advanced Electronic Solutions', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.cobham.com' },
  { name: 'Ultra Electronics', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ultra.group' },
  { name: 'Thales UK', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.thalesgroup.com/en/countries/europe/united-kingdom' },
  { name: 'Leonardo UK', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://uk.leonardo.com' },
  { name: 'MBDA', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mbda-systems.com' },
  { name: 'Raytheon UK', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.rtx.com' },
  { name: 'Procter & Gamble', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.pg.co.uk' },
  { name: 'Crown Holdings', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.crowncork.com' },
  { name: 'SIG plc', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.sigplc.com' },
  { name: 'Morgan Advanced Materials', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.morganadvancedmaterials.com' },
  { name: 'Vesuvius', sector: 'MANUFACTURING' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.vesuvius.com' },

  // ========== RETAIL (50) ==========
  { name: 'Tesco', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tesco.com' },
  { name: "Sainsbury's", sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.sainsburys.co.uk' },
  { name: 'Asda', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.asda.com' },
  { name: 'Morrisons', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.morrisons.com' },
  { name: 'Aldi', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.aldi.co.uk' },
  { name: 'Lidl', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.lidl.co.uk' },
  { name: 'Marks & Spencer', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.marksandspencer.com' },
  { name: 'Co-op', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.coop.co.uk' },
  { name: 'Waitrose', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.waitrose.com' },
  { name: 'Iceland', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.iceland.co.uk' },
  { name: 'B&Q', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.diy.com' },
  { name: 'Screwfix', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.screwfix.com' },
  { name: 'Argos', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.argos.co.uk' },
  { name: 'Primark', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.primark.com' },
  { name: 'Next', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.next.co.uk' },
  { name: 'Sports Direct', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.sportsdirect.com' },
  { name: 'Wilko', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.wilko.com' },
  { name: 'Poundland', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.poundland.co.uk' },
  { name: 'Home Bargains', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.homebargains.co.uk' },
  { name: 'B&M', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bmstores.co.uk' },
  { name: 'The Range', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.therange.co.uk' },
  { name: 'Wickes', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.wickes.co.uk' },
  { name: 'Halfords', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.halfords.com' },
  { name: 'Currys', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.currys.co.uk' },
  { name: 'John Lewis', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.johnlewis.com' },
  { name: 'Debenhams', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.debenhams.com' },
  { name: 'TK Maxx', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tkmaxx.com' },
  { name: 'WHSmith', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.whsmith.co.uk' },
  { name: 'Boots', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.boots.com' },
  { name: 'Superdrug', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.superdrug.com' },
  { name: 'Holland & Barrett', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.hollandandbarrett.com' },
  { name: 'Pets at Home', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.petsathome.com' },
  { name: 'Dunelm', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dunelm.com' },
  { name: 'IKEA', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ikea.com/gb' },
  { name: 'Homebase', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.homebase.co.uk' },
  { name: 'Matalan', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.matalan.co.uk' },
  { name: 'New Look', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.newlook.com' },
  { name: 'River Island', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.riverisland.com' },
  { name: 'Shoe Zone', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.shoezone.com' },
  { name: 'Card Factory', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.cardfactory.co.uk' },
  { name: 'Greggs (Retail)', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.greggs.co.uk' },
  { name: 'Farmfoods', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.farmfoods.co.uk' },
  { name: 'Heron Foods', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.heronfoods.com' },
  { name: 'Costco UK', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.costco.co.uk' },
  { name: 'Smyths Toys', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.smythstoys.com' },
  { name: 'Robert Dyas', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.robertdyas.co.uk' },
  { name: 'Toolstation', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.toolstation.com' },
  { name: 'Travis Perkins', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.travisperkins.co.uk' },
  { name: 'Jewson', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jewson.co.uk' },
  { name: 'Selco Builders Warehouse', sector: 'RETAIL' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.selcobw.com' },

  // ========== CONSTRUCTION (50) ==========
  { name: 'Balfour Beatty', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.balfourbeatty.com' },
  { name: 'Kier Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.kier.co.uk' },
  { name: 'Morgan Sindall', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.morgansindall.com' },
  { name: 'Taylor Wimpey', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.taylorwimpey.co.uk' },
  { name: 'Barratt Developments', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.barrattdevelopments.co.uk' },
  { name: 'Persimmon', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.persimmonhomes.com' },
  { name: 'Skanska UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.skanska.co.uk' },
  { name: "Laing O'Rourke", sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.laingorourke.com' },
  { name: 'Costain', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.costain.com' },
  { name: 'Galliford Try', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gallifordtry.co.uk' },
  { name: 'Wates Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.wates.co.uk' },
  { name: 'Willmott Dixon', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.willmottdixon.co.uk' },
  { name: 'McLaren Construction', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mclarenconstruction.com' },
  { name: 'Mace Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.macegroup.com' },
  { name: 'ISG', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.isgltd.com' },
  { name: 'BAM Construct UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bam.co.uk' },
  { name: 'Vistry Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.vistrygroup.co.uk' },
  { name: 'Bellway', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bellway.co.uk' },
  { name: 'Crest Nicholson', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.crestnicholson.com' },
  { name: 'Redrow', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.redrow.co.uk' },
  { name: 'Berkeley Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.berkeleygroup.co.uk' },
  { name: 'Countryside Partnerships', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.countrysideproperties.com' },
  { name: 'Henry Boot', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.henryboot.co.uk' },
  { name: 'Multiplex', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.multiplex.global' },
  { name: 'Sir Robert McAlpine', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.srm.com' },
  { name: 'Bouygues UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bouygues-uk.com' },
  { name: 'Amey', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.amey.co.uk' },
  { name: 'Interserve', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.interserve.com' },
  { name: 'Murphy Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.murphygroup.com' },
  { name: 'VolkerWessels UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.volkerwessels.co.uk' },
  { name: 'John Sisk & Son', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.johnsiskandson.com' },
  { name: 'Robertson Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.robertson.co.uk' },
  { name: 'Tilbury Douglas', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tilburydouglas.co.uk' },
  { name: 'Graham Construction', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.graham.co.uk' },
  { name: 'Seddon Construction', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.seddon.co.uk' },
  { name: 'Bowmer & Kirkland', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bandk.co.uk' },
  { name: 'McAleer & Rushe', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mcaleer-rushe.co.uk' },
  { name: 'Ardmore Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ardmoregroup.com' },
  { name: 'Higgins Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.higginsgroup.co.uk' },
  { name: 'Durkan', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.durkan.co.uk' },
  { name: 'Engie UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.engie.co.uk' },
  { name: 'Mitie', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mitie.com' },
  { name: 'Travis Perkins Construction', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.travisperkins.co.uk' },
  { name: 'Ibstock', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ibstock.co.uk' },
  { name: 'Forterra', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.forterra.co.uk' },
  { name: 'Marshalls', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.marshalls.co.uk' },
  { name: 'Breedon Group', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.breedongroup.com' },
  { name: 'Tarmac', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tarmac.com' },
  { name: 'Hanson UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.hanson.co.uk' },
  { name: 'CEMEX UK', sector: 'CONSTRUCTION' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.cemex.co.uk' },

  // ========== FOOD_BEVERAGE (50) ==========
  { name: "McDonald's", sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mcdonalds.com/gb/en-gb.html' },
  { name: 'KFC', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.kfc.co.uk' },
  { name: 'Burger King', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.burgerking.co.uk' },
  { name: "Nando's", sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.nandos.co.uk' },
  { name: 'Greggs', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.greggs.co.uk' },
  { name: 'Costa Coffee', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.costa.co.uk' },
  { name: 'Starbucks', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.starbucks.co.uk' },
  { name: 'Pret A Manger', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.pret.co.uk' },
  { name: "Domino's Pizza", sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dominos.co.uk' },
  { name: 'Pizza Hut', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.pizzahut.co.uk' },
  { name: 'Wagamama', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.wagamama.com' },
  { name: 'Five Guys', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.fiveguys.co.uk' },
  { name: 'Subway', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.subway.com/en-GB' },
  { name: 'Wetherspoons', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jdwetherspoon.com' },
  { name: 'Harvester', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.harvester.co.uk' },
  { name: 'Toby Carvery', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tobycarvery.co.uk' },
  { name: 'Pizza Express', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.pizzaexpress.com' },
  { name: "Frankie & Benny's", sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.frankieandbennys.com' },
  { name: 'TGI Fridays', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tgifridays.co.uk' },
  { name: 'Prezzo', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.prezzorestaurants.co.uk' },
  { name: 'Zizzi', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.zizzi.co.uk' },
  { name: "ASK Italian", sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.askitalian.co.uk' },
  { name: 'Yo! Sushi', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://yosushi.com' },
  { name: 'Leon', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://leon.co' },
  { name: 'Itsu', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.itsu.com' },
  { name: 'Cafe Rouge', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.caferouge.com' },
  { name: 'Bella Italia', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bellaitalia.co.uk' },
  { name: 'Byron Burger', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.byronhamburgers.com' },
  { name: 'GBK (Gourmet Burger Kitchen)', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gbk.co.uk' },
  { name: 'Honest Burgers', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.honestburgers.co.uk' },
  { name: 'Mitchells & Butlers', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mbplc.com' },
  { name: 'Greene King', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.greeneking.co.uk' },
  { name: 'Marston\'s', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.marstons.co.uk' },
  { name: 'Stonegate Pub Company', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.stonegatepubs.com' },
  { name: 'Young\'s Pubs', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.youngs.co.uk' },
  { name: 'Fuller\'s', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.fullers.co.uk' },
  { name: 'Whitbread', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.whitbread.co.uk' },
  { name: 'Compass Group', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.compass-group.co.uk' },
  { name: 'Sodexo', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://uk.sodexo.com' },
  { name: 'Aramark UK', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.aramark.co.uk' },
  { name: 'Elior UK', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.elior.co.uk' },
  { name: 'Boparan Restaurant Group', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bfrg.co.uk' },
  { name: 'The Restaurant Group', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.trgplc.com' },
  { name: 'Deliveroo', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://deliveroo.co.uk' },
  { name: 'Just Eat', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.just-eat.co.uk' },
  { name: 'Uber Eats', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ubereats.com/gb' },
  { name: 'Tortilla', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tortilla.co.uk' },
  { name: 'Dishoom', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.dishoom.com' },
  { name: 'Côte Brasserie', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.cote.co.uk' },
  { name: 'Bill\'s Restaurants', sector: 'FOOD_BEVERAGE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bills-website.co.uk' },

  // ========== AUTOMOTIVE (50) ==========
  { name: 'Jaguar Land Rover (Automotive)', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jaguarlandrover.com' },
  { name: 'Nissan Motor Manufacturing UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.nissan.co.uk' },
  { name: 'Toyota Manufacturing UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.toyota.co.uk' },
  { name: 'BMW Mini Oxford', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mini.co.uk' },
  { name: 'Bentley Motors', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bentleymotors.com' },
  { name: 'Aston Martin', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.astonmartin.com' },
  { name: 'Honda UK Manufacturing', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.honda.co.uk' },
  { name: 'Vauxhall (Stellantis)', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.vauxhall.co.uk' },
  { name: 'Ford Dagenham', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.ford.co.uk' },
  { name: 'McLaren Automotive', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.mclaren.com' },
  { name: 'Lotus Cars', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.lotuscars.com' },
  { name: 'Morgan Motor Company', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.morgan-motor.com' },
  { name: 'Caterham Cars', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.caterhamcars.com' },
  { name: 'Rolls-Royce Motor Cars', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.rolls-roycemotorcars.com' },
  { name: 'Leyland Trucks', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.leylandtrucksltd.co.uk' },
  { name: 'Alexander Dennis', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.alexander-dennis.com' },
  { name: 'Wrightbus', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://wrightbus.com' },
  { name: 'Optare', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.optare.com' },
  { name: 'ARRIVAL', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://arrival.com' },
  { name: 'Tevva', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.tevva.com' },
  { name: 'LEVC (London EV Company)', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.levc.com' },
  { name: 'Halfords Autocentre', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.halfords.com/motoring' },
  { name: 'Kwik Fit', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.kwik-fit.com' },
  { name: 'ATS Euromaster', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.atseuromaster.co.uk' },
  { name: 'National Tyres', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.national.co.uk' },
  { name: 'Arnold Clark', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.arnoldclark.com' },
  { name: 'Sytner Group', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.sytner.co.uk' },
  { name: 'Pendragon', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.pendragon.co.uk' },
  { name: 'Lookers', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.lookers.co.uk' },
  { name: 'Inchcape', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.inchcape.com' },
  { name: 'Vertu Motors', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.vertumotors.com' },
  { name: 'Jardine Motors', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jardinemotors.co.uk' },
  { name: 'Marshall Motor Group', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.marshall.co.uk' },
  { name: 'JCT600', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.jct600.co.uk' },
  { name: 'TrustFord', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.trustford.co.uk' },
  { name: 'Peter Vardy', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.petervardy.com' },
  { name: 'Stoneacre Motor Group', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.stoneacre.co.uk' },
  { name: 'RAC', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.rac.co.uk' },
  { name: 'AA (Automobile Association)', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.theaa.com' },
  { name: 'Green Flag', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.greenflag.com' },
  { name: 'Bridgestone UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.bridgestone.co.uk' },
  { name: 'Michelin UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.michelin.co.uk' },
  { name: 'Continental UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.continental-tyres.co.uk' },
  { name: 'GKN Automotive', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.gknautomotive.com' },
  { name: 'Magna International UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.magna.com' },
  { name: 'ZF Group UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.zf.com/uk' },
  { name: 'Schaeffler UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.schaeffler.co.uk' },
  { name: 'BorgWarner UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.borgwarner.com' },
  { name: 'Delphi Technologies UK', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.delphiaftermarket.com' },
  { name: 'Unipart Group', sector: 'AUTOMOTIVE' as Sector, sourceType: 'COMPANY_CAREER' as SourceType, websiteUrl: 'https://www.unipart.com' },

